/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dma_address_generator(clk, rst, load, increment, src_addr_in, dst_addr_in, src_addr, dst_addr);
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  input clk;
  wire clk;
  output [31:0] dst_addr;
  reg [31:0] dst_addr;
  input [31:0] dst_addr_in;
  wire [31:0] dst_addr_in;
  input increment;
  wire increment;
  input load;
  wire load;
  input rst;
  wire rst;
  output [31:0] src_addr;
  reg [31:0] src_addr;
  input [31:0] src_addr_in;
  wire [31:0] src_addr_in;
  INV_X1 _211_ (
    .A(load),
    .ZN(_004_)
  );
  INV_X1 _212_ (
    .A(src_addr[5]),
    .ZN(_005_)
  );
  INV_X1 _213_ (
    .A(src_addr[15]),
    .ZN(_006_)
  );
  INV_X1 _214_ (
    .A(src_addr[16]),
    .ZN(_007_)
  );
  INV_X1 _215_ (
    .A(src_addr[17]),
    .ZN(_008_)
  );
  INV_X1 _216_ (
    .A(src_addr[21]),
    .ZN(_009_)
  );
  INV_X1 _217_ (
    .A(src_addr[22]),
    .ZN(_010_)
  );
  INV_X1 _218_ (
    .A(src_addr[23]),
    .ZN(_011_)
  );
  INV_X1 _219_ (
    .A(dst_addr[5]),
    .ZN(_012_)
  );
  INV_X1 _220_ (
    .A(dst_addr[15]),
    .ZN(_013_)
  );
  INV_X1 _221_ (
    .A(dst_addr[16]),
    .ZN(_014_)
  );
  INV_X1 _222_ (
    .A(dst_addr[17]),
    .ZN(_015_)
  );
  INV_X1 _223_ (
    .A(dst_addr[21]),
    .ZN(_016_)
  );
  INV_X1 _224_ (
    .A(dst_addr[22]),
    .ZN(_017_)
  );
  INV_X1 _225_ (
    .A(dst_addr[23]),
    .ZN(_018_)
  );
  OR2_X1 _226_ (
    .A1(increment),
    .A2(load),
    .ZN(_002_)
  );
  AND2_X1 _227_ (
    .A1(load),
    .A2(src_addr_in[0]),
    .ZN(_001_[0])
  );
  AND2_X1 _228_ (
    .A1(load),
    .A2(src_addr_in[1]),
    .ZN(_001_[1])
  );
  AND2_X1 _229_ (
    .A1(increment),
    .A2(_004_),
    .ZN(_019_)
  );
  NAND2_X1 _230_ (
    .A1(increment),
    .A2(_004_),
    .ZN(_020_)
  );
  NAND2_X1 _231_ (
    .A1(load),
    .A2(src_addr_in[2]),
    .ZN(_021_)
  );
  OAI21_X1 _232_ (
    .A(_021_),
    .B1(_020_),
    .B2(src_addr[2]),
    .ZN(_001_[2])
  );
  OAI21_X1 _233_ (
    .A(_019_),
    .B1(src_addr[3]),
    .B2(src_addr[2]),
    .ZN(_022_)
  );
  AOI21_X1 _234_ (
    .A(_022_),
    .B1(src_addr[3]),
    .B2(src_addr[2]),
    .ZN(_023_)
  );
  AOI21_X1 _235_ (
    .A(_023_),
    .B1(src_addr_in[3]),
    .B2(load),
    .ZN(_024_)
  );
  INV_X1 _236_ (
    .A(_024_),
    .ZN(_001_[3])
  );
  NAND2_X1 _237_ (
    .A1(load),
    .A2(src_addr_in[4]),
    .ZN(_025_)
  );
  AOI21_X1 _238_ (
    .A(src_addr[4]),
    .B1(src_addr[3]),
    .B2(src_addr[2]),
    .ZN(_026_)
  );
  NAND3_X1 _239_ (
    .A1(src_addr[2]),
    .A2(src_addr[3]),
    .A3(src_addr[4]),
    .ZN(_027_)
  );
  NAND2_X1 _240_ (
    .A1(_019_),
    .A2(_027_),
    .ZN(_028_)
  );
  OAI21_X1 _241_ (
    .A(_025_),
    .B1(_026_),
    .B2(_028_),
    .ZN(_001_[4])
  );
  NAND2_X1 _242_ (
    .A1(load),
    .A2(src_addr_in[5]),
    .ZN(_029_)
  );
  NAND2_X1 _243_ (
    .A1(_005_),
    .A2(_027_),
    .ZN(_030_)
  );
  AND4_X1 _244_ (
    .A1(src_addr[2]),
    .A2(src_addr[3]),
    .A3(src_addr[4]),
    .A4(src_addr[5]),
    .ZN(_031_)
  );
  NAND2_X1 _245_ (
    .A1(_019_),
    .A2(_030_),
    .ZN(_032_)
  );
  OAI21_X1 _246_ (
    .A(_029_),
    .B1(_031_),
    .B2(_032_),
    .ZN(_001_[5])
  );
  NAND2_X1 _247_ (
    .A1(load),
    .A2(src_addr_in[6]),
    .ZN(_033_)
  );
  AND2_X1 _248_ (
    .A1(src_addr[6]),
    .A2(_031_),
    .ZN(_034_)
  );
  OAI21_X1 _249_ (
    .A(_019_),
    .B1(_031_),
    .B2(src_addr[6]),
    .ZN(_035_)
  );
  OAI21_X1 _250_ (
    .A(_033_),
    .B1(_034_),
    .B2(_035_),
    .ZN(_001_[6])
  );
  OAI21_X1 _251_ (
    .A(_019_),
    .B1(_034_),
    .B2(src_addr[7]),
    .ZN(_036_)
  );
  AOI21_X1 _252_ (
    .A(_036_),
    .B1(_034_),
    .B2(src_addr[7]),
    .ZN(_037_)
  );
  AOI21_X1 _253_ (
    .A(_037_),
    .B1(src_addr_in[7]),
    .B2(load),
    .ZN(_038_)
  );
  INV_X1 _254_ (
    .A(_038_),
    .ZN(_001_[7])
  );
  NAND2_X1 _255_ (
    .A1(load),
    .A2(src_addr_in[8]),
    .ZN(_039_)
  );
  AOI21_X1 _256_ (
    .A(src_addr[8]),
    .B1(_034_),
    .B2(src_addr[7]),
    .ZN(_040_)
  );
  AND4_X1 _257_ (
    .A1(src_addr[6]),
    .A2(src_addr[7]),
    .A3(src_addr[8]),
    .A4(_031_),
    .ZN(_041_)
  );
  OR2_X1 _258_ (
    .A1(_020_),
    .A2(_041_),
    .ZN(_042_)
  );
  OAI21_X1 _259_ (
    .A(_039_),
    .B1(_040_),
    .B2(_042_),
    .ZN(_001_[8])
  );
  NAND2_X1 _260_ (
    .A1(load),
    .A2(src_addr_in[9]),
    .ZN(_043_)
  );
  AND2_X1 _261_ (
    .A1(src_addr[9]),
    .A2(_041_),
    .ZN(_044_)
  );
  OAI21_X1 _262_ (
    .A(_019_),
    .B1(_041_),
    .B2(src_addr[9]),
    .ZN(_045_)
  );
  OAI21_X1 _263_ (
    .A(_043_),
    .B1(_044_),
    .B2(_045_),
    .ZN(_001_[9])
  );
  NAND2_X1 _264_ (
    .A1(load),
    .A2(src_addr_in[10]),
    .ZN(_046_)
  );
  AND2_X1 _265_ (
    .A1(src_addr[10]),
    .A2(_044_),
    .ZN(_047_)
  );
  OAI21_X1 _266_ (
    .A(_019_),
    .B1(_044_),
    .B2(src_addr[10]),
    .ZN(_048_)
  );
  OAI21_X1 _267_ (
    .A(_046_),
    .B1(_047_),
    .B2(_048_),
    .ZN(_001_[10])
  );
  NAND2_X1 _268_ (
    .A1(load),
    .A2(src_addr_in[11]),
    .ZN(_049_)
  );
  AND4_X1 _269_ (
    .A1(src_addr[9]),
    .A2(src_addr[10]),
    .A3(src_addr[11]),
    .A4(_041_),
    .ZN(_050_)
  );
  OAI21_X1 _270_ (
    .A(_019_),
    .B1(_047_),
    .B2(src_addr[11]),
    .ZN(_051_)
  );
  OAI21_X1 _271_ (
    .A(_049_),
    .B1(_050_),
    .B2(_051_),
    .ZN(_001_[11])
  );
  NAND2_X1 _272_ (
    .A1(load),
    .A2(src_addr_in[12]),
    .ZN(_052_)
  );
  AND2_X1 _273_ (
    .A1(src_addr[12]),
    .A2(_050_),
    .ZN(_053_)
  );
  OAI21_X1 _274_ (
    .A(_019_),
    .B1(_050_),
    .B2(src_addr[12]),
    .ZN(_054_)
  );
  OAI21_X1 _275_ (
    .A(_052_),
    .B1(_053_),
    .B2(_054_),
    .ZN(_001_[12])
  );
  NAND2_X1 _276_ (
    .A1(load),
    .A2(src_addr_in[13]),
    .ZN(_055_)
  );
  AND2_X1 _277_ (
    .A1(src_addr[13]),
    .A2(_053_),
    .ZN(_056_)
  );
  OAI21_X1 _278_ (
    .A(_019_),
    .B1(_053_),
    .B2(src_addr[13]),
    .ZN(_057_)
  );
  OAI21_X1 _279_ (
    .A(_055_),
    .B1(_056_),
    .B2(_057_),
    .ZN(_001_[13])
  );
  NAND2_X1 _280_ (
    .A1(load),
    .A2(src_addr_in[14]),
    .ZN(_058_)
  );
  NOR2_X1 _281_ (
    .A1(src_addr[14]),
    .A2(_056_),
    .ZN(_059_)
  );
  NAND4_X1 _282_ (
    .A1(src_addr[12]),
    .A2(src_addr[13]),
    .A3(src_addr[14]),
    .A4(_050_),
    .ZN(_060_)
  );
  NAND2_X1 _283_ (
    .A1(_019_),
    .A2(_060_),
    .ZN(_061_)
  );
  OAI21_X1 _284_ (
    .A(_058_),
    .B1(_059_),
    .B2(_061_),
    .ZN(_001_[14])
  );
  NAND2_X1 _285_ (
    .A1(load),
    .A2(src_addr_in[15]),
    .ZN(_062_)
  );
  NAND2_X1 _286_ (
    .A1(_006_),
    .A2(_060_),
    .ZN(_063_)
  );
  NOR2_X1 _287_ (
    .A1(_006_),
    .A2(_060_),
    .ZN(_064_)
  );
  NAND2_X1 _288_ (
    .A1(_019_),
    .A2(_063_),
    .ZN(_065_)
  );
  OAI21_X1 _289_ (
    .A(_062_),
    .B1(_064_),
    .B2(_065_),
    .ZN(_001_[15])
  );
  NAND2_X1 _290_ (
    .A1(load),
    .A2(src_addr_in[16]),
    .ZN(_066_)
  );
  NOR3_X1 _291_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_060_),
    .ZN(_067_)
  );
  OAI21_X1 _292_ (
    .A(_019_),
    .B1(_064_),
    .B2(src_addr[16]),
    .ZN(_068_)
  );
  OAI21_X1 _293_ (
    .A(_066_),
    .B1(_067_),
    .B2(_068_),
    .ZN(_001_[16])
  );
  NAND2_X1 _294_ (
    .A1(load),
    .A2(src_addr_in[17]),
    .ZN(_069_)
  );
  NOR4_X1 _295_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_008_),
    .A4(_060_),
    .ZN(_070_)
  );
  OAI21_X1 _296_ (
    .A(_019_),
    .B1(_067_),
    .B2(src_addr[17]),
    .ZN(_071_)
  );
  OAI21_X1 _297_ (
    .A(_069_),
    .B1(_070_),
    .B2(_071_),
    .ZN(_001_[17])
  );
  NAND2_X1 _298_ (
    .A1(load),
    .A2(src_addr_in[18]),
    .ZN(_072_)
  );
  AND2_X1 _299_ (
    .A1(src_addr[18]),
    .A2(_070_),
    .ZN(_073_)
  );
  OAI21_X1 _300_ (
    .A(_019_),
    .B1(_070_),
    .B2(src_addr[18]),
    .ZN(_074_)
  );
  OAI21_X1 _301_ (
    .A(_072_),
    .B1(_073_),
    .B2(_074_),
    .ZN(_001_[18])
  );
  NAND2_X1 _302_ (
    .A1(load),
    .A2(src_addr_in[19]),
    .ZN(_075_)
  );
  AND2_X1 _303_ (
    .A1(src_addr[19]),
    .A2(_073_),
    .ZN(_076_)
  );
  OAI21_X1 _304_ (
    .A(_019_),
    .B1(_073_),
    .B2(src_addr[19]),
    .ZN(_077_)
  );
  OAI21_X1 _305_ (
    .A(_075_),
    .B1(_076_),
    .B2(_077_),
    .ZN(_001_[19])
  );
  NAND2_X1 _306_ (
    .A1(load),
    .A2(src_addr_in[20]),
    .ZN(_078_)
  );
  NOR2_X1 _307_ (
    .A1(src_addr[20]),
    .A2(_076_),
    .ZN(_079_)
  );
  NAND4_X1 _308_ (
    .A1(src_addr[18]),
    .A2(src_addr[19]),
    .A3(src_addr[20]),
    .A4(_070_),
    .ZN(_080_)
  );
  NAND2_X1 _309_ (
    .A1(_019_),
    .A2(_080_),
    .ZN(_081_)
  );
  OAI21_X1 _310_ (
    .A(_078_),
    .B1(_079_),
    .B2(_081_),
    .ZN(_001_[20])
  );
  NAND2_X1 _311_ (
    .A1(load),
    .A2(src_addr_in[21]),
    .ZN(_082_)
  );
  NAND2_X1 _312_ (
    .A1(_009_),
    .A2(_080_),
    .ZN(_083_)
  );
  NOR2_X1 _313_ (
    .A1(_009_),
    .A2(_080_),
    .ZN(_084_)
  );
  NAND2_X1 _314_ (
    .A1(_019_),
    .A2(_083_),
    .ZN(_085_)
  );
  OAI21_X1 _315_ (
    .A(_082_),
    .B1(_084_),
    .B2(_085_),
    .ZN(_001_[21])
  );
  NAND2_X1 _316_ (
    .A1(load),
    .A2(src_addr_in[22]),
    .ZN(_086_)
  );
  NOR3_X1 _317_ (
    .A1(_009_),
    .A2(_010_),
    .A3(_080_),
    .ZN(_087_)
  );
  OAI21_X1 _318_ (
    .A(_019_),
    .B1(_084_),
    .B2(src_addr[22]),
    .ZN(_088_)
  );
  OAI21_X1 _319_ (
    .A(_086_),
    .B1(_087_),
    .B2(_088_),
    .ZN(_001_[22])
  );
  NAND2_X1 _320_ (
    .A1(load),
    .A2(src_addr_in[23]),
    .ZN(_089_)
  );
  NOR4_X1 _321_ (
    .A1(_009_),
    .A2(_010_),
    .A3(_011_),
    .A4(_080_),
    .ZN(_090_)
  );
  OAI21_X1 _322_ (
    .A(_019_),
    .B1(_087_),
    .B2(src_addr[23]),
    .ZN(_091_)
  );
  OAI21_X1 _323_ (
    .A(_089_),
    .B1(_090_),
    .B2(_091_),
    .ZN(_001_[23])
  );
  NAND2_X1 _324_ (
    .A1(load),
    .A2(src_addr_in[24]),
    .ZN(_092_)
  );
  AND2_X1 _325_ (
    .A1(src_addr[24]),
    .A2(_090_),
    .ZN(_093_)
  );
  OAI21_X1 _326_ (
    .A(_019_),
    .B1(_090_),
    .B2(src_addr[24]),
    .ZN(_094_)
  );
  OAI21_X1 _327_ (
    .A(_092_),
    .B1(_093_),
    .B2(_094_),
    .ZN(_001_[24])
  );
  NAND2_X1 _328_ (
    .A1(load),
    .A2(src_addr_in[25]),
    .ZN(_095_)
  );
  AND2_X1 _329_ (
    .A1(src_addr[25]),
    .A2(_093_),
    .ZN(_096_)
  );
  OAI21_X1 _330_ (
    .A(_019_),
    .B1(_093_),
    .B2(src_addr[25]),
    .ZN(_097_)
  );
  OAI21_X1 _331_ (
    .A(_095_),
    .B1(_096_),
    .B2(_097_),
    .ZN(_001_[25])
  );
  NAND2_X1 _332_ (
    .A1(load),
    .A2(src_addr_in[26]),
    .ZN(_098_)
  );
  AND2_X1 _333_ (
    .A1(src_addr[26]),
    .A2(_096_),
    .ZN(_099_)
  );
  OAI21_X1 _334_ (
    .A(_019_),
    .B1(_096_),
    .B2(src_addr[26]),
    .ZN(_100_)
  );
  OAI21_X1 _335_ (
    .A(_098_),
    .B1(_099_),
    .B2(_100_),
    .ZN(_001_[26])
  );
  NAND2_X1 _336_ (
    .A1(load),
    .A2(src_addr_in[27]),
    .ZN(_101_)
  );
  AND4_X1 _337_ (
    .A1(src_addr[25]),
    .A2(src_addr[26]),
    .A3(src_addr[27]),
    .A4(_093_),
    .ZN(_102_)
  );
  OAI21_X1 _338_ (
    .A(_019_),
    .B1(_099_),
    .B2(src_addr[27]),
    .ZN(_103_)
  );
  OAI21_X1 _339_ (
    .A(_101_),
    .B1(_102_),
    .B2(_103_),
    .ZN(_001_[27])
  );
  NAND2_X1 _340_ (
    .A1(load),
    .A2(src_addr_in[28]),
    .ZN(_104_)
  );
  AND2_X1 _341_ (
    .A1(src_addr[28]),
    .A2(_102_),
    .ZN(_105_)
  );
  OAI21_X1 _342_ (
    .A(_019_),
    .B1(_102_),
    .B2(src_addr[28]),
    .ZN(_106_)
  );
  OAI21_X1 _343_ (
    .A(_104_),
    .B1(_105_),
    .B2(_106_),
    .ZN(_001_[28])
  );
  NAND2_X1 _344_ (
    .A1(load),
    .A2(src_addr_in[29]),
    .ZN(_107_)
  );
  AND3_X1 _345_ (
    .A1(src_addr[28]),
    .A2(src_addr[29]),
    .A3(_102_),
    .ZN(_108_)
  );
  OAI21_X1 _346_ (
    .A(_019_),
    .B1(_105_),
    .B2(src_addr[29]),
    .ZN(_109_)
  );
  OAI21_X1 _347_ (
    .A(_107_),
    .B1(_108_),
    .B2(_109_),
    .ZN(_001_[29])
  );
  NAND2_X1 _348_ (
    .A1(load),
    .A2(src_addr_in[30]),
    .ZN(_110_)
  );
  AND4_X1 _349_ (
    .A1(src_addr[28]),
    .A2(src_addr[29]),
    .A3(src_addr[30]),
    .A4(_102_),
    .ZN(_111_)
  );
  OAI21_X1 _350_ (
    .A(_019_),
    .B1(_108_),
    .B2(src_addr[30]),
    .ZN(_112_)
  );
  OAI21_X1 _351_ (
    .A(_110_),
    .B1(_111_),
    .B2(_112_),
    .ZN(_001_[30])
  );
  NAND2_X1 _352_ (
    .A1(load),
    .A2(src_addr_in[31]),
    .ZN(_113_)
  );
  AND2_X1 _353_ (
    .A1(src_addr[31]),
    .A2(_111_),
    .ZN(_114_)
  );
  OAI21_X1 _354_ (
    .A(_019_),
    .B1(_111_),
    .B2(src_addr[31]),
    .ZN(_115_)
  );
  OAI21_X1 _355_ (
    .A(_113_),
    .B1(_114_),
    .B2(_115_),
    .ZN(_001_[31])
  );
  AND2_X1 _356_ (
    .A1(load),
    .A2(dst_addr_in[0]),
    .ZN(_000_[0])
  );
  AND2_X1 _357_ (
    .A1(load),
    .A2(dst_addr_in[1]),
    .ZN(_000_[1])
  );
  NAND2_X1 _358_ (
    .A1(load),
    .A2(dst_addr_in[2]),
    .ZN(_116_)
  );
  OAI21_X1 _359_ (
    .A(_116_),
    .B1(_020_),
    .B2(dst_addr[2]),
    .ZN(_000_[2])
  );
  OAI21_X1 _360_ (
    .A(_019_),
    .B1(dst_addr[3]),
    .B2(dst_addr[2]),
    .ZN(_117_)
  );
  AOI21_X1 _361_ (
    .A(_117_),
    .B1(dst_addr[3]),
    .B2(dst_addr[2]),
    .ZN(_118_)
  );
  AOI21_X1 _362_ (
    .A(_118_),
    .B1(dst_addr_in[3]),
    .B2(load),
    .ZN(_119_)
  );
  INV_X1 _363_ (
    .A(_119_),
    .ZN(_000_[3])
  );
  NAND2_X1 _364_ (
    .A1(load),
    .A2(dst_addr_in[4]),
    .ZN(_120_)
  );
  AOI21_X1 _365_ (
    .A(dst_addr[4]),
    .B1(dst_addr[3]),
    .B2(dst_addr[2]),
    .ZN(_121_)
  );
  NAND3_X1 _366_ (
    .A1(dst_addr[2]),
    .A2(dst_addr[3]),
    .A3(dst_addr[4]),
    .ZN(_122_)
  );
  NAND2_X1 _367_ (
    .A1(_019_),
    .A2(_122_),
    .ZN(_123_)
  );
  OAI21_X1 _368_ (
    .A(_120_),
    .B1(_121_),
    .B2(_123_),
    .ZN(_000_[4])
  );
  NAND2_X1 _369_ (
    .A1(load),
    .A2(dst_addr_in[5]),
    .ZN(_124_)
  );
  NAND2_X1 _370_ (
    .A1(_012_),
    .A2(_122_),
    .ZN(_125_)
  );
  AND4_X1 _371_ (
    .A1(dst_addr[2]),
    .A2(dst_addr[3]),
    .A3(dst_addr[4]),
    .A4(dst_addr[5]),
    .ZN(_126_)
  );
  NAND2_X1 _372_ (
    .A1(_019_),
    .A2(_125_),
    .ZN(_127_)
  );
  OAI21_X1 _373_ (
    .A(_124_),
    .B1(_126_),
    .B2(_127_),
    .ZN(_000_[5])
  );
  NAND2_X1 _374_ (
    .A1(load),
    .A2(dst_addr_in[6]),
    .ZN(_128_)
  );
  AND2_X1 _375_ (
    .A1(dst_addr[6]),
    .A2(_126_),
    .ZN(_129_)
  );
  OAI21_X1 _376_ (
    .A(_019_),
    .B1(_126_),
    .B2(dst_addr[6]),
    .ZN(_130_)
  );
  OAI21_X1 _377_ (
    .A(_128_),
    .B1(_129_),
    .B2(_130_),
    .ZN(_000_[6])
  );
  OAI21_X1 _378_ (
    .A(_019_),
    .B1(_129_),
    .B2(dst_addr[7]),
    .ZN(_131_)
  );
  AOI21_X1 _379_ (
    .A(_131_),
    .B1(_129_),
    .B2(dst_addr[7]),
    .ZN(_132_)
  );
  AOI21_X1 _380_ (
    .A(_132_),
    .B1(dst_addr_in[7]),
    .B2(load),
    .ZN(_133_)
  );
  INV_X1 _381_ (
    .A(_133_),
    .ZN(_000_[7])
  );
  NAND2_X1 _382_ (
    .A1(load),
    .A2(dst_addr_in[8]),
    .ZN(_134_)
  );
  AOI21_X1 _383_ (
    .A(dst_addr[8]),
    .B1(_129_),
    .B2(dst_addr[7]),
    .ZN(_135_)
  );
  AND4_X1 _384_ (
    .A1(dst_addr[6]),
    .A2(dst_addr[7]),
    .A3(dst_addr[8]),
    .A4(_126_),
    .ZN(_136_)
  );
  OR2_X1 _385_ (
    .A1(_020_),
    .A2(_136_),
    .ZN(_137_)
  );
  OAI21_X1 _386_ (
    .A(_134_),
    .B1(_135_),
    .B2(_137_),
    .ZN(_000_[8])
  );
  NAND2_X1 _387_ (
    .A1(load),
    .A2(dst_addr_in[9]),
    .ZN(_138_)
  );
  AND2_X1 _388_ (
    .A1(dst_addr[9]),
    .A2(_136_),
    .ZN(_139_)
  );
  OAI21_X1 _389_ (
    .A(_019_),
    .B1(_136_),
    .B2(dst_addr[9]),
    .ZN(_140_)
  );
  OAI21_X1 _390_ (
    .A(_138_),
    .B1(_139_),
    .B2(_140_),
    .ZN(_000_[9])
  );
  NAND2_X1 _391_ (
    .A1(load),
    .A2(dst_addr_in[10]),
    .ZN(_141_)
  );
  AND2_X1 _392_ (
    .A1(dst_addr[10]),
    .A2(_139_),
    .ZN(_142_)
  );
  OAI21_X1 _393_ (
    .A(_019_),
    .B1(_139_),
    .B2(dst_addr[10]),
    .ZN(_143_)
  );
  OAI21_X1 _394_ (
    .A(_141_),
    .B1(_142_),
    .B2(_143_),
    .ZN(_000_[10])
  );
  NAND2_X1 _395_ (
    .A1(load),
    .A2(dst_addr_in[11]),
    .ZN(_144_)
  );
  AND4_X1 _396_ (
    .A1(dst_addr[9]),
    .A2(dst_addr[10]),
    .A3(dst_addr[11]),
    .A4(_136_),
    .ZN(_145_)
  );
  OAI21_X1 _397_ (
    .A(_019_),
    .B1(_142_),
    .B2(dst_addr[11]),
    .ZN(_146_)
  );
  OAI21_X1 _398_ (
    .A(_144_),
    .B1(_145_),
    .B2(_146_),
    .ZN(_000_[11])
  );
  NAND2_X1 _399_ (
    .A1(load),
    .A2(dst_addr_in[12]),
    .ZN(_147_)
  );
  AND2_X1 _400_ (
    .A1(dst_addr[12]),
    .A2(_145_),
    .ZN(_148_)
  );
  OAI21_X1 _401_ (
    .A(_019_),
    .B1(_145_),
    .B2(dst_addr[12]),
    .ZN(_149_)
  );
  OAI21_X1 _402_ (
    .A(_147_),
    .B1(_148_),
    .B2(_149_),
    .ZN(_000_[12])
  );
  NAND2_X1 _403_ (
    .A1(load),
    .A2(dst_addr_in[13]),
    .ZN(_150_)
  );
  AND2_X1 _404_ (
    .A1(dst_addr[13]),
    .A2(_148_),
    .ZN(_151_)
  );
  OAI21_X1 _405_ (
    .A(_019_),
    .B1(_148_),
    .B2(dst_addr[13]),
    .ZN(_152_)
  );
  OAI21_X1 _406_ (
    .A(_150_),
    .B1(_151_),
    .B2(_152_),
    .ZN(_000_[13])
  );
  NAND2_X1 _407_ (
    .A1(load),
    .A2(dst_addr_in[14]),
    .ZN(_153_)
  );
  NOR2_X1 _408_ (
    .A1(dst_addr[14]),
    .A2(_151_),
    .ZN(_154_)
  );
  NAND4_X1 _409_ (
    .A1(dst_addr[12]),
    .A2(dst_addr[13]),
    .A3(dst_addr[14]),
    .A4(_145_),
    .ZN(_155_)
  );
  NAND2_X1 _410_ (
    .A1(_019_),
    .A2(_155_),
    .ZN(_156_)
  );
  OAI21_X1 _411_ (
    .A(_153_),
    .B1(_154_),
    .B2(_156_),
    .ZN(_000_[14])
  );
  NAND2_X1 _412_ (
    .A1(load),
    .A2(dst_addr_in[15]),
    .ZN(_157_)
  );
  NAND2_X1 _413_ (
    .A1(_013_),
    .A2(_155_),
    .ZN(_158_)
  );
  NOR2_X1 _414_ (
    .A1(_013_),
    .A2(_155_),
    .ZN(_159_)
  );
  NAND2_X1 _415_ (
    .A1(_019_),
    .A2(_158_),
    .ZN(_160_)
  );
  OAI21_X1 _416_ (
    .A(_157_),
    .B1(_159_),
    .B2(_160_),
    .ZN(_000_[15])
  );
  NAND2_X1 _417_ (
    .A1(load),
    .A2(dst_addr_in[16]),
    .ZN(_161_)
  );
  NOR3_X1 _418_ (
    .A1(_013_),
    .A2(_014_),
    .A3(_155_),
    .ZN(_162_)
  );
  OAI21_X1 _419_ (
    .A(_019_),
    .B1(_159_),
    .B2(dst_addr[16]),
    .ZN(_163_)
  );
  OAI21_X1 _420_ (
    .A(_161_),
    .B1(_162_),
    .B2(_163_),
    .ZN(_000_[16])
  );
  NAND2_X1 _421_ (
    .A1(load),
    .A2(dst_addr_in[17]),
    .ZN(_164_)
  );
  NOR4_X1 _422_ (
    .A1(_013_),
    .A2(_014_),
    .A3(_015_),
    .A4(_155_),
    .ZN(_165_)
  );
  OAI21_X1 _423_ (
    .A(_019_),
    .B1(_162_),
    .B2(dst_addr[17]),
    .ZN(_166_)
  );
  OAI21_X1 _424_ (
    .A(_164_),
    .B1(_165_),
    .B2(_166_),
    .ZN(_000_[17])
  );
  NAND2_X1 _425_ (
    .A1(load),
    .A2(dst_addr_in[18]),
    .ZN(_167_)
  );
  AND2_X1 _426_ (
    .A1(dst_addr[18]),
    .A2(_165_),
    .ZN(_168_)
  );
  OAI21_X1 _427_ (
    .A(_019_),
    .B1(_165_),
    .B2(dst_addr[18]),
    .ZN(_169_)
  );
  OAI21_X1 _428_ (
    .A(_167_),
    .B1(_168_),
    .B2(_169_),
    .ZN(_000_[18])
  );
  NAND2_X1 _429_ (
    .A1(load),
    .A2(dst_addr_in[19]),
    .ZN(_170_)
  );
  AND2_X1 _430_ (
    .A1(dst_addr[19]),
    .A2(_168_),
    .ZN(_171_)
  );
  OAI21_X1 _431_ (
    .A(_019_),
    .B1(_168_),
    .B2(dst_addr[19]),
    .ZN(_172_)
  );
  OAI21_X1 _432_ (
    .A(_170_),
    .B1(_171_),
    .B2(_172_),
    .ZN(_000_[19])
  );
  NAND2_X1 _433_ (
    .A1(load),
    .A2(dst_addr_in[20]),
    .ZN(_173_)
  );
  NOR2_X1 _434_ (
    .A1(dst_addr[20]),
    .A2(_171_),
    .ZN(_174_)
  );
  NAND4_X1 _435_ (
    .A1(dst_addr[18]),
    .A2(dst_addr[19]),
    .A3(dst_addr[20]),
    .A4(_165_),
    .ZN(_175_)
  );
  NAND2_X1 _436_ (
    .A1(_019_),
    .A2(_175_),
    .ZN(_176_)
  );
  OAI21_X1 _437_ (
    .A(_173_),
    .B1(_174_),
    .B2(_176_),
    .ZN(_000_[20])
  );
  NAND2_X1 _438_ (
    .A1(load),
    .A2(dst_addr_in[21]),
    .ZN(_177_)
  );
  NAND2_X1 _439_ (
    .A1(_016_),
    .A2(_175_),
    .ZN(_178_)
  );
  NOR2_X1 _440_ (
    .A1(_016_),
    .A2(_175_),
    .ZN(_179_)
  );
  NAND2_X1 _441_ (
    .A1(_019_),
    .A2(_178_),
    .ZN(_180_)
  );
  OAI21_X1 _442_ (
    .A(_177_),
    .B1(_179_),
    .B2(_180_),
    .ZN(_000_[21])
  );
  NAND2_X1 _443_ (
    .A1(load),
    .A2(dst_addr_in[22]),
    .ZN(_181_)
  );
  NOR3_X1 _444_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_175_),
    .ZN(_182_)
  );
  OAI21_X1 _445_ (
    .A(_019_),
    .B1(_179_),
    .B2(dst_addr[22]),
    .ZN(_183_)
  );
  OAI21_X1 _446_ (
    .A(_181_),
    .B1(_182_),
    .B2(_183_),
    .ZN(_000_[22])
  );
  NAND2_X1 _447_ (
    .A1(load),
    .A2(dst_addr_in[23]),
    .ZN(_184_)
  );
  NOR4_X1 _448_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_018_),
    .A4(_175_),
    .ZN(_185_)
  );
  OAI21_X1 _449_ (
    .A(_019_),
    .B1(_182_),
    .B2(dst_addr[23]),
    .ZN(_186_)
  );
  OAI21_X1 _450_ (
    .A(_184_),
    .B1(_185_),
    .B2(_186_),
    .ZN(_000_[23])
  );
  NAND2_X1 _451_ (
    .A1(load),
    .A2(dst_addr_in[24]),
    .ZN(_187_)
  );
  AND2_X1 _452_ (
    .A1(dst_addr[24]),
    .A2(_185_),
    .ZN(_188_)
  );
  OAI21_X1 _453_ (
    .A(_019_),
    .B1(_185_),
    .B2(dst_addr[24]),
    .ZN(_189_)
  );
  OAI21_X1 _454_ (
    .A(_187_),
    .B1(_188_),
    .B2(_189_),
    .ZN(_000_[24])
  );
  NAND2_X1 _455_ (
    .A1(load),
    .A2(dst_addr_in[25]),
    .ZN(_190_)
  );
  AND2_X1 _456_ (
    .A1(dst_addr[25]),
    .A2(_188_),
    .ZN(_191_)
  );
  OAI21_X1 _457_ (
    .A(_019_),
    .B1(_188_),
    .B2(dst_addr[25]),
    .ZN(_192_)
  );
  OAI21_X1 _458_ (
    .A(_190_),
    .B1(_191_),
    .B2(_192_),
    .ZN(_000_[25])
  );
  NAND2_X1 _459_ (
    .A1(load),
    .A2(dst_addr_in[26]),
    .ZN(_193_)
  );
  AND2_X1 _460_ (
    .A1(dst_addr[26]),
    .A2(_191_),
    .ZN(_194_)
  );
  OAI21_X1 _461_ (
    .A(_019_),
    .B1(_191_),
    .B2(dst_addr[26]),
    .ZN(_195_)
  );
  OAI21_X1 _462_ (
    .A(_193_),
    .B1(_194_),
    .B2(_195_),
    .ZN(_000_[26])
  );
  NAND2_X1 _463_ (
    .A1(load),
    .A2(dst_addr_in[27]),
    .ZN(_196_)
  );
  AND4_X1 _464_ (
    .A1(dst_addr[25]),
    .A2(dst_addr[26]),
    .A3(dst_addr[27]),
    .A4(_188_),
    .ZN(_197_)
  );
  OAI21_X1 _465_ (
    .A(_019_),
    .B1(_194_),
    .B2(dst_addr[27]),
    .ZN(_198_)
  );
  OAI21_X1 _466_ (
    .A(_196_),
    .B1(_197_),
    .B2(_198_),
    .ZN(_000_[27])
  );
  NAND2_X1 _467_ (
    .A1(load),
    .A2(dst_addr_in[28]),
    .ZN(_199_)
  );
  AND2_X1 _468_ (
    .A1(dst_addr[28]),
    .A2(_197_),
    .ZN(_200_)
  );
  OAI21_X1 _469_ (
    .A(_019_),
    .B1(_197_),
    .B2(dst_addr[28]),
    .ZN(_201_)
  );
  OAI21_X1 _470_ (
    .A(_199_),
    .B1(_200_),
    .B2(_201_),
    .ZN(_000_[28])
  );
  NAND2_X1 _471_ (
    .A1(load),
    .A2(dst_addr_in[29]),
    .ZN(_202_)
  );
  AND3_X1 _472_ (
    .A1(dst_addr[28]),
    .A2(dst_addr[29]),
    .A3(_197_),
    .ZN(_203_)
  );
  OAI21_X1 _473_ (
    .A(_019_),
    .B1(_200_),
    .B2(dst_addr[29]),
    .ZN(_204_)
  );
  OAI21_X1 _474_ (
    .A(_202_),
    .B1(_203_),
    .B2(_204_),
    .ZN(_000_[29])
  );
  NAND2_X1 _475_ (
    .A1(load),
    .A2(dst_addr_in[30]),
    .ZN(_205_)
  );
  AND4_X1 _476_ (
    .A1(dst_addr[28]),
    .A2(dst_addr[29]),
    .A3(dst_addr[30]),
    .A4(_197_),
    .ZN(_206_)
  );
  OAI21_X1 _477_ (
    .A(_019_),
    .B1(_203_),
    .B2(dst_addr[30]),
    .ZN(_207_)
  );
  OAI21_X1 _478_ (
    .A(_205_),
    .B1(_206_),
    .B2(_207_),
    .ZN(_000_[30])
  );
  NAND2_X1 _479_ (
    .A1(load),
    .A2(dst_addr_in[31]),
    .ZN(_208_)
  );
  AND2_X1 _480_ (
    .A1(dst_addr[31]),
    .A2(_206_),
    .ZN(_209_)
  );
  OAI21_X1 _481_ (
    .A(_019_),
    .B1(_206_),
    .B2(dst_addr[31]),
    .ZN(_210_)
  );
  OAI21_X1 _482_ (
    .A(_208_),
    .B1(_209_),
    .B2(_210_),
    .ZN(_000_[31])
  );
  BUF_X1 _483_ (
    .A(load),
    .Z(_003_)
  );
  always @(posedge clk, posedge rst)
    if (rst) src_addr[2] <= 1'h0;
    else if (_002_) src_addr[2] <= _001_[2];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[3] <= 1'h0;
    else if (_002_) src_addr[3] <= _001_[3];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[4] <= 1'h0;
    else if (_002_) src_addr[4] <= _001_[4];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[5] <= 1'h0;
    else if (_002_) src_addr[5] <= _001_[5];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[6] <= 1'h0;
    else if (_002_) src_addr[6] <= _001_[6];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[7] <= 1'h0;
    else if (_002_) src_addr[7] <= _001_[7];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[8] <= 1'h0;
    else if (_002_) src_addr[8] <= _001_[8];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[9] <= 1'h0;
    else if (_002_) src_addr[9] <= _001_[9];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[10] <= 1'h0;
    else if (_002_) src_addr[10] <= _001_[10];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[11] <= 1'h0;
    else if (_002_) src_addr[11] <= _001_[11];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[12] <= 1'h0;
    else if (_002_) src_addr[12] <= _001_[12];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[13] <= 1'h0;
    else if (_002_) src_addr[13] <= _001_[13];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[14] <= 1'h0;
    else if (_002_) src_addr[14] <= _001_[14];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[15] <= 1'h0;
    else if (_002_) src_addr[15] <= _001_[15];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[16] <= 1'h0;
    else if (_002_) src_addr[16] <= _001_[16];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[17] <= 1'h0;
    else if (_002_) src_addr[17] <= _001_[17];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[18] <= 1'h0;
    else if (_002_) src_addr[18] <= _001_[18];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[19] <= 1'h0;
    else if (_002_) src_addr[19] <= _001_[19];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[20] <= 1'h0;
    else if (_002_) src_addr[20] <= _001_[20];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[21] <= 1'h0;
    else if (_002_) src_addr[21] <= _001_[21];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[22] <= 1'h0;
    else if (_002_) src_addr[22] <= _001_[22];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[23] <= 1'h0;
    else if (_002_) src_addr[23] <= _001_[23];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[24] <= 1'h0;
    else if (_002_) src_addr[24] <= _001_[24];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[25] <= 1'h0;
    else if (_002_) src_addr[25] <= _001_[25];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[26] <= 1'h0;
    else if (_002_) src_addr[26] <= _001_[26];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[27] <= 1'h0;
    else if (_002_) src_addr[27] <= _001_[27];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[28] <= 1'h0;
    else if (_002_) src_addr[28] <= _001_[28];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[29] <= 1'h0;
    else if (_002_) src_addr[29] <= _001_[29];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[30] <= 1'h0;
    else if (_002_) src_addr[30] <= _001_[30];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[31] <= 1'h0;
    else if (_002_) src_addr[31] <= _001_[31];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[2] <= 1'h0;
    else if (_002_) dst_addr[2] <= _000_[2];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[3] <= 1'h0;
    else if (_002_) dst_addr[3] <= _000_[3];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[4] <= 1'h0;
    else if (_002_) dst_addr[4] <= _000_[4];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[5] <= 1'h0;
    else if (_002_) dst_addr[5] <= _000_[5];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[6] <= 1'h0;
    else if (_002_) dst_addr[6] <= _000_[6];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[7] <= 1'h0;
    else if (_002_) dst_addr[7] <= _000_[7];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[8] <= 1'h0;
    else if (_002_) dst_addr[8] <= _000_[8];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[9] <= 1'h0;
    else if (_002_) dst_addr[9] <= _000_[9];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[10] <= 1'h0;
    else if (_002_) dst_addr[10] <= _000_[10];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[11] <= 1'h0;
    else if (_002_) dst_addr[11] <= _000_[11];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[12] <= 1'h0;
    else if (_002_) dst_addr[12] <= _000_[12];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[13] <= 1'h0;
    else if (_002_) dst_addr[13] <= _000_[13];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[14] <= 1'h0;
    else if (_002_) dst_addr[14] <= _000_[14];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[15] <= 1'h0;
    else if (_002_) dst_addr[15] <= _000_[15];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[16] <= 1'h0;
    else if (_002_) dst_addr[16] <= _000_[16];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[17] <= 1'h0;
    else if (_002_) dst_addr[17] <= _000_[17];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[18] <= 1'h0;
    else if (_002_) dst_addr[18] <= _000_[18];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[19] <= 1'h0;
    else if (_002_) dst_addr[19] <= _000_[19];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[20] <= 1'h0;
    else if (_002_) dst_addr[20] <= _000_[20];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[21] <= 1'h0;
    else if (_002_) dst_addr[21] <= _000_[21];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[22] <= 1'h0;
    else if (_002_) dst_addr[22] <= _000_[22];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[23] <= 1'h0;
    else if (_002_) dst_addr[23] <= _000_[23];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[24] <= 1'h0;
    else if (_002_) dst_addr[24] <= _000_[24];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[25] <= 1'h0;
    else if (_002_) dst_addr[25] <= _000_[25];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[26] <= 1'h0;
    else if (_002_) dst_addr[26] <= _000_[26];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[27] <= 1'h0;
    else if (_002_) dst_addr[27] <= _000_[27];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[28] <= 1'h0;
    else if (_002_) dst_addr[28] <= _000_[28];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[29] <= 1'h0;
    else if (_002_) dst_addr[29] <= _000_[29];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[30] <= 1'h0;
    else if (_002_) dst_addr[30] <= _000_[30];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[31] <= 1'h0;
    else if (_002_) dst_addr[31] <= _000_[31];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[0] <= 1'h0;
    else if (_003_) src_addr[0] <= _001_[0];
  always @(posedge clk, posedge rst)
    if (rst) src_addr[1] <= 1'h0;
    else if (_003_) src_addr[1] <= _001_[1];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[0] <= 1'h0;
    else if (_003_) dst_addr[0] <= _000_[0];
  always @(posedge clk, posedge rst)
    if (rst) dst_addr[1] <= 1'h0;
    else if (_003_) dst_addr[1] <= _000_[1];
endmodule

module dma_control_register(clk, rst, start, dma_busy, dma_done, start_reg, busy_reg, done_reg);
  output busy_reg;
  reg busy_reg;
  input clk;
  wire clk;
  input dma_busy;
  wire dma_busy;
  input dma_done;
  wire dma_done;
  output done_reg;
  reg done_reg;
  input rst;
  wire rst;
  input start;
  wire start;
  output start_reg;
  reg start_reg;
  always @(posedge clk, posedge rst)
    if (rst) start_reg <= 1'h0;
    else start_reg <= start;
  always @(posedge clk, posedge rst)
    if (rst) busy_reg <= 1'h0;
    else busy_reg <= dma_busy;
  always @(posedge clk, posedge rst)
    if (rst) done_reg <= 1'h0;
    else done_reg <= dma_done;
endmodule

module dma_controller_fsm(clk, rst, start, transfer_done, load, increment, decrement, dma_busy, dma_done);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [14:0] _12_;
  wire [4:0] _13_;
  wire [2:0] _14_;
  wire _15_;
  input clk;
  wire clk;
  output decrement;
  reg decrement;
  output dma_busy;
  reg dma_busy;
  output dma_done;
  reg dma_done;
  output increment;
  wire increment;
  output load;
  reg load;
  input rst;
  wire rst;
  input start;
  wire start;
  reg [2:0] state;
  input transfer_done;
  wire transfer_done;
  INV_X1 _16_ (
    .A(state[2]),
    .ZN(_03_)
  );
  INV_X1 _17_ (
    .A(state[0]),
    .ZN(_04_)
  );
  INV_X1 _18_ (
    .A(start),
    .ZN(_05_)
  );
  NOR2_X1 _19_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_06_)
  );
  NAND3_X1 _20_ (
    .A1(_03_),
    .A2(_05_),
    .A3(_06_),
    .ZN(_02_)
  );
  NOR3_X1 _21_ (
    .A1(_03_),
    .A2(_04_),
    .A3(state[1]),
    .ZN(_00_)
  );
  OR3_X1 _22_ (
    .A1(state[2]),
    .A2(_04_),
    .A3(state[1]),
    .ZN(_07_)
  );
  INV_X1 _23_ (
    .A(_07_),
    .ZN(_12_[10])
  );
  AOI21_X1 _24_ (
    .A(state[1]),
    .B1(_04_),
    .B2(state[2]),
    .ZN(_01_)
  );
  NAND2_X1 _25_ (
    .A1(state[2]),
    .A2(_06_),
    .ZN(_08_)
  );
  INV_X1 _26_ (
    .A(_08_),
    .ZN(_13_[0])
  );
  NAND3_X1 _27_ (
    .A1(state[2]),
    .A2(transfer_done),
    .A3(_06_),
    .ZN(_09_)
  );
  NAND2_X1 _28_ (
    .A1(_03_),
    .A2(state[1]),
    .ZN(_10_)
  );
  OAI211_X1 _29_ (
    .A(_03_),
    .B(_04_),
    .C1(state[1]),
    .C2(start),
    .ZN(_11_)
  );
  NAND2_X1 _30_ (
    .A1(_09_),
    .A2(_11_),
    .ZN(_14_[0])
  );
  OAI221_X1 _31_ (
    .A(_07_),
    .B1(_08_),
    .B2(transfer_done),
    .C1(_10_),
    .C2(state[0]),
    .ZN(_14_[1])
  );
  OAI21_X1 _32_ (
    .A(_09_),
    .B1(_10_),
    .B2(_04_),
    .ZN(_14_[2])
  );
  INV_X1 _33_ (
    .A(_07_),
    .ZN(_15_)
  );
  always @(posedge clk, posedge rst)
    if (rst) dma_busy <= 1'h0;
    else if (_01_) dma_busy <= _15_;
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _12_[10];
  always @(posedge clk, posedge rst)
    if (rst) state[0] <= 1'h0;
    else if (_02_) state[0] <= _14_[0];
  always @(posedge clk, posedge rst)
    if (rst) state[1] <= 1'h0;
    else if (_02_) state[1] <= _14_[1];
  always @(posedge clk, posedge rst)
    if (rst) state[2] <= 1'h0;
    else if (_02_) state[2] <= _14_[2];
  always @(posedge clk, posedge rst)
    if (rst) dma_done <= 1'h0;
    else dma_done <= _00_;
  always @(posedge clk, posedge rst)
    if (rst) decrement <= 1'h0;
    else decrement <= _13_[0];
  assign { _12_[13], _12_[11], _12_[9:8], _12_[6], _12_[4:3], _12_[0] } = { _12_[14], 3'h0, _12_[7], 2'h0, _12_[2] };
  assign _13_[3:1] = { _12_[10], _12_[7], _12_[5] };
  assign increment = decrement;
endmodule

module dma_top(clk, rst, start, src_addr_in, dst_addr_in, transfer_length, src_addr, dst_addr, dma_busy, dma_done);
  wire busy_reg;
  input clk;
  wire clk;
  wire [15:0] count;
  wire decrement;
  output dma_busy;
  wire dma_busy;
  output dma_done;
  wire dma_done;
  wire done_reg;
  output [31:0] dst_addr;
  wire [31:0] dst_addr;
  input [31:0] dst_addr_in;
  wire [31:0] dst_addr_in;
  wire increment;
  wire load;
  input rst;
  wire rst;
  output [31:0] src_addr;
  wire [31:0] src_addr;
  input [31:0] src_addr_in;
  wire [31:0] src_addr_in;
  input start;
  wire start;
  wire start_reg;
  wire transfer_done;
  input [15:0] transfer_length;
  wire [15:0] transfer_length;
  dma_address_generator address_gen (
    .clk(clk),
    .dst_addr(dst_addr),
    .dst_addr_in(dst_addr_in),
    .increment(increment),
    .load(load),
    .rst(rst),
    .src_addr(src_addr),
    .src_addr_in(src_addr_in)
  );
  dma_control_register control_reg (
    .busy_reg(busy_reg),
    .clk(clk),
    .dma_busy(dma_busy),
    .dma_done(dma_done),
    .done_reg(done_reg),
    .rst(rst),
    .start(start),
    .start_reg(start_reg)
  );
  dma_controller_fsm controller (
    .clk(clk),
    .decrement(decrement),
    .dma_busy(dma_busy),
    .dma_done(dma_done),
    .increment(increment),
    .load(load),
    .rst(rst),
    .start(start_reg),
    .transfer_done(transfer_done)
  );
  dma_transfer_counter counter (
    .clk(clk),
    .count(count),
    .decrement(decrement),
    .load(load),
    .rst(rst),
    .transfer_done(transfer_done),
    .transfer_length(transfer_length)
  );
endmodule

module dma_transfer_counter(clk, rst, load, decrement, transfer_length, count, transfer_done);
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  input clk;
  wire clk;
  output [15:0] count;
  reg [15:0] count;
  input decrement;
  wire decrement;
  input load;
  wire load;
  input rst;
  wire rst;
  output transfer_done;
  wire transfer_done;
  input [15:0] transfer_length;
  wire [15:0] transfer_length;
  INV_X1 _055_ (
    .A(count[7]),
    .ZN(_018_)
  );
  INV_X1 _056_ (
    .A(count[8]),
    .ZN(_019_)
  );
  INV_X1 _057_ (
    .A(count[9]),
    .ZN(_020_)
  );
  INV_X1 _058_ (
    .A(count[13]),
    .ZN(_021_)
  );
  INV_X1 _059_ (
    .A(count[14]),
    .ZN(_022_)
  );
  INV_X1 _060_ (
    .A(load),
    .ZN(_023_)
  );
  INV_X1 _061_ (
    .A(decrement),
    .ZN(_024_)
  );
  NOR2_X1 _062_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_025_)
  );
  NOR3_X1 _063_ (
    .A1(count[0]),
    .A2(count[2]),
    .A3(count[1]),
    .ZN(_026_)
  );
  OR4_X1 _064_ (
    .A1(count[0]),
    .A2(count[2]),
    .A3(count[3]),
    .A4(count[1]),
    .ZN(_027_)
  );
  NOR2_X1 _065_ (
    .A1(count[4]),
    .A2(_027_),
    .ZN(_028_)
  );
  NOR3_X1 _066_ (
    .A1(count[4]),
    .A2(count[5]),
    .A3(_027_),
    .ZN(_029_)
  );
  NOR4_X1 _067_ (
    .A1(count[6]),
    .A2(count[4]),
    .A3(count[5]),
    .A4(_027_),
    .ZN(_030_)
  );
  NAND2_X1 _068_ (
    .A1(_018_),
    .A2(_030_),
    .ZN(_031_)
  );
  NAND4_X1 _069_ (
    .A1(_018_),
    .A2(_019_),
    .A3(_020_),
    .A4(_030_),
    .ZN(_032_)
  );
  OR3_X1 _070_ (
    .A1(count[10]),
    .A2(count[11]),
    .A3(_032_),
    .ZN(_033_)
  );
  NOR4_X1 _071_ (
    .A1(count[10]),
    .A2(count[11]),
    .A3(count[12]),
    .A4(_032_),
    .ZN(_034_)
  );
  NAND2_X1 _072_ (
    .A1(_021_),
    .A2(_034_),
    .ZN(_035_)
  );
  NAND3_X1 _073_ (
    .A1(_021_),
    .A2(_022_),
    .A3(_034_),
    .ZN(_036_)
  );
  NOR2_X1 _074_ (
    .A1(count[15]),
    .A2(_036_),
    .ZN(transfer_done)
  );
  OAI21_X1 _075_ (
    .A(_023_),
    .B1(_024_),
    .B2(transfer_done),
    .ZN(_001_)
  );
  OAI211_X1 _076_ (
    .A(_023_),
    .B(decrement),
    .C1(_036_),
    .C2(count[15]),
    .ZN(_037_)
  );
  NAND2_X1 _077_ (
    .A1(load),
    .A2(transfer_length[0]),
    .ZN(_038_)
  );
  OAI21_X1 _078_ (
    .A(_038_),
    .B1(_037_),
    .B2(count[0]),
    .ZN(_000_[0])
  );
  XOR2_X1 _079_ (
    .A(count[0]),
    .B(count[1]),
    .Z(_039_)
  );
  NAND2_X1 _080_ (
    .A1(load),
    .A2(transfer_length[1]),
    .ZN(_040_)
  );
  OAI21_X1 _081_ (
    .A(_040_),
    .B1(_039_),
    .B2(_037_),
    .ZN(_000_[1])
  );
  XNOR2_X1 _082_ (
    .A(count[2]),
    .B(_025_),
    .ZN(_041_)
  );
  NAND2_X1 _083_ (
    .A1(load),
    .A2(transfer_length[2]),
    .ZN(_042_)
  );
  OAI21_X1 _084_ (
    .A(_042_),
    .B1(_041_),
    .B2(_037_),
    .ZN(_000_[2])
  );
  XNOR2_X1 _085_ (
    .A(count[3]),
    .B(_026_),
    .ZN(_043_)
  );
  NAND2_X1 _086_ (
    .A1(load),
    .A2(transfer_length[3]),
    .ZN(_044_)
  );
  OAI21_X1 _087_ (
    .A(_044_),
    .B1(_043_),
    .B2(_037_),
    .ZN(_000_[3])
  );
  XOR2_X1 _088_ (
    .A(count[4]),
    .B(_027_),
    .Z(_045_)
  );
  NAND2_X1 _089_ (
    .A1(load),
    .A2(transfer_length[4]),
    .ZN(_046_)
  );
  OAI21_X1 _090_ (
    .A(_046_),
    .B1(_045_),
    .B2(_037_),
    .ZN(_000_[4])
  );
  XNOR2_X1 _091_ (
    .A(count[5]),
    .B(_028_),
    .ZN(_047_)
  );
  NAND2_X1 _092_ (
    .A1(load),
    .A2(transfer_length[5]),
    .ZN(_048_)
  );
  OAI21_X1 _093_ (
    .A(_048_),
    .B1(_047_),
    .B2(_037_),
    .ZN(_000_[5])
  );
  XNOR2_X1 _094_ (
    .A(count[6]),
    .B(_029_),
    .ZN(_049_)
  );
  NAND2_X1 _095_ (
    .A1(load),
    .A2(transfer_length[6]),
    .ZN(_050_)
  );
  OAI21_X1 _096_ (
    .A(_050_),
    .B1(_049_),
    .B2(_037_),
    .ZN(_000_[6])
  );
  XNOR2_X1 _097_ (
    .A(count[7]),
    .B(_030_),
    .ZN(_051_)
  );
  NAND2_X1 _098_ (
    .A1(load),
    .A2(transfer_length[7]),
    .ZN(_052_)
  );
  OAI21_X1 _099_ (
    .A(_052_),
    .B1(_051_),
    .B2(_037_),
    .ZN(_000_[7])
  );
  XNOR2_X1 _100_ (
    .A(_019_),
    .B(_031_),
    .ZN(_053_)
  );
  NAND2_X1 _101_ (
    .A1(load),
    .A2(transfer_length[8]),
    .ZN(_054_)
  );
  OAI21_X1 _102_ (
    .A(_054_),
    .B1(_053_),
    .B2(_037_),
    .ZN(_000_[8])
  );
  OAI21_X1 _103_ (
    .A(count[9]),
    .B1(_031_),
    .B2(count[8]),
    .ZN(_002_)
  );
  AND2_X1 _104_ (
    .A1(_032_),
    .A2(_002_),
    .ZN(_003_)
  );
  NAND2_X1 _105_ (
    .A1(load),
    .A2(transfer_length[9]),
    .ZN(_004_)
  );
  OAI21_X1 _106_ (
    .A(_004_),
    .B1(_003_),
    .B2(_037_),
    .ZN(_000_[9])
  );
  XOR2_X1 _107_ (
    .A(count[10]),
    .B(_032_),
    .Z(_005_)
  );
  NAND2_X1 _108_ (
    .A1(load),
    .A2(transfer_length[10]),
    .ZN(_006_)
  );
  OAI21_X1 _109_ (
    .A(_006_),
    .B1(_005_),
    .B2(_037_),
    .ZN(_000_[10])
  );
  OAI21_X1 _110_ (
    .A(count[11]),
    .B1(_032_),
    .B2(count[10]),
    .ZN(_007_)
  );
  AND2_X1 _111_ (
    .A1(_033_),
    .A2(_007_),
    .ZN(_008_)
  );
  NAND2_X1 _112_ (
    .A1(load),
    .A2(transfer_length[11]),
    .ZN(_009_)
  );
  OAI21_X1 _113_ (
    .A(_009_),
    .B1(_008_),
    .B2(_037_),
    .ZN(_000_[11])
  );
  XOR2_X1 _114_ (
    .A(count[12]),
    .B(_033_),
    .Z(_010_)
  );
  NAND2_X1 _115_ (
    .A1(load),
    .A2(transfer_length[12]),
    .ZN(_011_)
  );
  OAI21_X1 _116_ (
    .A(_011_),
    .B1(_010_),
    .B2(_037_),
    .ZN(_000_[12])
  );
  XNOR2_X1 _117_ (
    .A(count[13]),
    .B(_034_),
    .ZN(_012_)
  );
  NAND2_X1 _118_ (
    .A1(load),
    .A2(transfer_length[13]),
    .ZN(_013_)
  );
  OAI21_X1 _119_ (
    .A(_013_),
    .B1(_012_),
    .B2(_037_),
    .ZN(_000_[13])
  );
  XNOR2_X1 _120_ (
    .A(_022_),
    .B(_035_),
    .ZN(_014_)
  );
  NAND2_X1 _121_ (
    .A1(load),
    .A2(transfer_length[14]),
    .ZN(_015_)
  );
  OAI21_X1 _122_ (
    .A(_015_),
    .B1(_014_),
    .B2(_037_),
    .ZN(_000_[14])
  );
  NAND2_X1 _123_ (
    .A1(load),
    .A2(transfer_length[15]),
    .ZN(_016_)
  );
  NAND2_X1 _124_ (
    .A1(count[15]),
    .A2(_036_),
    .ZN(_017_)
  );
  OAI21_X1 _125_ (
    .A(_016_),
    .B1(_017_),
    .B2(_037_),
    .ZN(_000_[15])
  );
  always @(posedge clk, posedge rst)
    if (rst) count[0] <= 1'h0;
    else if (_001_) count[0] <= _000_[0];
  always @(posedge clk, posedge rst)
    if (rst) count[1] <= 1'h0;
    else if (_001_) count[1] <= _000_[1];
  always @(posedge clk, posedge rst)
    if (rst) count[2] <= 1'h0;
    else if (_001_) count[2] <= _000_[2];
  always @(posedge clk, posedge rst)
    if (rst) count[3] <= 1'h0;
    else if (_001_) count[3] <= _000_[3];
  always @(posedge clk, posedge rst)
    if (rst) count[4] <= 1'h0;
    else if (_001_) count[4] <= _000_[4];
  always @(posedge clk, posedge rst)
    if (rst) count[5] <= 1'h0;
    else if (_001_) count[5] <= _000_[5];
  always @(posedge clk, posedge rst)
    if (rst) count[6] <= 1'h0;
    else if (_001_) count[6] <= _000_[6];
  always @(posedge clk, posedge rst)
    if (rst) count[7] <= 1'h0;
    else if (_001_) count[7] <= _000_[7];
  always @(posedge clk, posedge rst)
    if (rst) count[8] <= 1'h0;
    else if (_001_) count[8] <= _000_[8];
  always @(posedge clk, posedge rst)
    if (rst) count[9] <= 1'h0;
    else if (_001_) count[9] <= _000_[9];
  always @(posedge clk, posedge rst)
    if (rst) count[10] <= 1'h0;
    else if (_001_) count[10] <= _000_[10];
  always @(posedge clk, posedge rst)
    if (rst) count[11] <= 1'h0;
    else if (_001_) count[11] <= _000_[11];
  always @(posedge clk, posedge rst)
    if (rst) count[12] <= 1'h0;
    else if (_001_) count[12] <= _000_[12];
  always @(posedge clk, posedge rst)
    if (rst) count[13] <= 1'h0;
    else if (_001_) count[13] <= _000_[13];
  always @(posedge clk, posedge rst)
    if (rst) count[14] <= 1'h0;
    else if (_001_) count[14] <= _000_[14];
  always @(posedge clk, posedge rst)
    if (rst) count[15] <= 1'h0;
    else if (_001_) count[15] <= _000_[15];
endmodule
