/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

module arbiter_fsm(clk, rst, request_pending, transfer_done, read_fifo, grant_enable, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input request_pending;
  wire request_pending;
  input transfer_done;
  wire transfer_done;
  output read_fifo;
  wire read_fifo;
  output grant_enable;
  wire grant_enable;
  output done;
  wire done;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire [1:0] state;
  INV_X1 _23_ (
    .A(state[0]),
    .ZN(_05_)
  );
  INV_X1 _24_ (
    .A(transfer_done),
    .ZN(_06_)
  );
  INV_X1 _25_ (
    .A(request_pending),
    .ZN(_07_)
  );
  NOR2_X1 _26_ (
    .A1(state[1]),
    .A2(_05_),
    .ZN(_02_)
  );
  AND2_X1 _27_ (
    .A1(state[1]),
    .A2(state[0]),
    .ZN(_00_)
  );
  AND2_X1 _28_ (
    .A1(state[1]),
    .A2(_05_),
    .ZN(_01_)
  );
  NAND3_X1 _29_ (
    .A1(state[1]),
    .A2(_05_),
    .A3(transfer_done),
    .ZN(_08_)
  );
  NOR2_X1 _30_ (
    .A1(state[1]),
    .A2(state[0]),
    .ZN(_09_)
  );
  NAND2_X1 _31_ (
    .A1(request_pending),
    .A2(_09_),
    .ZN(_10_)
  );
  NAND2_X1 _32_ (
    .A1(_08_),
    .A2(_10_),
    .ZN(_03_[0])
  );
  AOI22_X1 _33_ (
    .A1(_06_),
    .A2(_01_),
    .B1(_09_),
    .B2(_07_),
    .ZN(_04_)
  );
  OAI21_X1 _34_ (
    .A(_08_),
    .B1(_05_),
    .B2(state[1]),
    .ZN(_03_[1])
  );
  assign _16_ = ~rst;
  assign _17_ = ~rst;
  assign _18_ = ~rst;
  assign _19_ = ~rst;
  assign _20_ = ~rst;
  DFFR_X1 _40_ (
    .CK(clk),
    .D(_21_),
    .Q(state[0]),
    .QN(_14_),
    .RN(_17_)
  );
  DFFR_X1 _41_ (
    .CK(clk),
    .D(_22_),
    .Q(state[1]),
    .QN(_12_),
    .RN(_19_)
  );
  DFFR_X1 _42_ (
    .CK(clk),
    .D(_02_),
    .Q(read_fifo),
    .QN(_11_),
    .RN(_20_)
  );
  DFFR_X1 _43_ (
    .CK(clk),
    .D(_01_),
    .Q(grant_enable),
    .QN(_15_),
    .RN(_16_)
  );
  DFFR_X1 _44_ (
    .CK(clk),
    .D(_00_),
    .Q(done),
    .QN(_13_),
    .RN(_18_)
  );
  assign _21_ = _04_ ? _03_[0] : state[0];
  assign _22_ = _04_ ? _03_[1] : state[1];
endmodule

module multi_port_sdram_top(clk, rst, cpu_req, dma_req, eth_req, gpu_req, grant, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input cpu_req;
  wire cpu_req;
  input dma_req;
  wire dma_req;
  input eth_req;
  wire eth_req;
  input gpu_req;
  wire gpu_req;
  output [1:0] grant;
  wire [1:0] grant;
  output done;
  wire done;
  wire grant_enable;
  wire read_fifo;
  wire request_pending;
  OR4_X1 _0_ (
    .A1(gpu_req),
    .A2(eth_req),
    .A3(cpu_req),
    .A4(dma_req),
    .ZN(request_pending)
  );
  round_robin_arbiter arbiter (
    .clk(clk),
    .cpu_req(cpu_req),
    .dma_req(dma_req),
    .eth_req(eth_req),
    .gpu_req(gpu_req),
    .grant(grant),
    .rst(rst)
  );
  arbiter_fsm controller (
    .clk(clk),
    .done(done),
    .grant_enable(grant_enable),
    .read_fifo(read_fifo),
    .request_pending(request_pending),
    .rst(rst),
    .transfer_done(grant_enable)
  );
endmodule

module round_robin_arbiter(clk, rst, cpu_req, dma_req, eth_req, gpu_req, grant, valid);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input cpu_req;
  wire cpu_req;
  input dma_req;
  wire dma_req;
  input eth_req;
  wire eth_req;
  input gpu_req;
  wire gpu_req;
  output [1:0] grant;
  wire [1:0] grant;
  output valid;
  wire valid;
  wire [1:0] _00_;
  wire [1:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire [1:0] pointer;
  INV_X1 _41_ (
    .A(gpu_req),
    .ZN(_04_)
  );
  INV_X1 _42_ (
    .A(cpu_req),
    .ZN(_05_)
  );
  INV_X1 _43_ (
    .A(eth_req),
    .ZN(_06_)
  );
  INV_X1 _44_ (
    .A(pointer[0]),
    .ZN(_07_)
  );
  INV_X1 _45_ (
    .A(pointer[1]),
    .ZN(_08_)
  );
  AOI21_X1 _46_ (
    .A(gpu_req),
    .B1(_05_),
    .B2(dma_req),
    .ZN(_09_)
  );
  NOR3_X1 _47_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_09_),
    .ZN(_10_)
  );
  NOR2_X1 _48_ (
    .A1(_04_),
    .A2(eth_req),
    .ZN(_11_)
  );
  NAND2_X1 _49_ (
    .A1(gpu_req),
    .A2(_06_),
    .ZN(_12_)
  );
  AOI21_X1 _50_ (
    .A(_12_),
    .B1(pointer[1]),
    .B2(pointer[0]),
    .ZN(_13_)
  );
  NAND2_X1 _51_ (
    .A1(dma_req),
    .A2(_08_),
    .ZN(_14_)
  );
  OAI21_X1 _52_ (
    .A(_14_),
    .B1(eth_req),
    .B2(cpu_req),
    .ZN(_15_)
  );
  OAI33_X1 _53_ (
    .A1(_05_),
    .A2(pointer[0]),
    .A3(pointer[1]),
    .B1(_10_),
    .B2(_13_),
    .B3(_15_),
    .ZN(_01_[0])
  );
  AOI21_X1 _54_ (
    .A(pointer[1]),
    .B1(_07_),
    .B2(cpu_req),
    .ZN(_16_)
  );
  OAI21_X1 _55_ (
    .A(_16_),
    .B1(_11_),
    .B2(dma_req),
    .ZN(_17_)
  );
  OAI21_X1 _56_ (
    .A(pointer[1]),
    .B1(pointer[0]),
    .B2(_06_),
    .ZN(_18_)
  );
  OAI21_X1 _57_ (
    .A(_17_),
    .B1(_18_),
    .B2(_09_),
    .ZN(_00_[0])
  );
  NOR2_X1 _58_ (
    .A1(dma_req),
    .A2(eth_req),
    .ZN(_19_)
  );
  NAND3_X1 _59_ (
    .A1(_04_),
    .A2(_05_),
    .A3(_19_),
    .ZN(_03_)
  );
  OAI21_X1 _60_ (
    .A(_14_),
    .B1(eth_req),
    .B2(gpu_req),
    .ZN(_20_)
  );
  OAI211_X1 _61_ (
    .A(_04_),
    .B(pointer[0]),
    .C1(dma_req),
    .C2(cpu_req),
    .ZN(_21_)
  );
  AOI21_X1 _62_ (
    .A(_16_),
    .B1(_21_),
    .B2(pointer[1]),
    .ZN(_22_)
  );
  NOR2_X1 _63_ (
    .A1(_20_),
    .A2(_22_),
    .ZN(_00_[1])
  );
  NOR3_X1 _64_ (
    .A1(gpu_req),
    .A2(cpu_req),
    .A3(_07_),
    .ZN(_23_)
  );
  NOR2_X1 _65_ (
    .A1(_16_),
    .A2(_23_),
    .ZN(_24_)
  );
  AOI21_X1 _66_ (
    .A(eth_req),
    .B1(dma_req),
    .B2(_05_),
    .ZN(_25_)
  );
  NAND3_X1 _67_ (
    .A1(_07_),
    .A2(pointer[1]),
    .A3(_12_),
    .ZN(_26_)
  );
  OAI22_X1 _68_ (
    .A1(_19_),
    .A2(_24_),
    .B1(_25_),
    .B2(_26_),
    .ZN(_01_[1])
  );
  NAND3_X1 _69_ (
    .A1(_04_),
    .A2(_05_),
    .A3(_19_),
    .ZN(_02_)
  );
  assign _32_ = ~rst;
  assign _33_ = ~rst;
  assign _34_ = ~rst;
  assign _35_ = ~rst;
  assign _36_ = ~rst;
  DFFR_X1 _75_ (
    .CK(clk),
    .D(_40_),
    .Q(pointer[0]),
    .QN(_27_),
    .RN(_36_)
  );
  DFFR_X1 _76_ (
    .CK(clk),
    .D(_37_),
    .Q(pointer[1]),
    .QN(_31_),
    .RN(_32_)
  );
  DFFR_X1 _77_ (
    .CK(clk),
    .D(_38_),
    .Q(grant[0]),
    .QN(_30_),
    .RN(_33_)
  );
  DFFR_X1 _78_ (
    .CK(clk),
    .D(_39_),
    .Q(grant[1]),
    .QN(_29_),
    .RN(_34_)
  );
  DFFR_X1 _79_ (
    .CK(clk),
    .D(_02_),
    .Q(valid),
    .QN(_28_),
    .RN(_35_)
  );
  assign _37_ = _03_ ? _01_[1] : pointer[1];
  assign _38_ = _03_ ? _00_[0] : grant[0];
  assign _39_ = _03_ ? _00_[1] : grant[1];
  assign _40_ = _03_ ? _01_[0] : pointer[0];
endmodule
