/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module axi_slave_top(clk, rst, awvalid, wvalid, bready, arvalid, rready, address, write_data, read_data, awready, wready, bvalid, arready, rvalid);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  input [31:0] address;
  wire [31:0] address;
  wire address_valid;
  output arready;
  wire arready;
  input arvalid;
  wire arvalid;
  output awready;
  wire awready;
  input awvalid;
  wire awvalid;
  input bready;
  wire bready;
  output bvalid;
  wire bvalid;
  input clk;
  wire clk;
  wire [31:0] \decoder.address ;
  wire \decoder.valid ;
  wire \read_ctrl.address_valid ;
  wire \read_ctrl.arready ;
  wire \read_ctrl.arvalid ;
  wire \read_ctrl.clk ;
  wire \read_ctrl.rready ;
  wire \read_ctrl.rst ;
  wire \read_ctrl.rvalid ;
  output [31:0] read_data;
  wire [31:0] read_data;
  wire \regfile.clk ;
  wire [31:0] \regfile.i ;
  wire [31:0] \regfile.read_data ;
  wire [31:0] \regfile.reg_bank[0] ;
  wire [31:0] \regfile.reg_bank[1] ;
  wire [31:0] \regfile.reg_bank[2] ;
  wire [31:0] \regfile.reg_bank[3] ;
  wire \regfile.rst ;
  wire [31:0] \regfile.write_data ;
  wire \regfile.write_enable ;
  input rready;
  wire rready;
  input rst;
  wire rst;
  output rvalid;
  wire rvalid;
  output wready;
  wire wready;
  wire \write_ctrl.address_valid ;
  wire \write_ctrl.awready ;
  wire \write_ctrl.awvalid ;
  wire \write_ctrl.bready ;
  wire \write_ctrl.bvalid ;
  wire \write_ctrl.clk ;
  wire \write_ctrl.rst ;
  wire \write_ctrl.wready ;
  wire \write_ctrl.write_enable ;
  wire \write_ctrl.wvalid ;
  input [31:0] write_data;
  wire [31:0] write_data;
  wire write_enable;
  input wvalid;
  wire wvalid;
  INV_X1 _0495_ (
    .A(address[2]),
    .ZN(_0009_)
  );
  INV_X1 _0496_ (
    .A(bready),
    .ZN(_0010_)
  );
  INV_X1 _0497_ (
    .A(rready),
    .ZN(_0011_)
  );
  INV_X1 _0498_ (
    .A(arvalid),
    .ZN(_0012_)
  );
  NOR2_X1 _0499_ (
    .A1(address[28]),
    .A2(address[29]),
    .ZN(_0013_)
  );
  NOR4_X1 _0500_ (
    .A1(address[24]),
    .A2(address[25]),
    .A3(address[30]),
    .A4(address[31]),
    .ZN(_0014_)
  );
  NOR4_X1 _0501_ (
    .A1(address[20]),
    .A2(address[21]),
    .A3(address[26]),
    .A4(address[27]),
    .ZN(_0015_)
  );
  NAND3_X1 _0502_ (
    .A1(_0013_),
    .A2(_0014_),
    .A3(_0015_),
    .ZN(_0016_)
  );
  NOR3_X1 _0503_ (
    .A1(address[16]),
    .A2(address[22]),
    .A3(address[23]),
    .ZN(_0017_)
  );
  NOR3_X1 _0504_ (
    .A1(address[17]),
    .A2(address[18]),
    .A3(address[19]),
    .ZN(_0018_)
  );
  NAND2_X1 _0505_ (
    .A1(_0017_),
    .A2(_0018_),
    .ZN(_0019_)
  );
  NOR3_X1 _0506_ (
    .A1(_0009_),
    .A2(_0016_),
    .A3(_0019_),
    .ZN(_0020_)
  );
  NOR4_X1 _0507_ (
    .A1(address[12]),
    .A2(address[13]),
    .A3(address[14]),
    .A4(address[15]),
    .ZN(_0021_)
  );
  NOR4_X1 _0508_ (
    .A1(address[8]),
    .A2(address[9]),
    .A3(address[10]),
    .A4(address[11]),
    .ZN(_0022_)
  );
  NAND2_X1 _0509_ (
    .A1(_0021_),
    .A2(_0022_),
    .ZN(_0023_)
  );
  NOR4_X1 _0510_ (
    .A1(address[4]),
    .A2(address[5]),
    .A3(address[6]),
    .A4(address[7]),
    .ZN(_0024_)
  );
  NOR2_X1 _0511_ (
    .A1(address[0]),
    .A2(address[1]),
    .ZN(_0025_)
  );
  NAND3_X1 _0512_ (
    .A1(address[3]),
    .A2(_0024_),
    .A3(_0025_),
    .ZN(_0026_)
  );
  NOR2_X1 _0513_ (
    .A1(_0023_),
    .A2(_0026_),
    .ZN(_0027_)
  );
  AND2_X1 _0514_ (
    .A1(_0020_),
    .A2(_0027_),
    .ZN(_0028_)
  );
  NOR3_X1 _0515_ (
    .A1(address[3]),
    .A2(address[0]),
    .A3(address[1]),
    .ZN(_0029_)
  );
  NAND4_X1 _0516_ (
    .A1(_0021_),
    .A2(_0022_),
    .A3(_0024_),
    .A4(_0029_),
    .ZN(_0030_)
  );
  NOR4_X1 _0517_ (
    .A1(_0009_),
    .A2(_0016_),
    .A3(_0019_),
    .A4(_0030_),
    .ZN(_0031_)
  );
  NAND3_X1 _0518_ (
    .A1(_0009_),
    .A2(_0021_),
    .A3(_0022_),
    .ZN(_0032_)
  );
  NOR3_X1 _0519_ (
    .A1(_0016_),
    .A2(_0019_),
    .A3(_0032_),
    .ZN(_0033_)
  );
  NOR4_X1 _0520_ (
    .A1(_0016_),
    .A2(_0019_),
    .A3(_0026_),
    .A4(_0032_),
    .ZN(_0034_)
  );
  AOI211_X1 _0521_ (
    .A(_0031_),
    .B(_0034_),
    .C1(_0020_),
    .C2(_0027_),
    .ZN(_0035_)
  );
  NAND3_X1 _0522_ (
    .A1(_0024_),
    .A2(_0029_),
    .A3(_0033_),
    .ZN(_0036_)
  );
  AND2_X1 _0523_ (
    .A1(_0035_),
    .A2(_0036_),
    .ZN(_0037_)
  );
  NAND2_X1 _0524_ (
    .A1(awvalid),
    .A2(wvalid),
    .ZN(_0038_)
  );
  NOR2_X1 _0525_ (
    .A1(_0037_),
    .A2(_0038_),
    .ZN(_0008_)
  );
  OAI21_X1 _0526_ (
    .A(_0010_),
    .B1(_0037_),
    .B2(_0038_),
    .ZN(_0001_)
  );
  AND2_X1 _0527_ (
    .A1(\write_ctrl.write_enable ),
    .A2(_0035_),
    .ZN(_0005_)
  );
  AND2_X1 _0528_ (
    .A1(\write_ctrl.write_enable ),
    .A2(_0031_),
    .ZN(_0004_)
  );
  AND2_X1 _0529_ (
    .A1(\write_ctrl.write_enable ),
    .A2(_0034_),
    .ZN(_0003_)
  );
  NOR2_X1 _0530_ (
    .A1(_0012_),
    .A2(_0037_),
    .ZN(_0006_)
  );
  OAI21_X1 _0531_ (
    .A(_0011_),
    .B1(_0012_),
    .B2(_0037_),
    .ZN(_0000_)
  );
  AND2_X1 _0532_ (
    .A1(\write_ctrl.write_enable ),
    .A2(_0028_),
    .ZN(_0002_)
  );
  AOI22_X1 _0533_ (
    .A1(\regfile.reg_bank[3] [0]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [0]),
    .ZN(_0039_)
  );
  AOI22_X1 _0534_ (
    .A1(\regfile.reg_bank[2] [0]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [0]),
    .ZN(_0040_)
  );
  NAND2_X1 _0535_ (
    .A1(_0039_),
    .A2(_0040_),
    .ZN(read_data[0])
  );
  AOI22_X1 _0536_ (
    .A1(\regfile.reg_bank[3] [1]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [1]),
    .ZN(_0041_)
  );
  AOI22_X1 _0537_ (
    .A1(\regfile.reg_bank[2] [1]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [1]),
    .ZN(_0042_)
  );
  NAND2_X1 _0538_ (
    .A1(_0041_),
    .A2(_0042_),
    .ZN(read_data[1])
  );
  AOI22_X1 _0539_ (
    .A1(\regfile.reg_bank[3] [2]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [2]),
    .ZN(_0043_)
  );
  AOI22_X1 _0540_ (
    .A1(\regfile.reg_bank[2] [2]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [2]),
    .ZN(_0044_)
  );
  NAND2_X1 _0541_ (
    .A1(_0043_),
    .A2(_0044_),
    .ZN(read_data[2])
  );
  AOI22_X1 _0542_ (
    .A1(\regfile.reg_bank[3] [3]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [3]),
    .ZN(_0045_)
  );
  AOI22_X1 _0543_ (
    .A1(\regfile.reg_bank[2] [3]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [3]),
    .ZN(_0046_)
  );
  NAND2_X1 _0544_ (
    .A1(_0045_),
    .A2(_0046_),
    .ZN(read_data[3])
  );
  AOI22_X1 _0545_ (
    .A1(\regfile.reg_bank[3] [4]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [4]),
    .ZN(_0047_)
  );
  AOI22_X1 _0546_ (
    .A1(\regfile.reg_bank[2] [4]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [4]),
    .ZN(_0048_)
  );
  NAND2_X1 _0547_ (
    .A1(_0047_),
    .A2(_0048_),
    .ZN(read_data[4])
  );
  AOI22_X1 _0548_ (
    .A1(\regfile.reg_bank[3] [5]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [5]),
    .ZN(_0049_)
  );
  AOI22_X1 _0549_ (
    .A1(\regfile.reg_bank[2] [5]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [5]),
    .ZN(_0050_)
  );
  NAND2_X1 _0550_ (
    .A1(_0049_),
    .A2(_0050_),
    .ZN(read_data[5])
  );
  AOI22_X1 _0551_ (
    .A1(\regfile.reg_bank[3] [6]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [6]),
    .ZN(_0051_)
  );
  AOI22_X1 _0552_ (
    .A1(\regfile.reg_bank[2] [6]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [6]),
    .ZN(_0052_)
  );
  NAND2_X1 _0553_ (
    .A1(_0051_),
    .A2(_0052_),
    .ZN(read_data[6])
  );
  AOI22_X1 _0554_ (
    .A1(\regfile.reg_bank[3] [7]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [7]),
    .ZN(_0053_)
  );
  AOI22_X1 _0555_ (
    .A1(\regfile.reg_bank[2] [7]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [7]),
    .ZN(_0054_)
  );
  NAND2_X1 _0556_ (
    .A1(_0053_),
    .A2(_0054_),
    .ZN(read_data[7])
  );
  AOI22_X1 _0557_ (
    .A1(\regfile.reg_bank[3] [8]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [8]),
    .ZN(_0055_)
  );
  AOI22_X1 _0558_ (
    .A1(\regfile.reg_bank[2] [8]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [8]),
    .ZN(_0056_)
  );
  NAND2_X1 _0559_ (
    .A1(_0055_),
    .A2(_0056_),
    .ZN(read_data[8])
  );
  AOI22_X1 _0560_ (
    .A1(\regfile.reg_bank[3] [9]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [9]),
    .ZN(_0057_)
  );
  AOI22_X1 _0561_ (
    .A1(\regfile.reg_bank[2] [9]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [9]),
    .ZN(_0058_)
  );
  NAND2_X1 _0562_ (
    .A1(_0057_),
    .A2(_0058_),
    .ZN(read_data[9])
  );
  AOI22_X1 _0563_ (
    .A1(\regfile.reg_bank[3] [10]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [10]),
    .ZN(_0059_)
  );
  AOI22_X1 _0564_ (
    .A1(\regfile.reg_bank[2] [10]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [10]),
    .ZN(_0060_)
  );
  NAND2_X1 _0565_ (
    .A1(_0059_),
    .A2(_0060_),
    .ZN(read_data[10])
  );
  AOI22_X1 _0566_ (
    .A1(\regfile.reg_bank[3] [11]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [11]),
    .ZN(_0061_)
  );
  AOI22_X1 _0567_ (
    .A1(\regfile.reg_bank[2] [11]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [11]),
    .ZN(_0062_)
  );
  NAND2_X1 _0568_ (
    .A1(_0061_),
    .A2(_0062_),
    .ZN(read_data[11])
  );
  AOI22_X1 _0569_ (
    .A1(\regfile.reg_bank[3] [12]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [12]),
    .ZN(_0063_)
  );
  AOI22_X1 _0570_ (
    .A1(\regfile.reg_bank[2] [12]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [12]),
    .ZN(_0064_)
  );
  NAND2_X1 _0571_ (
    .A1(_0063_),
    .A2(_0064_),
    .ZN(read_data[12])
  );
  AOI22_X1 _0572_ (
    .A1(\regfile.reg_bank[3] [13]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [13]),
    .ZN(_0065_)
  );
  AOI22_X1 _0573_ (
    .A1(\regfile.reg_bank[2] [13]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [13]),
    .ZN(_0066_)
  );
  NAND2_X1 _0574_ (
    .A1(_0065_),
    .A2(_0066_),
    .ZN(read_data[13])
  );
  AOI22_X1 _0575_ (
    .A1(\regfile.reg_bank[3] [14]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [14]),
    .ZN(_0067_)
  );
  AOI22_X1 _0576_ (
    .A1(\regfile.reg_bank[2] [14]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [14]),
    .ZN(_0068_)
  );
  NAND2_X1 _0577_ (
    .A1(_0067_),
    .A2(_0068_),
    .ZN(read_data[14])
  );
  AOI22_X1 _0578_ (
    .A1(\regfile.reg_bank[3] [15]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [15]),
    .ZN(_0069_)
  );
  AOI22_X1 _0579_ (
    .A1(\regfile.reg_bank[2] [15]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [15]),
    .ZN(_0070_)
  );
  NAND2_X1 _0580_ (
    .A1(_0069_),
    .A2(_0070_),
    .ZN(read_data[15])
  );
  AOI22_X1 _0581_ (
    .A1(\regfile.reg_bank[3] [16]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [16]),
    .ZN(_0071_)
  );
  AOI22_X1 _0582_ (
    .A1(\regfile.reg_bank[2] [16]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [16]),
    .ZN(_0072_)
  );
  NAND2_X1 _0583_ (
    .A1(_0071_),
    .A2(_0072_),
    .ZN(read_data[16])
  );
  AOI22_X1 _0584_ (
    .A1(\regfile.reg_bank[3] [17]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [17]),
    .ZN(_0073_)
  );
  AOI22_X1 _0585_ (
    .A1(\regfile.reg_bank[2] [17]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [17]),
    .ZN(_0074_)
  );
  NAND2_X1 _0586_ (
    .A1(_0073_),
    .A2(_0074_),
    .ZN(read_data[17])
  );
  AOI22_X1 _0587_ (
    .A1(\regfile.reg_bank[3] [18]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [18]),
    .ZN(_0075_)
  );
  AOI22_X1 _0588_ (
    .A1(\regfile.reg_bank[2] [18]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [18]),
    .ZN(_0076_)
  );
  NAND2_X1 _0589_ (
    .A1(_0075_),
    .A2(_0076_),
    .ZN(read_data[18])
  );
  AOI22_X1 _0590_ (
    .A1(\regfile.reg_bank[3] [19]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [19]),
    .ZN(_0077_)
  );
  AOI22_X1 _0591_ (
    .A1(\regfile.reg_bank[2] [19]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [19]),
    .ZN(_0078_)
  );
  NAND2_X1 _0592_ (
    .A1(_0077_),
    .A2(_0078_),
    .ZN(read_data[19])
  );
  AOI22_X1 _0593_ (
    .A1(\regfile.reg_bank[3] [20]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [20]),
    .ZN(_0079_)
  );
  AOI22_X1 _0594_ (
    .A1(\regfile.reg_bank[2] [20]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [20]),
    .ZN(_0080_)
  );
  NAND2_X1 _0595_ (
    .A1(_0079_),
    .A2(_0080_),
    .ZN(read_data[20])
  );
  AOI22_X1 _0596_ (
    .A1(\regfile.reg_bank[3] [21]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [21]),
    .ZN(_0081_)
  );
  AOI22_X1 _0597_ (
    .A1(\regfile.reg_bank[2] [21]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [21]),
    .ZN(_0082_)
  );
  NAND2_X1 _0598_ (
    .A1(_0081_),
    .A2(_0082_),
    .ZN(read_data[21])
  );
  AOI22_X1 _0599_ (
    .A1(\regfile.reg_bank[3] [22]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [22]),
    .ZN(_0083_)
  );
  AOI22_X1 _0600_ (
    .A1(\regfile.reg_bank[2] [22]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [22]),
    .ZN(_0084_)
  );
  NAND2_X1 _0601_ (
    .A1(_0083_),
    .A2(_0084_),
    .ZN(read_data[22])
  );
  AOI22_X1 _0602_ (
    .A1(\regfile.reg_bank[3] [23]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [23]),
    .ZN(_0085_)
  );
  AOI22_X1 _0603_ (
    .A1(\regfile.reg_bank[2] [23]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [23]),
    .ZN(_0086_)
  );
  NAND2_X1 _0604_ (
    .A1(_0085_),
    .A2(_0086_),
    .ZN(read_data[23])
  );
  AOI22_X1 _0605_ (
    .A1(\regfile.reg_bank[3] [24]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [24]),
    .ZN(_0087_)
  );
  AOI22_X1 _0606_ (
    .A1(\regfile.reg_bank[2] [24]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [24]),
    .ZN(_0088_)
  );
  NAND2_X1 _0607_ (
    .A1(_0087_),
    .A2(_0088_),
    .ZN(read_data[24])
  );
  AOI22_X1 _0608_ (
    .A1(\regfile.reg_bank[3] [25]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [25]),
    .ZN(_0089_)
  );
  AOI22_X1 _0609_ (
    .A1(\regfile.reg_bank[2] [25]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [25]),
    .ZN(_0090_)
  );
  NAND2_X1 _0610_ (
    .A1(_0089_),
    .A2(_0090_),
    .ZN(read_data[25])
  );
  AOI22_X1 _0611_ (
    .A1(\regfile.reg_bank[3] [26]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [26]),
    .ZN(_0091_)
  );
  AOI22_X1 _0612_ (
    .A1(\regfile.reg_bank[2] [26]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [26]),
    .ZN(_0092_)
  );
  NAND2_X1 _0613_ (
    .A1(_0091_),
    .A2(_0092_),
    .ZN(read_data[26])
  );
  AOI22_X1 _0614_ (
    .A1(\regfile.reg_bank[3] [27]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [27]),
    .ZN(_0093_)
  );
  AOI22_X1 _0615_ (
    .A1(\regfile.reg_bank[2] [27]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [27]),
    .ZN(_0094_)
  );
  NAND2_X1 _0616_ (
    .A1(_0093_),
    .A2(_0094_),
    .ZN(read_data[27])
  );
  AOI22_X1 _0617_ (
    .A1(\regfile.reg_bank[3] [28]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [28]),
    .ZN(_0095_)
  );
  AOI22_X1 _0618_ (
    .A1(\regfile.reg_bank[2] [28]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [28]),
    .ZN(_0096_)
  );
  NAND2_X1 _0619_ (
    .A1(_0095_),
    .A2(_0096_),
    .ZN(read_data[28])
  );
  AOI22_X1 _0620_ (
    .A1(\regfile.reg_bank[3] [29]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [29]),
    .ZN(_0097_)
  );
  AOI22_X1 _0621_ (
    .A1(\regfile.reg_bank[2] [29]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [29]),
    .ZN(_0098_)
  );
  NAND2_X1 _0622_ (
    .A1(_0097_),
    .A2(_0098_),
    .ZN(read_data[29])
  );
  AOI22_X1 _0623_ (
    .A1(\regfile.reg_bank[3] [30]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [30]),
    .ZN(_0099_)
  );
  AOI22_X1 _0624_ (
    .A1(\regfile.reg_bank[2] [30]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [30]),
    .ZN(_0100_)
  );
  NAND2_X1 _0625_ (
    .A1(_0099_),
    .A2(_0100_),
    .ZN(read_data[30])
  );
  AOI22_X1 _0626_ (
    .A1(\regfile.reg_bank[3] [31]),
    .A2(_0028_),
    .B1(_0031_),
    .B2(\regfile.reg_bank[1] [31]),
    .ZN(_0101_)
  );
  AOI22_X1 _0627_ (
    .A1(\regfile.reg_bank[2] [31]),
    .A2(_0034_),
    .B1(_0035_),
    .B2(\regfile.reg_bank[0] [31]),
    .ZN(_0102_)
  );
  NAND2_X1 _0628_ (
    .A1(_0101_),
    .A2(_0102_),
    .ZN(read_data[31])
  );
  NOR2_X1 _0629_ (
    .A1(_0037_),
    .A2(_0038_),
    .ZN(_0007_)
  );
  assign _0234_ = ~rst;
  assign _0235_ = ~rst;
  assign _0236_ = ~rst;
  assign _0237_ = ~rst;
  assign _0238_ = ~rst;
  assign _0239_ = ~rst;
  assign _0240_ = ~rst;
  assign _0241_ = ~rst;
  assign _0242_ = ~rst;
  assign _0243_ = ~rst;
  assign _0244_ = ~rst;
  assign _0245_ = ~rst;
  assign _0246_ = ~rst;
  assign _0247_ = ~rst;
  assign _0248_ = ~rst;
  assign _0249_ = ~rst;
  assign _0250_ = ~rst;
  assign _0251_ = ~rst;
  assign _0252_ = ~rst;
  assign _0253_ = ~rst;
  assign _0254_ = ~rst;
  assign _0255_ = ~rst;
  assign _0256_ = ~rst;
  assign _0257_ = ~rst;
  assign _0258_ = ~rst;
  assign _0259_ = ~rst;
  assign _0260_ = ~rst;
  assign _0261_ = ~rst;
  assign _0262_ = ~rst;
  assign _0263_ = ~rst;
  assign _0264_ = ~rst;
  assign _0265_ = ~rst;
  assign _0266_ = ~rst;
  assign _0267_ = ~rst;
  assign _0268_ = ~rst;
  assign _0269_ = ~rst;
  assign _0270_ = ~rst;
  assign _0271_ = ~rst;
  assign _0272_ = ~rst;
  assign _0273_ = ~rst;
  assign _0274_ = ~rst;
  assign _0275_ = ~rst;
  assign _0276_ = ~rst;
  assign _0277_ = ~rst;
  assign _0278_ = ~rst;
  assign _0279_ = ~rst;
  assign _0280_ = ~rst;
  assign _0281_ = ~rst;
  assign _0282_ = ~rst;
  assign _0283_ = ~rst;
  assign _0284_ = ~rst;
  assign _0285_ = ~rst;
  assign _0286_ = ~rst;
  assign _0287_ = ~rst;
  assign _0288_ = ~rst;
  assign _0289_ = ~rst;
  assign _0290_ = ~rst;
  assign _0291_ = ~rst;
  assign _0292_ = ~rst;
  assign _0293_ = ~rst;
  assign _0294_ = ~rst;
  assign _0295_ = ~rst;
  assign _0296_ = ~rst;
  assign _0297_ = ~rst;
  assign _0298_ = ~rst;
  assign _0299_ = ~rst;
  assign _0300_ = ~rst;
  assign _0301_ = ~rst;
  assign _0302_ = ~rst;
  assign _0303_ = ~rst;
  assign _0304_ = ~rst;
  assign _0305_ = ~rst;
  assign _0306_ = ~rst;
  assign _0307_ = ~rst;
  assign _0308_ = ~rst;
  assign _0309_ = ~rst;
  assign _0310_ = ~rst;
  assign _0311_ = ~rst;
  assign _0312_ = ~rst;
  assign _0313_ = ~rst;
  assign _0314_ = ~rst;
  assign _0315_ = ~rst;
  assign _0316_ = ~rst;
  assign _0317_ = ~rst;
  assign _0318_ = ~rst;
  assign _0319_ = ~rst;
  assign _0320_ = ~rst;
  assign _0321_ = ~rst;
  assign _0322_ = ~rst;
  assign _0323_ = ~rst;
  assign _0324_ = ~rst;
  assign _0325_ = ~rst;
  assign _0326_ = ~rst;
  assign _0327_ = ~rst;
  assign _0328_ = ~rst;
  assign _0329_ = ~rst;
  assign _0330_ = ~rst;
  assign _0331_ = ~rst;
  assign _0332_ = ~rst;
  assign _0333_ = ~rst;
  assign _0334_ = ~rst;
  assign _0335_ = ~rst;
  assign _0336_ = ~rst;
  assign _0337_ = ~rst;
  assign _0338_ = ~rst;
  assign _0339_ = ~rst;
  assign _0340_ = ~rst;
  assign _0341_ = ~rst;
  assign _0342_ = ~rst;
  assign _0343_ = ~rst;
  assign _0344_ = ~rst;
  assign _0345_ = ~rst;
  assign _0346_ = ~rst;
  assign _0347_ = ~rst;
  assign _0348_ = ~rst;
  assign _0349_ = ~rst;
  assign _0350_ = ~rst;
  assign _0351_ = ~rst;
  assign _0352_ = ~rst;
  assign _0353_ = ~rst;
  assign _0354_ = ~rst;
  assign _0355_ = ~rst;
  assign _0356_ = ~rst;
  assign _0357_ = ~rst;
  assign _0358_ = ~rst;
  assign _0359_ = ~rst;
  assign _0360_ = ~rst;
  assign _0361_ = ~rst;
  assign _0362_ = ~rst;
  assign _0363_ = ~rst;
  assign _0364_ = ~rst;
  DFFR_X1 _0761_ (
    .CK(clk),
    .D(_0416_),
    .Q(\read_ctrl.rvalid ),
    .QN(_0181_),
    .RN(_0286_)
  );
  DFFR_X1 _0762_ (
    .CK(clk),
    .D(_0417_),
    .Q(\regfile.reg_bank[2] [0]),
    .QN(_0180_),
    .RN(_0287_)
  );
  DFFR_X1 _0763_ (
    .CK(clk),
    .D(_0418_),
    .Q(\regfile.reg_bank[2] [1]),
    .QN(_0179_),
    .RN(_0288_)
  );
  DFFR_X1 _0764_ (
    .CK(clk),
    .D(_0419_),
    .Q(\regfile.reg_bank[2] [2]),
    .QN(_0178_),
    .RN(_0289_)
  );
  DFFR_X1 _0765_ (
    .CK(clk),
    .D(_0420_),
    .Q(\regfile.reg_bank[2] [3]),
    .QN(_0177_),
    .RN(_0290_)
  );
  DFFR_X1 _0766_ (
    .CK(clk),
    .D(_0421_),
    .Q(\regfile.reg_bank[2] [4]),
    .QN(_0176_),
    .RN(_0291_)
  );
  DFFR_X1 _0767_ (
    .CK(clk),
    .D(_0422_),
    .Q(\regfile.reg_bank[2] [5]),
    .QN(_0175_),
    .RN(_0292_)
  );
  DFFR_X1 _0768_ (
    .CK(clk),
    .D(_0423_),
    .Q(\regfile.reg_bank[2] [6]),
    .QN(_0174_),
    .RN(_0293_)
  );
  DFFR_X1 _0769_ (
    .CK(clk),
    .D(_0424_),
    .Q(\regfile.reg_bank[2] [7]),
    .QN(_0173_),
    .RN(_0294_)
  );
  DFFR_X1 _0770_ (
    .CK(clk),
    .D(_0425_),
    .Q(\regfile.reg_bank[2] [8]),
    .QN(_0172_),
    .RN(_0295_)
  );
  DFFR_X1 _0771_ (
    .CK(clk),
    .D(_0426_),
    .Q(\regfile.reg_bank[2] [9]),
    .QN(_0171_),
    .RN(_0296_)
  );
  DFFR_X1 _0772_ (
    .CK(clk),
    .D(_0427_),
    .Q(\regfile.reg_bank[2] [10]),
    .QN(_0170_),
    .RN(_0297_)
  );
  DFFR_X1 _0773_ (
    .CK(clk),
    .D(_0428_),
    .Q(\regfile.reg_bank[2] [11]),
    .QN(_0169_),
    .RN(_0298_)
  );
  DFFR_X1 _0774_ (
    .CK(clk),
    .D(_0429_),
    .Q(\regfile.reg_bank[2] [12]),
    .QN(_0168_),
    .RN(_0299_)
  );
  DFFR_X1 _0775_ (
    .CK(clk),
    .D(_0430_),
    .Q(\regfile.reg_bank[2] [13]),
    .QN(_0167_),
    .RN(_0300_)
  );
  DFFR_X1 _0776_ (
    .CK(clk),
    .D(_0431_),
    .Q(\regfile.reg_bank[2] [14]),
    .QN(_0166_),
    .RN(_0301_)
  );
  DFFR_X1 _0777_ (
    .CK(clk),
    .D(_0432_),
    .Q(\regfile.reg_bank[2] [15]),
    .QN(_0165_),
    .RN(_0302_)
  );
  DFFR_X1 _0778_ (
    .CK(clk),
    .D(_0433_),
    .Q(\regfile.reg_bank[2] [16]),
    .QN(_0164_),
    .RN(_0303_)
  );
  DFFR_X1 _0779_ (
    .CK(clk),
    .D(_0434_),
    .Q(\regfile.reg_bank[2] [17]),
    .QN(_0163_),
    .RN(_0304_)
  );
  DFFR_X1 _0780_ (
    .CK(clk),
    .D(_0435_),
    .Q(\regfile.reg_bank[2] [18]),
    .QN(_0162_),
    .RN(_0305_)
  );
  DFFR_X1 _0781_ (
    .CK(clk),
    .D(_0436_),
    .Q(\regfile.reg_bank[2] [19]),
    .QN(_0161_),
    .RN(_0306_)
  );
  DFFR_X1 _0782_ (
    .CK(clk),
    .D(_0437_),
    .Q(\regfile.reg_bank[2] [20]),
    .QN(_0160_),
    .RN(_0307_)
  );
  DFFR_X1 _0783_ (
    .CK(clk),
    .D(_0438_),
    .Q(\regfile.reg_bank[2] [21]),
    .QN(_0159_),
    .RN(_0308_)
  );
  DFFR_X1 _0784_ (
    .CK(clk),
    .D(_0439_),
    .Q(\regfile.reg_bank[2] [22]),
    .QN(_0158_),
    .RN(_0309_)
  );
  DFFR_X1 _0785_ (
    .CK(clk),
    .D(_0440_),
    .Q(\regfile.reg_bank[2] [23]),
    .QN(_0157_),
    .RN(_0310_)
  );
  DFFR_X1 _0786_ (
    .CK(clk),
    .D(_0441_),
    .Q(\regfile.reg_bank[2] [24]),
    .QN(_0156_),
    .RN(_0311_)
  );
  DFFR_X1 _0787_ (
    .CK(clk),
    .D(_0442_),
    .Q(\regfile.reg_bank[2] [25]),
    .QN(_0155_),
    .RN(_0312_)
  );
  DFFR_X1 _0788_ (
    .CK(clk),
    .D(_0443_),
    .Q(\regfile.reg_bank[2] [26]),
    .QN(_0154_),
    .RN(_0313_)
  );
  DFFR_X1 _0789_ (
    .CK(clk),
    .D(_0444_),
    .Q(\regfile.reg_bank[2] [27]),
    .QN(_0153_),
    .RN(_0314_)
  );
  DFFR_X1 _0790_ (
    .CK(clk),
    .D(_0445_),
    .Q(\regfile.reg_bank[2] [28]),
    .QN(_0152_),
    .RN(_0315_)
  );
  DFFR_X1 _0791_ (
    .CK(clk),
    .D(_0446_),
    .Q(\regfile.reg_bank[2] [29]),
    .QN(_0151_),
    .RN(_0316_)
  );
  DFFR_X1 _0792_ (
    .CK(clk),
    .D(_0447_),
    .Q(\regfile.reg_bank[2] [30]),
    .QN(_0150_),
    .RN(_0317_)
  );
  DFFR_X1 _0793_ (
    .CK(clk),
    .D(_0448_),
    .Q(\regfile.reg_bank[2] [31]),
    .QN(_0149_),
    .RN(_0318_)
  );
  DFFR_X1 _0794_ (
    .CK(clk),
    .D(_0449_),
    .Q(\regfile.reg_bank[1] [0]),
    .QN(_0148_),
    .RN(_0319_)
  );
  DFFR_X1 _0795_ (
    .CK(clk),
    .D(_0450_),
    .Q(\regfile.reg_bank[1] [1]),
    .QN(_0147_),
    .RN(_0320_)
  );
  DFFR_X1 _0796_ (
    .CK(clk),
    .D(_0451_),
    .Q(\regfile.reg_bank[1] [2]),
    .QN(_0146_),
    .RN(_0321_)
  );
  DFFR_X1 _0797_ (
    .CK(clk),
    .D(_0452_),
    .Q(\regfile.reg_bank[1] [3]),
    .QN(_0145_),
    .RN(_0322_)
  );
  DFFR_X1 _0798_ (
    .CK(clk),
    .D(_0453_),
    .Q(\regfile.reg_bank[1] [4]),
    .QN(_0144_),
    .RN(_0323_)
  );
  DFFR_X1 _0799_ (
    .CK(clk),
    .D(_0454_),
    .Q(\regfile.reg_bank[1] [5]),
    .QN(_0143_),
    .RN(_0324_)
  );
  DFFR_X1 _0800_ (
    .CK(clk),
    .D(_0455_),
    .Q(\regfile.reg_bank[1] [6]),
    .QN(_0142_),
    .RN(_0325_)
  );
  DFFR_X1 _0801_ (
    .CK(clk),
    .D(_0456_),
    .Q(\regfile.reg_bank[1] [7]),
    .QN(_0141_),
    .RN(_0326_)
  );
  DFFR_X1 _0802_ (
    .CK(clk),
    .D(_0457_),
    .Q(\regfile.reg_bank[1] [8]),
    .QN(_0140_),
    .RN(_0327_)
  );
  DFFR_X1 _0803_ (
    .CK(clk),
    .D(_0458_),
    .Q(\regfile.reg_bank[1] [9]),
    .QN(_0139_),
    .RN(_0328_)
  );
  DFFR_X1 _0804_ (
    .CK(clk),
    .D(_0459_),
    .Q(\regfile.reg_bank[1] [10]),
    .QN(_0138_),
    .RN(_0329_)
  );
  DFFR_X1 _0805_ (
    .CK(clk),
    .D(_0460_),
    .Q(\regfile.reg_bank[1] [11]),
    .QN(_0137_),
    .RN(_0330_)
  );
  DFFR_X1 _0806_ (
    .CK(clk),
    .D(_0461_),
    .Q(\regfile.reg_bank[1] [12]),
    .QN(_0136_),
    .RN(_0331_)
  );
  DFFR_X1 _0807_ (
    .CK(clk),
    .D(_0462_),
    .Q(\regfile.reg_bank[1] [13]),
    .QN(_0135_),
    .RN(_0332_)
  );
  DFFR_X1 _0808_ (
    .CK(clk),
    .D(_0463_),
    .Q(\regfile.reg_bank[1] [14]),
    .QN(_0134_),
    .RN(_0333_)
  );
  DFFR_X1 _0809_ (
    .CK(clk),
    .D(_0464_),
    .Q(\regfile.reg_bank[1] [15]),
    .QN(_0133_),
    .RN(_0334_)
  );
  DFFR_X1 _0810_ (
    .CK(clk),
    .D(_0465_),
    .Q(\regfile.reg_bank[1] [16]),
    .QN(_0132_),
    .RN(_0335_)
  );
  DFFR_X1 _0811_ (
    .CK(clk),
    .D(_0466_),
    .Q(\regfile.reg_bank[1] [17]),
    .QN(_0131_),
    .RN(_0336_)
  );
  DFFR_X1 _0812_ (
    .CK(clk),
    .D(_0467_),
    .Q(\regfile.reg_bank[1] [18]),
    .QN(_0130_),
    .RN(_0337_)
  );
  DFFR_X1 _0813_ (
    .CK(clk),
    .D(_0468_),
    .Q(\regfile.reg_bank[1] [19]),
    .QN(_0129_),
    .RN(_0338_)
  );
  DFFR_X1 _0814_ (
    .CK(clk),
    .D(_0469_),
    .Q(\regfile.reg_bank[1] [20]),
    .QN(_0128_),
    .RN(_0339_)
  );
  DFFR_X1 _0815_ (
    .CK(clk),
    .D(_0470_),
    .Q(\regfile.reg_bank[1] [21]),
    .QN(_0127_),
    .RN(_0340_)
  );
  DFFR_X1 _0816_ (
    .CK(clk),
    .D(_0471_),
    .Q(\regfile.reg_bank[1] [22]),
    .QN(_0126_),
    .RN(_0341_)
  );
  DFFR_X1 _0817_ (
    .CK(clk),
    .D(_0472_),
    .Q(\regfile.reg_bank[1] [23]),
    .QN(_0125_),
    .RN(_0342_)
  );
  DFFR_X1 _0818_ (
    .CK(clk),
    .D(_0473_),
    .Q(\regfile.reg_bank[1] [24]),
    .QN(_0124_),
    .RN(_0343_)
  );
  DFFR_X1 _0819_ (
    .CK(clk),
    .D(_0474_),
    .Q(\regfile.reg_bank[1] [25]),
    .QN(_0123_),
    .RN(_0344_)
  );
  DFFR_X1 _0820_ (
    .CK(clk),
    .D(_0475_),
    .Q(\regfile.reg_bank[1] [26]),
    .QN(_0122_),
    .RN(_0345_)
  );
  DFFR_X1 _0821_ (
    .CK(clk),
    .D(_0476_),
    .Q(\regfile.reg_bank[1] [27]),
    .QN(_0121_),
    .RN(_0346_)
  );
  DFFR_X1 _0822_ (
    .CK(clk),
    .D(_0477_),
    .Q(\regfile.reg_bank[1] [28]),
    .QN(_0120_),
    .RN(_0347_)
  );
  DFFR_X1 _0823_ (
    .CK(clk),
    .D(_0478_),
    .Q(\regfile.reg_bank[1] [29]),
    .QN(_0119_),
    .RN(_0348_)
  );
  DFFR_X1 _0824_ (
    .CK(clk),
    .D(_0479_),
    .Q(\regfile.reg_bank[1] [30]),
    .QN(_0118_),
    .RN(_0349_)
  );
  DFFR_X1 _0825_ (
    .CK(clk),
    .D(_0480_),
    .Q(\regfile.reg_bank[1] [31]),
    .QN(_0117_),
    .RN(_0350_)
  );
  DFFR_X1 _0826_ (
    .CK(clk),
    .D(_0481_),
    .Q(\regfile.reg_bank[0] [0]),
    .QN(_0116_),
    .RN(_0351_)
  );
  DFFR_X1 _0827_ (
    .CK(clk),
    .D(_0482_),
    .Q(\regfile.reg_bank[0] [1]),
    .QN(_0115_),
    .RN(_0352_)
  );
  DFFR_X1 _0828_ (
    .CK(clk),
    .D(_0483_),
    .Q(\regfile.reg_bank[0] [2]),
    .QN(_0114_),
    .RN(_0353_)
  );
  DFFR_X1 _0829_ (
    .CK(clk),
    .D(_0484_),
    .Q(\regfile.reg_bank[0] [3]),
    .QN(_0113_),
    .RN(_0354_)
  );
  DFFR_X1 _0830_ (
    .CK(clk),
    .D(_0485_),
    .Q(\regfile.reg_bank[0] [4]),
    .QN(_0112_),
    .RN(_0355_)
  );
  DFFR_X1 _0831_ (
    .CK(clk),
    .D(_0486_),
    .Q(\regfile.reg_bank[0] [5]),
    .QN(_0111_),
    .RN(_0356_)
  );
  DFFR_X1 _0832_ (
    .CK(clk),
    .D(_0487_),
    .Q(\regfile.reg_bank[0] [6]),
    .QN(_0110_),
    .RN(_0357_)
  );
  DFFR_X1 _0833_ (
    .CK(clk),
    .D(_0488_),
    .Q(\regfile.reg_bank[0] [7]),
    .QN(_0109_),
    .RN(_0358_)
  );
  DFFR_X1 _0834_ (
    .CK(clk),
    .D(_0489_),
    .Q(\regfile.reg_bank[0] [8]),
    .QN(_0108_),
    .RN(_0359_)
  );
  DFFR_X1 _0835_ (
    .CK(clk),
    .D(_0490_),
    .Q(\regfile.reg_bank[0] [9]),
    .QN(_0107_),
    .RN(_0360_)
  );
  DFFR_X1 _0836_ (
    .CK(clk),
    .D(_0491_),
    .Q(\regfile.reg_bank[0] [10]),
    .QN(_0106_),
    .RN(_0361_)
  );
  DFFR_X1 _0837_ (
    .CK(clk),
    .D(_0492_),
    .Q(\regfile.reg_bank[0] [11]),
    .QN(_0105_),
    .RN(_0362_)
  );
  DFFR_X1 _0838_ (
    .CK(clk),
    .D(_0493_),
    .Q(\regfile.reg_bank[0] [12]),
    .QN(_0104_),
    .RN(_0363_)
  );
  DFFR_X1 _0839_ (
    .CK(clk),
    .D(_0494_),
    .Q(\regfile.reg_bank[0] [13]),
    .QN(_0103_),
    .RN(_0364_)
  );
  DFFR_X1 _0840_ (
    .CK(clk),
    .D(_0365_),
    .Q(\regfile.reg_bank[0] [14]),
    .QN(_0233_),
    .RN(_0234_)
  );
  DFFR_X1 _0841_ (
    .CK(clk),
    .D(_0366_),
    .Q(\regfile.reg_bank[0] [15]),
    .QN(_0232_),
    .RN(_0235_)
  );
  DFFR_X1 _0842_ (
    .CK(clk),
    .D(_0367_),
    .Q(\regfile.reg_bank[0] [16]),
    .QN(_0231_),
    .RN(_0236_)
  );
  DFFR_X1 _0843_ (
    .CK(clk),
    .D(_0368_),
    .Q(\regfile.reg_bank[0] [17]),
    .QN(_0230_),
    .RN(_0237_)
  );
  DFFR_X1 _0844_ (
    .CK(clk),
    .D(_0369_),
    .Q(\regfile.reg_bank[0] [18]),
    .QN(_0229_),
    .RN(_0238_)
  );
  DFFR_X1 _0845_ (
    .CK(clk),
    .D(_0370_),
    .Q(\regfile.reg_bank[0] [19]),
    .QN(_0228_),
    .RN(_0239_)
  );
  DFFR_X1 _0846_ (
    .CK(clk),
    .D(_0371_),
    .Q(\regfile.reg_bank[0] [20]),
    .QN(_0227_),
    .RN(_0240_)
  );
  DFFR_X1 _0847_ (
    .CK(clk),
    .D(_0372_),
    .Q(\regfile.reg_bank[0] [21]),
    .QN(_0226_),
    .RN(_0241_)
  );
  DFFR_X1 _0848_ (
    .CK(clk),
    .D(_0373_),
    .Q(\regfile.reg_bank[0] [22]),
    .QN(_0225_),
    .RN(_0242_)
  );
  DFFR_X1 _0849_ (
    .CK(clk),
    .D(_0374_),
    .Q(\regfile.reg_bank[0] [23]),
    .QN(_0224_),
    .RN(_0243_)
  );
  DFFR_X1 _0850_ (
    .CK(clk),
    .D(_0375_),
    .Q(\regfile.reg_bank[0] [24]),
    .QN(_0223_),
    .RN(_0244_)
  );
  DFFR_X1 _0851_ (
    .CK(clk),
    .D(_0376_),
    .Q(\regfile.reg_bank[0] [25]),
    .QN(_0222_),
    .RN(_0245_)
  );
  DFFR_X1 _0852_ (
    .CK(clk),
    .D(_0377_),
    .Q(\regfile.reg_bank[0] [26]),
    .QN(_0221_),
    .RN(_0246_)
  );
  DFFR_X1 _0853_ (
    .CK(clk),
    .D(_0378_),
    .Q(\regfile.reg_bank[0] [27]),
    .QN(_0220_),
    .RN(_0247_)
  );
  DFFR_X1 _0854_ (
    .CK(clk),
    .D(_0379_),
    .Q(\regfile.reg_bank[0] [28]),
    .QN(_0219_),
    .RN(_0248_)
  );
  DFFR_X1 _0855_ (
    .CK(clk),
    .D(_0380_),
    .Q(\regfile.reg_bank[0] [29]),
    .QN(_0218_),
    .RN(_0249_)
  );
  DFFR_X1 _0856_ (
    .CK(clk),
    .D(_0381_),
    .Q(\regfile.reg_bank[0] [30]),
    .QN(_0217_),
    .RN(_0250_)
  );
  DFFR_X1 _0857_ (
    .CK(clk),
    .D(_0382_),
    .Q(\regfile.reg_bank[0] [31]),
    .QN(_0216_),
    .RN(_0251_)
  );
  DFFR_X1 _0858_ (
    .CK(clk),
    .D(_0383_),
    .Q(\write_ctrl.bvalid ),
    .QN(_0215_),
    .RN(_0252_)
  );
  DFFR_X1 _0859_ (
    .CK(clk),
    .D(_0008_),
    .Q(\write_ctrl.write_enable ),
    .QN(_0214_),
    .RN(_0253_)
  );
  DFFR_X1 _0860_ (
    .CK(clk),
    .D(_0384_),
    .Q(\regfile.reg_bank[3] [0]),
    .QN(_0213_),
    .RN(_0254_)
  );
  DFFR_X1 _0861_ (
    .CK(clk),
    .D(_0385_),
    .Q(\regfile.reg_bank[3] [1]),
    .QN(_0212_),
    .RN(_0255_)
  );
  DFFR_X1 _0862_ (
    .CK(clk),
    .D(_0386_),
    .Q(\regfile.reg_bank[3] [2]),
    .QN(_0211_),
    .RN(_0256_)
  );
  DFFR_X1 _0863_ (
    .CK(clk),
    .D(_0387_),
    .Q(\regfile.reg_bank[3] [3]),
    .QN(_0210_),
    .RN(_0257_)
  );
  DFFR_X1 _0864_ (
    .CK(clk),
    .D(_0388_),
    .Q(\regfile.reg_bank[3] [4]),
    .QN(_0209_),
    .RN(_0258_)
  );
  DFFR_X1 _0865_ (
    .CK(clk),
    .D(_0389_),
    .Q(\regfile.reg_bank[3] [5]),
    .QN(_0208_),
    .RN(_0259_)
  );
  DFFR_X1 _0866_ (
    .CK(clk),
    .D(_0390_),
    .Q(\regfile.reg_bank[3] [6]),
    .QN(_0207_),
    .RN(_0260_)
  );
  DFFR_X1 _0867_ (
    .CK(clk),
    .D(_0391_),
    .Q(\regfile.reg_bank[3] [7]),
    .QN(_0206_),
    .RN(_0261_)
  );
  DFFR_X1 _0868_ (
    .CK(clk),
    .D(_0392_),
    .Q(\regfile.reg_bank[3] [8]),
    .QN(_0205_),
    .RN(_0262_)
  );
  DFFR_X1 _0869_ (
    .CK(clk),
    .D(_0393_),
    .Q(\regfile.reg_bank[3] [9]),
    .QN(_0204_),
    .RN(_0263_)
  );
  DFFR_X1 _0870_ (
    .CK(clk),
    .D(_0394_),
    .Q(\regfile.reg_bank[3] [10]),
    .QN(_0203_),
    .RN(_0264_)
  );
  DFFR_X1 _0871_ (
    .CK(clk),
    .D(_0395_),
    .Q(\regfile.reg_bank[3] [11]),
    .QN(_0202_),
    .RN(_0265_)
  );
  DFFR_X1 _0872_ (
    .CK(clk),
    .D(_0396_),
    .Q(\regfile.reg_bank[3] [12]),
    .QN(_0201_),
    .RN(_0266_)
  );
  DFFR_X1 _0873_ (
    .CK(clk),
    .D(_0397_),
    .Q(\regfile.reg_bank[3] [13]),
    .QN(_0200_),
    .RN(_0267_)
  );
  DFFR_X1 _0874_ (
    .CK(clk),
    .D(_0398_),
    .Q(\regfile.reg_bank[3] [14]),
    .QN(_0199_),
    .RN(_0268_)
  );
  DFFR_X1 _0875_ (
    .CK(clk),
    .D(_0399_),
    .Q(\regfile.reg_bank[3] [15]),
    .QN(_0198_),
    .RN(_0269_)
  );
  DFFR_X1 _0876_ (
    .CK(clk),
    .D(_0400_),
    .Q(\regfile.reg_bank[3] [16]),
    .QN(_0197_),
    .RN(_0270_)
  );
  DFFR_X1 _0877_ (
    .CK(clk),
    .D(_0401_),
    .Q(\regfile.reg_bank[3] [17]),
    .QN(_0196_),
    .RN(_0271_)
  );
  DFFR_X1 _0878_ (
    .CK(clk),
    .D(_0402_),
    .Q(\regfile.reg_bank[3] [18]),
    .QN(_0195_),
    .RN(_0272_)
  );
  DFFR_X1 _0879_ (
    .CK(clk),
    .D(_0403_),
    .Q(\regfile.reg_bank[3] [19]),
    .QN(_0194_),
    .RN(_0273_)
  );
  DFFR_X1 _0880_ (
    .CK(clk),
    .D(_0404_),
    .Q(\regfile.reg_bank[3] [20]),
    .QN(_0193_),
    .RN(_0274_)
  );
  DFFR_X1 _0881_ (
    .CK(clk),
    .D(_0405_),
    .Q(\regfile.reg_bank[3] [21]),
    .QN(_0192_),
    .RN(_0275_)
  );
  DFFR_X1 _0882_ (
    .CK(clk),
    .D(_0406_),
    .Q(\regfile.reg_bank[3] [22]),
    .QN(_0191_),
    .RN(_0276_)
  );
  DFFR_X1 _0883_ (
    .CK(clk),
    .D(_0407_),
    .Q(\regfile.reg_bank[3] [23]),
    .QN(_0190_),
    .RN(_0277_)
  );
  DFFR_X1 _0884_ (
    .CK(clk),
    .D(_0408_),
    .Q(\regfile.reg_bank[3] [24]),
    .QN(_0189_),
    .RN(_0278_)
  );
  DFFR_X1 _0885_ (
    .CK(clk),
    .D(_0409_),
    .Q(\regfile.reg_bank[3] [25]),
    .QN(_0188_),
    .RN(_0279_)
  );
  DFFR_X1 _0886_ (
    .CK(clk),
    .D(_0410_),
    .Q(\regfile.reg_bank[3] [26]),
    .QN(_0187_),
    .RN(_0280_)
  );
  DFFR_X1 _0887_ (
    .CK(clk),
    .D(_0411_),
    .Q(\regfile.reg_bank[3] [27]),
    .QN(_0186_),
    .RN(_0281_)
  );
  DFFR_X1 _0888_ (
    .CK(clk),
    .D(_0412_),
    .Q(\regfile.reg_bank[3] [28]),
    .QN(_0185_),
    .RN(_0282_)
  );
  DFFR_X1 _0889_ (
    .CK(clk),
    .D(_0413_),
    .Q(\regfile.reg_bank[3] [29]),
    .QN(_0184_),
    .RN(_0283_)
  );
  DFFR_X1 _0890_ (
    .CK(clk),
    .D(_0414_),
    .Q(\regfile.reg_bank[3] [30]),
    .QN(_0183_),
    .RN(_0284_)
  );
  DFFR_X1 _0891_ (
    .CK(clk),
    .D(_0415_),
    .Q(\regfile.reg_bank[3] [31]),
    .QN(_0182_),
    .RN(_0285_)
  );
  assign _0365_ = _0005_ ? write_data[14] : \regfile.reg_bank[0] [14];
  assign _0366_ = _0005_ ? write_data[15] : \regfile.reg_bank[0] [15];
  assign _0367_ = _0005_ ? write_data[16] : \regfile.reg_bank[0] [16];
  assign _0368_ = _0005_ ? write_data[17] : \regfile.reg_bank[0] [17];
  assign _0369_ = _0005_ ? write_data[18] : \regfile.reg_bank[0] [18];
  assign _0370_ = _0005_ ? write_data[19] : \regfile.reg_bank[0] [19];
  assign _0371_ = _0005_ ? write_data[20] : \regfile.reg_bank[0] [20];
  assign _0372_ = _0005_ ? write_data[21] : \regfile.reg_bank[0] [21];
  assign _0373_ = _0005_ ? write_data[22] : \regfile.reg_bank[0] [22];
  assign _0374_ = _0005_ ? write_data[23] : \regfile.reg_bank[0] [23];
  assign _0375_ = _0005_ ? write_data[24] : \regfile.reg_bank[0] [24];
  assign _0376_ = _0005_ ? write_data[25] : \regfile.reg_bank[0] [25];
  assign _0377_ = _0005_ ? write_data[26] : \regfile.reg_bank[0] [26];
  assign _0378_ = _0005_ ? write_data[27] : \regfile.reg_bank[0] [27];
  assign _0379_ = _0005_ ? write_data[28] : \regfile.reg_bank[0] [28];
  assign _0380_ = _0005_ ? write_data[29] : \regfile.reg_bank[0] [29];
  assign _0381_ = _0005_ ? write_data[30] : \regfile.reg_bank[0] [30];
  assign _0382_ = _0005_ ? write_data[31] : \regfile.reg_bank[0] [31];
  assign _0383_ = _0001_ ? _0007_ : \write_ctrl.bvalid ;
  assign _0384_ = _0002_ ? write_data[0] : \regfile.reg_bank[3] [0];
  assign _0385_ = _0002_ ? write_data[1] : \regfile.reg_bank[3] [1];
  assign _0386_ = _0002_ ? write_data[2] : \regfile.reg_bank[3] [2];
  assign _0387_ = _0002_ ? write_data[3] : \regfile.reg_bank[3] [3];
  assign _0388_ = _0002_ ? write_data[4] : \regfile.reg_bank[3] [4];
  assign _0389_ = _0002_ ? write_data[5] : \regfile.reg_bank[3] [5];
  assign _0390_ = _0002_ ? write_data[6] : \regfile.reg_bank[3] [6];
  assign _0391_ = _0002_ ? write_data[7] : \regfile.reg_bank[3] [7];
  assign _0392_ = _0002_ ? write_data[8] : \regfile.reg_bank[3] [8];
  assign _0393_ = _0002_ ? write_data[9] : \regfile.reg_bank[3] [9];
  assign _0394_ = _0002_ ? write_data[10] : \regfile.reg_bank[3] [10];
  assign _0395_ = _0002_ ? write_data[11] : \regfile.reg_bank[3] [11];
  assign _0396_ = _0002_ ? write_data[12] : \regfile.reg_bank[3] [12];
  assign _0397_ = _0002_ ? write_data[13] : \regfile.reg_bank[3] [13];
  assign _0398_ = _0002_ ? write_data[14] : \regfile.reg_bank[3] [14];
  assign _0399_ = _0002_ ? write_data[15] : \regfile.reg_bank[3] [15];
  assign _0400_ = _0002_ ? write_data[16] : \regfile.reg_bank[3] [16];
  assign _0401_ = _0002_ ? write_data[17] : \regfile.reg_bank[3] [17];
  assign _0402_ = _0002_ ? write_data[18] : \regfile.reg_bank[3] [18];
  assign _0403_ = _0002_ ? write_data[19] : \regfile.reg_bank[3] [19];
  assign _0404_ = _0002_ ? write_data[20] : \regfile.reg_bank[3] [20];
  assign _0405_ = _0002_ ? write_data[21] : \regfile.reg_bank[3] [21];
  assign _0406_ = _0002_ ? write_data[22] : \regfile.reg_bank[3] [22];
  assign _0407_ = _0002_ ? write_data[23] : \regfile.reg_bank[3] [23];
  assign _0408_ = _0002_ ? write_data[24] : \regfile.reg_bank[3] [24];
  assign _0409_ = _0002_ ? write_data[25] : \regfile.reg_bank[3] [25];
  assign _0410_ = _0002_ ? write_data[26] : \regfile.reg_bank[3] [26];
  assign _0411_ = _0002_ ? write_data[27] : \regfile.reg_bank[3] [27];
  assign _0412_ = _0002_ ? write_data[28] : \regfile.reg_bank[3] [28];
  assign _0413_ = _0002_ ? write_data[29] : \regfile.reg_bank[3] [29];
  assign _0414_ = _0002_ ? write_data[30] : \regfile.reg_bank[3] [30];
  assign _0415_ = _0002_ ? write_data[31] : \regfile.reg_bank[3] [31];
  assign _0416_ = _0000_ ? _0006_ : \read_ctrl.rvalid ;
  assign _0417_ = _0003_ ? write_data[0] : \regfile.reg_bank[2] [0];
  assign _0418_ = _0003_ ? write_data[1] : \regfile.reg_bank[2] [1];
  assign _0419_ = _0003_ ? write_data[2] : \regfile.reg_bank[2] [2];
  assign _0420_ = _0003_ ? write_data[3] : \regfile.reg_bank[2] [3];
  assign _0421_ = _0003_ ? write_data[4] : \regfile.reg_bank[2] [4];
  assign _0422_ = _0003_ ? write_data[5] : \regfile.reg_bank[2] [5];
  assign _0423_ = _0003_ ? write_data[6] : \regfile.reg_bank[2] [6];
  assign _0424_ = _0003_ ? write_data[7] : \regfile.reg_bank[2] [7];
  assign _0425_ = _0003_ ? write_data[8] : \regfile.reg_bank[2] [8];
  assign _0426_ = _0003_ ? write_data[9] : \regfile.reg_bank[2] [9];
  assign _0427_ = _0003_ ? write_data[10] : \regfile.reg_bank[2] [10];
  assign _0428_ = _0003_ ? write_data[11] : \regfile.reg_bank[2] [11];
  assign _0429_ = _0003_ ? write_data[12] : \regfile.reg_bank[2] [12];
  assign _0430_ = _0003_ ? write_data[13] : \regfile.reg_bank[2] [13];
  assign _0431_ = _0003_ ? write_data[14] : \regfile.reg_bank[2] [14];
  assign _0432_ = _0003_ ? write_data[15] : \regfile.reg_bank[2] [15];
  assign _0433_ = _0003_ ? write_data[16] : \regfile.reg_bank[2] [16];
  assign _0434_ = _0003_ ? write_data[17] : \regfile.reg_bank[2] [17];
  assign _0435_ = _0003_ ? write_data[18] : \regfile.reg_bank[2] [18];
  assign _0436_ = _0003_ ? write_data[19] : \regfile.reg_bank[2] [19];
  assign _0437_ = _0003_ ? write_data[20] : \regfile.reg_bank[2] [20];
  assign _0438_ = _0003_ ? write_data[21] : \regfile.reg_bank[2] [21];
  assign _0439_ = _0003_ ? write_data[22] : \regfile.reg_bank[2] [22];
  assign _0440_ = _0003_ ? write_data[23] : \regfile.reg_bank[2] [23];
  assign _0441_ = _0003_ ? write_data[24] : \regfile.reg_bank[2] [24];
  assign _0442_ = _0003_ ? write_data[25] : \regfile.reg_bank[2] [25];
  assign _0443_ = _0003_ ? write_data[26] : \regfile.reg_bank[2] [26];
  assign _0444_ = _0003_ ? write_data[27] : \regfile.reg_bank[2] [27];
  assign _0445_ = _0003_ ? write_data[28] : \regfile.reg_bank[2] [28];
  assign _0446_ = _0003_ ? write_data[29] : \regfile.reg_bank[2] [29];
  assign _0447_ = _0003_ ? write_data[30] : \regfile.reg_bank[2] [30];
  assign _0448_ = _0003_ ? write_data[31] : \regfile.reg_bank[2] [31];
  assign _0449_ = _0004_ ? write_data[0] : \regfile.reg_bank[1] [0];
  assign _0450_ = _0004_ ? write_data[1] : \regfile.reg_bank[1] [1];
  assign _0451_ = _0004_ ? write_data[2] : \regfile.reg_bank[1] [2];
  assign _0452_ = _0004_ ? write_data[3] : \regfile.reg_bank[1] [3];
  assign _0453_ = _0004_ ? write_data[4] : \regfile.reg_bank[1] [4];
  assign _0454_ = _0004_ ? write_data[5] : \regfile.reg_bank[1] [5];
  assign _0455_ = _0004_ ? write_data[6] : \regfile.reg_bank[1] [6];
  assign _0456_ = _0004_ ? write_data[7] : \regfile.reg_bank[1] [7];
  assign _0457_ = _0004_ ? write_data[8] : \regfile.reg_bank[1] [8];
  assign _0458_ = _0004_ ? write_data[9] : \regfile.reg_bank[1] [9];
  assign _0459_ = _0004_ ? write_data[10] : \regfile.reg_bank[1] [10];
  assign _0460_ = _0004_ ? write_data[11] : \regfile.reg_bank[1] [11];
  assign _0461_ = _0004_ ? write_data[12] : \regfile.reg_bank[1] [12];
  assign _0462_ = _0004_ ? write_data[13] : \regfile.reg_bank[1] [13];
  assign _0463_ = _0004_ ? write_data[14] : \regfile.reg_bank[1] [14];
  assign _0464_ = _0004_ ? write_data[15] : \regfile.reg_bank[1] [15];
  assign _0465_ = _0004_ ? write_data[16] : \regfile.reg_bank[1] [16];
  assign _0466_ = _0004_ ? write_data[17] : \regfile.reg_bank[1] [17];
  assign _0467_ = _0004_ ? write_data[18] : \regfile.reg_bank[1] [18];
  assign _0468_ = _0004_ ? write_data[19] : \regfile.reg_bank[1] [19];
  assign _0469_ = _0004_ ? write_data[20] : \regfile.reg_bank[1] [20];
  assign _0470_ = _0004_ ? write_data[21] : \regfile.reg_bank[1] [21];
  assign _0471_ = _0004_ ? write_data[22] : \regfile.reg_bank[1] [22];
  assign _0472_ = _0004_ ? write_data[23] : \regfile.reg_bank[1] [23];
  assign _0473_ = _0004_ ? write_data[24] : \regfile.reg_bank[1] [24];
  assign _0474_ = _0004_ ? write_data[25] : \regfile.reg_bank[1] [25];
  assign _0475_ = _0004_ ? write_data[26] : \regfile.reg_bank[1] [26];
  assign _0476_ = _0004_ ? write_data[27] : \regfile.reg_bank[1] [27];
  assign _0477_ = _0004_ ? write_data[28] : \regfile.reg_bank[1] [28];
  assign _0478_ = _0004_ ? write_data[29] : \regfile.reg_bank[1] [29];
  assign _0479_ = _0004_ ? write_data[30] : \regfile.reg_bank[1] [30];
  assign _0480_ = _0004_ ? write_data[31] : \regfile.reg_bank[1] [31];
  assign _0481_ = _0005_ ? write_data[0] : \regfile.reg_bank[0] [0];
  assign _0482_ = _0005_ ? write_data[1] : \regfile.reg_bank[0] [1];
  assign _0483_ = _0005_ ? write_data[2] : \regfile.reg_bank[0] [2];
  assign _0484_ = _0005_ ? write_data[3] : \regfile.reg_bank[0] [3];
  assign _0485_ = _0005_ ? write_data[4] : \regfile.reg_bank[0] [4];
  assign _0486_ = _0005_ ? write_data[5] : \regfile.reg_bank[0] [5];
  assign _0487_ = _0005_ ? write_data[6] : \regfile.reg_bank[0] [6];
  assign _0488_ = _0005_ ? write_data[7] : \regfile.reg_bank[0] [7];
  assign _0489_ = _0005_ ? write_data[8] : \regfile.reg_bank[0] [8];
  assign _0490_ = _0005_ ? write_data[9] : \regfile.reg_bank[0] [9];
  assign _0491_ = _0005_ ? write_data[10] : \regfile.reg_bank[0] [10];
  assign _0492_ = _0005_ ? write_data[11] : \regfile.reg_bank[0] [11];
  assign _0493_ = _0005_ ? write_data[12] : \regfile.reg_bank[0] [12];
  assign _0494_ = _0005_ ? write_data[13] : \regfile.reg_bank[0] [13];
  assign address_valid = \decoder.valid ;
  assign arready = \read_ctrl.rvalid ;
  assign awready = \write_ctrl.bvalid ;
  assign bvalid = \write_ctrl.bvalid ;
  assign \decoder.address  = address;
  assign \read_ctrl.address_valid  = \decoder.valid ;
  assign \read_ctrl.arready  = \read_ctrl.rvalid ;
  assign \read_ctrl.arvalid  = arvalid;
  assign \read_ctrl.clk  = clk;
  assign \read_ctrl.rready  = rready;
  assign \read_ctrl.rst  = rst;
  assign \regfile.clk  = clk;
  assign \regfile.i  = 32'd4;
  assign \regfile.read_data  = read_data;
  assign \regfile.rst  = rst;
  assign \regfile.write_data  = write_data;
  assign \regfile.write_enable  = \write_ctrl.write_enable ;
  assign rvalid = \read_ctrl.rvalid ;
  assign wready = \write_ctrl.bvalid ;
  assign \write_ctrl.address_valid  = \decoder.valid ;
  assign \write_ctrl.awready  = \write_ctrl.bvalid ;
  assign \write_ctrl.awvalid  = awvalid;
  assign \write_ctrl.bready  = bready;
  assign \write_ctrl.clk  = clk;
  assign \write_ctrl.rst  = rst;
  assign \write_ctrl.wready  = \write_ctrl.bvalid ;
  assign \write_ctrl.wvalid  = wvalid;
  assign write_enable = \write_ctrl.write_enable ;
endmodule
