###############################################################################
# Created by write_sdc
###############################################################################
current_design axi_slave_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_uncertainty 0.2000 clk
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_address[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_address[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_data[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {write_enable}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {read_data[9]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
