/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

module \$paramod\spi_clock_divider\DIVIDER=s32'00000000000000000000000000000100 (clk, rst, spi_clk);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output spi_clk;
  wire spi_clk;
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire [31:0] counter;
  INV_X1 _120_ (
    .A(counter[20]),
    .ZN(_022_)
  );
  INV_X1 _121_ (
    .A(counter[13]),
    .ZN(_023_)
  );
  INV_X1 _122_ (
    .A(counter[27]),
    .ZN(_024_)
  );
  INV_X1 _123_ (
    .A(counter[26]),
    .ZN(_025_)
  );
  INV_X1 _124_ (
    .A(counter[25]),
    .ZN(_026_)
  );
  INV_X1 _125_ (
    .A(counter[21]),
    .ZN(_027_)
  );
  INV_X1 _126_ (
    .A(counter[19]),
    .ZN(_028_)
  );
  INV_X1 _127_ (
    .A(counter[15]),
    .ZN(_029_)
  );
  INV_X1 _128_ (
    .A(counter[14]),
    .ZN(_030_)
  );
  INV_X1 _129_ (
    .A(counter[0]),
    .ZN(_000_[0])
  );
  INV_X1 _130_ (
    .A(spi_clk),
    .ZN(_052_)
  );
  NAND2_X1 _131_ (
    .A1(counter[1]),
    .A2(counter[0]),
    .ZN(_031_)
  );
  NAND3_X1 _132_ (
    .A1(counter[2]),
    .A2(counter[1]),
    .A3(counter[0]),
    .ZN(_032_)
  );
  AND4_X1 _133_ (
    .A1(counter[2]),
    .A2(counter[3]),
    .A3(counter[1]),
    .A4(counter[0]),
    .ZN(_033_)
  );
  NAND2_X1 _134_ (
    .A1(counter[4]),
    .A2(_033_),
    .ZN(_034_)
  );
  NAND3_X1 _135_ (
    .A1(counter[4]),
    .A2(counter[5]),
    .A3(_033_),
    .ZN(_035_)
  );
  AND4_X1 _136_ (
    .A1(counter[6]),
    .A2(counter[4]),
    .A3(counter[5]),
    .A4(_033_),
    .ZN(_036_)
  );
  AND2_X1 _137_ (
    .A1(counter[7]),
    .A2(_036_),
    .ZN(_037_)
  );
  AND4_X1 _138_ (
    .A1(counter[7]),
    .A2(counter[8]),
    .A3(counter[9]),
    .A4(_036_),
    .ZN(_038_)
  );
  AND2_X1 _139_ (
    .A1(counter[10]),
    .A2(_038_),
    .ZN(_039_)
  );
  NAND2_X1 _140_ (
    .A1(counter[11]),
    .A2(_039_),
    .ZN(_040_)
  );
  NAND4_X1 _141_ (
    .A1(counter[12]),
    .A2(counter[10]),
    .A3(counter[11]),
    .A4(_038_),
    .ZN(_041_)
  );
  NOR2_X1 _142_ (
    .A1(_023_),
    .A2(_041_),
    .ZN(_042_)
  );
  NOR4_X1 _143_ (
    .A1(_023_),
    .A2(_029_),
    .A3(_030_),
    .A4(_041_),
    .ZN(_043_)
  );
  AND2_X1 _144_ (
    .A1(counter[16]),
    .A2(_043_),
    .ZN(_044_)
  );
  NAND2_X1 _145_ (
    .A1(counter[17]),
    .A2(_044_),
    .ZN(_045_)
  );
  NAND4_X1 _146_ (
    .A1(counter[18]),
    .A2(counter[17]),
    .A3(counter[16]),
    .A4(_043_),
    .ZN(_046_)
  );
  NOR2_X1 _147_ (
    .A1(_028_),
    .A2(_046_),
    .ZN(_047_)
  );
  NOR4_X1 _148_ (
    .A1(_022_),
    .A2(_027_),
    .A3(_028_),
    .A4(_046_),
    .ZN(_048_)
  );
  AND2_X1 _149_ (
    .A1(counter[22]),
    .A2(_048_),
    .ZN(_049_)
  );
  NAND2_X1 _150_ (
    .A1(counter[23]),
    .A2(_049_),
    .ZN(_050_)
  );
  NAND4_X1 _151_ (
    .A1(counter[24]),
    .A2(counter[23]),
    .A3(counter[22]),
    .A4(_048_),
    .ZN(_051_)
  );
  NOR2_X1 _152_ (
    .A1(_026_),
    .A2(_051_),
    .ZN(_002_)
  );
  NOR4_X1 _153_ (
    .A1(_024_),
    .A2(_025_),
    .A3(_026_),
    .A4(_051_),
    .ZN(_003_)
  );
  NAND2_X1 _154_ (
    .A1(counter[28]),
    .A2(_003_),
    .ZN(_004_)
  );
  NAND3_X1 _155_ (
    .A1(counter[29]),
    .A2(counter[28]),
    .A3(_003_),
    .ZN(_005_)
  );
  NAND4_X1 _156_ (
    .A1(counter[30]),
    .A2(counter[29]),
    .A3(counter[28]),
    .A4(_003_),
    .ZN(_006_)
  );
  XNOR2_X1 _157_ (
    .A(counter[30]),
    .B(_005_),
    .ZN(_000_[30])
  );
  XNOR2_X1 _158_ (
    .A(counter[29]),
    .B(_004_),
    .ZN(_000_[29])
  );
  XOR2_X1 _159_ (
    .A(counter[28]),
    .B(_003_),
    .Z(_000_[28])
  );
  AOI21_X1 _160_ (
    .A(counter[27]),
    .B1(counter[26]),
    .B2(_002_),
    .ZN(_007_)
  );
  NOR2_X1 _161_ (
    .A1(_003_),
    .A2(_007_),
    .ZN(_000_[27])
  );
  XNOR2_X1 _162_ (
    .A(_025_),
    .B(_002_),
    .ZN(_000_[26])
  );
  XNOR2_X1 _163_ (
    .A(counter[25]),
    .B(_051_),
    .ZN(_000_[25])
  );
  XNOR2_X1 _164_ (
    .A(counter[24]),
    .B(_050_),
    .ZN(_000_[24])
  );
  XOR2_X1 _165_ (
    .A(counter[23]),
    .B(_049_),
    .Z(_000_[23])
  );
  XOR2_X1 _166_ (
    .A(counter[22]),
    .B(_048_),
    .Z(_000_[22])
  );
  AOI21_X1 _167_ (
    .A(counter[21]),
    .B1(_047_),
    .B2(counter[20]),
    .ZN(_008_)
  );
  NOR2_X1 _168_ (
    .A1(_048_),
    .A2(_008_),
    .ZN(_000_[21])
  );
  XNOR2_X1 _169_ (
    .A(_022_),
    .B(_047_),
    .ZN(_000_[20])
  );
  XNOR2_X1 _170_ (
    .A(counter[19]),
    .B(_046_),
    .ZN(_000_[19])
  );
  XNOR2_X1 _171_ (
    .A(counter[18]),
    .B(_045_),
    .ZN(_000_[18])
  );
  XOR2_X1 _172_ (
    .A(counter[17]),
    .B(_044_),
    .Z(_000_[17])
  );
  XOR2_X1 _173_ (
    .A(counter[16]),
    .B(_043_),
    .Z(_000_[16])
  );
  AOI21_X1 _174_ (
    .A(counter[15]),
    .B1(counter[14]),
    .B2(_042_),
    .ZN(_009_)
  );
  NOR2_X1 _175_ (
    .A1(_043_),
    .A2(_009_),
    .ZN(_000_[15])
  );
  XNOR2_X1 _176_ (
    .A(_030_),
    .B(_042_),
    .ZN(_000_[14])
  );
  XNOR2_X1 _177_ (
    .A(counter[13]),
    .B(_041_),
    .ZN(_000_[13])
  );
  XNOR2_X1 _178_ (
    .A(counter[12]),
    .B(_040_),
    .ZN(_000_[12])
  );
  XOR2_X1 _179_ (
    .A(counter[11]),
    .B(_039_),
    .Z(_000_[11])
  );
  XOR2_X1 _180_ (
    .A(counter[10]),
    .B(_038_),
    .Z(_000_[10])
  );
  AOI21_X1 _181_ (
    .A(counter[9]),
    .B1(_037_),
    .B2(counter[8]),
    .ZN(_010_)
  );
  NOR2_X1 _182_ (
    .A1(_038_),
    .A2(_010_),
    .ZN(_000_[9])
  );
  XOR2_X1 _183_ (
    .A(counter[8]),
    .B(_037_),
    .Z(_000_[8])
  );
  XOR2_X1 _184_ (
    .A(counter[7]),
    .B(_036_),
    .Z(_000_[7])
  );
  XNOR2_X1 _185_ (
    .A(counter[6]),
    .B(_035_),
    .ZN(_000_[6])
  );
  XNOR2_X1 _186_ (
    .A(counter[5]),
    .B(_034_),
    .ZN(_000_[5])
  );
  XOR2_X1 _187_ (
    .A(counter[4]),
    .B(_033_),
    .Z(_000_[4])
  );
  XNOR2_X1 _188_ (
    .A(counter[3]),
    .B(_032_),
    .ZN(_000_[3])
  );
  XNOR2_X1 _189_ (
    .A(counter[2]),
    .B(_031_),
    .ZN(_000_[2])
  );
  XNOR2_X1 _190_ (
    .A(counter[1]),
    .B(counter[0]),
    .ZN(_011_)
  );
  NOR4_X1 _191_ (
    .A1(counter[4]),
    .A2(counter[12]),
    .A3(counter[10]),
    .A4(counter[2]),
    .ZN(_012_)
  );
  NOR4_X1 _192_ (
    .A1(counter[20]),
    .A2(counter[6]),
    .A3(counter[7]),
    .A4(counter[8]),
    .ZN(_013_)
  );
  NOR4_X1 _193_ (
    .A1(counter[29]),
    .A2(counter[28]),
    .A3(counter[27]),
    .A4(counter[26]),
    .ZN(_014_)
  );
  NOR4_X1 _194_ (
    .A1(counter[9]),
    .A2(counter[13]),
    .A3(counter[31]),
    .A4(counter[30]),
    .ZN(_015_)
  );
  NAND4_X1 _195_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_014_),
    .A4(_015_),
    .ZN(_016_)
  );
  NOR4_X1 _196_ (
    .A1(counter[21]),
    .A2(counter[19]),
    .A3(counter[18]),
    .A4(counter[17]),
    .ZN(_017_)
  );
  NOR4_X1 _197_ (
    .A1(counter[25]),
    .A2(counter[24]),
    .A3(counter[23]),
    .A4(counter[22]),
    .ZN(_018_)
  );
  NOR4_X1 _198_ (
    .A1(counter[5]),
    .A2(counter[3]),
    .A3(counter[1]),
    .A4(_000_[0]),
    .ZN(_019_)
  );
  NOR4_X1 _199_ (
    .A1(counter[16]),
    .A2(counter[15]),
    .A3(counter[14]),
    .A4(counter[11]),
    .ZN(_020_)
  );
  NAND4_X1 _200_ (
    .A1(_017_),
    .A2(_018_),
    .A3(_019_),
    .A4(_020_),
    .ZN(_021_)
  );
  NOR2_X1 _201_ (
    .A1(_016_),
    .A2(_021_),
    .ZN(_001_)
  );
  NOR2_X1 _202_ (
    .A1(_011_),
    .A2(_001_),
    .ZN(_000_[1])
  );
  XNOR2_X1 _203_ (
    .A(counter[31]),
    .B(_006_),
    .ZN(_000_[31])
  );
  assign _086_ = ~rst;
  assign _087_ = ~rst;
  assign _088_ = ~rst;
  assign _089_ = ~rst;
  assign _090_ = ~rst;
  assign _091_ = ~rst;
  assign _092_ = ~rst;
  assign _093_ = ~rst;
  assign _094_ = ~rst;
  assign _095_ = ~rst;
  assign _096_ = ~rst;
  assign _097_ = ~rst;
  assign _098_ = ~rst;
  assign _099_ = ~rst;
  assign _100_ = ~rst;
  assign _101_ = ~rst;
  assign _102_ = ~rst;
  assign _103_ = ~rst;
  assign _104_ = ~rst;
  assign _105_ = ~rst;
  assign _106_ = ~rst;
  assign _107_ = ~rst;
  assign _108_ = ~rst;
  assign _109_ = ~rst;
  assign _110_ = ~rst;
  assign _111_ = ~rst;
  assign _112_ = ~rst;
  assign _113_ = ~rst;
  assign _114_ = ~rst;
  assign _115_ = ~rst;
  assign _116_ = ~rst;
  assign _117_ = ~rst;
  assign _118_ = ~rst;
  DFFR_X1 _237_ (
    .CK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .QN(_060_),
    .RN(_111_)
  );
  DFFR_X1 _238_ (
    .CK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .QN(_061_),
    .RN(_110_)
  );
  DFFR_X1 _239_ (
    .CK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .QN(_062_),
    .RN(_109_)
  );
  DFFR_X1 _240_ (
    .CK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .QN(_063_),
    .RN(_108_)
  );
  DFFR_X1 _241_ (
    .CK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .QN(_064_),
    .RN(_107_)
  );
  DFFR_X1 _242_ (
    .CK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .QN(_065_),
    .RN(_106_)
  );
  DFFR_X1 _243_ (
    .CK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .QN(_066_),
    .RN(_105_)
  );
  DFFR_X1 _244_ (
    .CK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .QN(_067_),
    .RN(_104_)
  );
  DFFR_X1 _245_ (
    .CK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .QN(_068_),
    .RN(_103_)
  );
  DFFR_X1 _246_ (
    .CK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .QN(_069_),
    .RN(_102_)
  );
  DFFR_X1 _247_ (
    .CK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .QN(_070_),
    .RN(_101_)
  );
  DFFR_X1 _248_ (
    .CK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .QN(_071_),
    .RN(_100_)
  );
  DFFR_X1 _249_ (
    .CK(clk),
    .D(_000_[12]),
    .Q(counter[12]),
    .QN(_072_),
    .RN(_099_)
  );
  DFFR_X1 _250_ (
    .CK(clk),
    .D(_000_[13]),
    .Q(counter[13]),
    .QN(_073_),
    .RN(_098_)
  );
  DFFR_X1 _251_ (
    .CK(clk),
    .D(_000_[14]),
    .Q(counter[14]),
    .QN(_074_),
    .RN(_097_)
  );
  DFFR_X1 _252_ (
    .CK(clk),
    .D(_000_[15]),
    .Q(counter[15]),
    .QN(_075_),
    .RN(_096_)
  );
  DFFR_X1 _253_ (
    .CK(clk),
    .D(_000_[16]),
    .Q(counter[16]),
    .QN(_076_),
    .RN(_095_)
  );
  DFFR_X1 _254_ (
    .CK(clk),
    .D(_000_[17]),
    .Q(counter[17]),
    .QN(_077_),
    .RN(_094_)
  );
  DFFR_X1 _255_ (
    .CK(clk),
    .D(_000_[18]),
    .Q(counter[18]),
    .QN(_078_),
    .RN(_093_)
  );
  DFFR_X1 _256_ (
    .CK(clk),
    .D(_000_[19]),
    .Q(counter[19]),
    .QN(_079_),
    .RN(_092_)
  );
  DFFR_X1 _257_ (
    .CK(clk),
    .D(_000_[20]),
    .Q(counter[20]),
    .QN(_080_),
    .RN(_091_)
  );
  DFFR_X1 _258_ (
    .CK(clk),
    .D(_000_[21]),
    .Q(counter[21]),
    .QN(_081_),
    .RN(_090_)
  );
  DFFR_X1 _259_ (
    .CK(clk),
    .D(_000_[22]),
    .Q(counter[22]),
    .QN(_082_),
    .RN(_089_)
  );
  DFFR_X1 _260_ (
    .CK(clk),
    .D(_000_[23]),
    .Q(counter[23]),
    .QN(_083_),
    .RN(_088_)
  );
  DFFR_X1 _261_ (
    .CK(clk),
    .D(_000_[24]),
    .Q(counter[24]),
    .QN(_084_),
    .RN(_087_)
  );
  DFFR_X1 _262_ (
    .CK(clk),
    .D(_000_[25]),
    .Q(counter[25]),
    .QN(_085_),
    .RN(_086_)
  );
  DFFR_X1 _263_ (
    .CK(clk),
    .D(_000_[26]),
    .Q(counter[26]),
    .QN(_053_),
    .RN(_118_)
  );
  DFFR_X1 _264_ (
    .CK(clk),
    .D(_000_[27]),
    .Q(counter[27]),
    .QN(_054_),
    .RN(_117_)
  );
  DFFR_X1 _265_ (
    .CK(clk),
    .D(_000_[28]),
    .Q(counter[28]),
    .QN(_055_),
    .RN(_116_)
  );
  DFFR_X1 _266_ (
    .CK(clk),
    .D(_000_[29]),
    .Q(counter[29]),
    .QN(_056_),
    .RN(_115_)
  );
  DFFR_X1 _267_ (
    .CK(clk),
    .D(_000_[30]),
    .Q(counter[30]),
    .QN(_059_),
    .RN(_112_)
  );
  DFFR_X1 _268_ (
    .CK(clk),
    .D(_000_[31]),
    .Q(counter[31]),
    .QN(_058_),
    .RN(_113_)
  );
  DFFR_X1 _269_ (
    .CK(clk),
    .D(_119_),
    .Q(spi_clk),
    .QN(_057_),
    .RN(_114_)
  );
  assign _119_ = _001_ ? _052_ : spi_clk;
endmodule

module \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, rst, load, shift_enable, tx_data, miso, mosi, rx_data, shift_done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input load;
  wire load;
  input shift_enable;
  wire shift_enable;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  input miso;
  wire miso;
  output mosi;
  wire mosi;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  output shift_done;
  wire shift_done;
  wire [3:0] _000_;
  wire [7:0] _001_;
  wire _002_;
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire [3:0] bit_count;
  wire [7:0] tx_shift;
  INV_X1 _091_ (
    .A(load),
    .ZN(_005_)
  );
  INV_X1 _092_ (
    .A(shift_enable),
    .ZN(_006_)
  );
  INV_X1 _093_ (
    .A(tx_shift[5]),
    .ZN(_007_)
  );
  INV_X1 _094_ (
    .A(tx_shift[4]),
    .ZN(_008_)
  );
  INV_X1 _095_ (
    .A(tx_shift[3]),
    .ZN(_009_)
  );
  INV_X1 _096_ (
    .A(tx_shift[2]),
    .ZN(_010_)
  );
  INV_X1 _097_ (
    .A(tx_shift[1]),
    .ZN(_011_)
  );
  INV_X1 _098_ (
    .A(tx_shift[0]),
    .ZN(_012_)
  );
  INV_X1 _099_ (
    .A(tx_shift[6]),
    .ZN(_013_)
  );
  NOR2_X1 _100_ (
    .A1(load),
    .A2(_006_),
    .ZN(_014_)
  );
  NAND2_X1 _101_ (
    .A1(_005_),
    .A2(shift_enable),
    .ZN(_015_)
  );
  AND2_X1 _102_ (
    .A1(rx_data[5]),
    .A2(_014_),
    .ZN(_001_[6])
  );
  AND2_X1 _103_ (
    .A1(rx_data[4]),
    .A2(_014_),
    .ZN(_001_[5])
  );
  AND2_X1 _104_ (
    .A1(rx_data[3]),
    .A2(_014_),
    .ZN(_001_[4])
  );
  AND2_X1 _105_ (
    .A1(rx_data[2]),
    .A2(_014_),
    .ZN(_001_[3])
  );
  AND2_X1 _106_ (
    .A1(rx_data[1]),
    .A2(_014_),
    .ZN(_001_[2])
  );
  AND2_X1 _107_ (
    .A1(rx_data[0]),
    .A2(_014_),
    .ZN(_001_[1])
  );
  AND2_X1 _108_ (
    .A1(miso),
    .A2(_014_),
    .ZN(_001_[0])
  );
  NAND2_X1 _109_ (
    .A1(load),
    .A2(tx_data[6]),
    .ZN(_016_)
  );
  OAI21_X1 _110_ (
    .A(_016_),
    .B1(_015_),
    .B2(_007_),
    .ZN(_003_[6])
  );
  NAND2_X1 _111_ (
    .A1(load),
    .A2(tx_data[5]),
    .ZN(_017_)
  );
  OAI21_X1 _112_ (
    .A(_017_),
    .B1(_015_),
    .B2(_008_),
    .ZN(_003_[5])
  );
  NAND2_X1 _113_ (
    .A1(load),
    .A2(tx_data[4]),
    .ZN(_018_)
  );
  OAI21_X1 _114_ (
    .A(_018_),
    .B1(_015_),
    .B2(_009_),
    .ZN(_003_[4])
  );
  NAND2_X1 _115_ (
    .A1(load),
    .A2(tx_data[3]),
    .ZN(_019_)
  );
  OAI21_X1 _116_ (
    .A(_019_),
    .B1(_015_),
    .B2(_010_),
    .ZN(_003_[3])
  );
  NAND2_X1 _117_ (
    .A1(load),
    .A2(tx_data[2]),
    .ZN(_020_)
  );
  OAI21_X1 _118_ (
    .A(_020_),
    .B1(_015_),
    .B2(_011_),
    .ZN(_003_[2])
  );
  NAND2_X1 _119_ (
    .A1(load),
    .A2(tx_data[1]),
    .ZN(_021_)
  );
  OAI21_X1 _120_ (
    .A(_021_),
    .B1(_015_),
    .B2(_012_),
    .ZN(_003_[1])
  );
  AND2_X1 _121_ (
    .A1(load),
    .A2(tx_data[0]),
    .ZN(_003_[0])
  );
  NAND3_X1 _122_ (
    .A1(bit_count[0]),
    .A2(bit_count[2]),
    .A3(bit_count[1]),
    .ZN(_022_)
  );
  INV_X1 _123_ (
    .A(_022_),
    .ZN(_023_)
  );
  AOI21_X1 _124_ (
    .A(bit_count[2]),
    .B1(bit_count[1]),
    .B2(bit_count[0]),
    .ZN(_024_)
  );
  NOR3_X1 _125_ (
    .A1(_015_),
    .A2(_023_),
    .A3(_024_),
    .ZN(_000_[2])
  );
  OAI211_X1 _126_ (
    .A(_005_),
    .B(shift_enable),
    .C1(bit_count[1]),
    .C2(bit_count[0]),
    .ZN(_025_)
  );
  AOI21_X1 _127_ (
    .A(_025_),
    .B1(bit_count[1]),
    .B2(bit_count[0]),
    .ZN(_000_[1])
  );
  NOR2_X1 _128_ (
    .A1(bit_count[0]),
    .A2(_015_),
    .ZN(_000_[0])
  );
  NAND2_X1 _129_ (
    .A1(_005_),
    .A2(_006_),
    .ZN(_004_)
  );
  AND2_X1 _130_ (
    .A1(rx_data[6]),
    .A2(_014_),
    .ZN(_001_[7])
  );
  NAND2_X1 _131_ (
    .A1(load),
    .A2(tx_data[7]),
    .ZN(_026_)
  );
  OAI21_X1 _132_ (
    .A(_026_),
    .B1(_015_),
    .B2(_013_),
    .ZN(_003_[7])
  );
  OR4_X1 _133_ (
    .A1(load),
    .A2(_006_),
    .A3(bit_count[3]),
    .A4(_022_),
    .ZN(_027_)
  );
  INV_X1 _134_ (
    .A(_027_),
    .ZN(_002_)
  );
  NAND3_X1 _135_ (
    .A1(_005_),
    .A2(shift_enable),
    .A3(bit_count[3]),
    .ZN(_028_)
  );
  OAI21_X1 _136_ (
    .A(_027_),
    .B1(_028_),
    .B2(_023_),
    .ZN(_000_[3])
  );
  assign _050_ = ~rst;
  assign _051_ = ~rst;
  assign _052_ = ~rst;
  assign _053_ = ~rst;
  assign _054_ = ~rst;
  assign _055_ = ~rst;
  assign _056_ = ~rst;
  assign _057_ = ~rst;
  assign _058_ = ~rst;
  assign _059_ = ~rst;
  assign _060_ = ~rst;
  assign _061_ = ~rst;
  assign _062_ = ~rst;
  assign _063_ = ~rst;
  assign _064_ = ~rst;
  assign _065_ = ~rst;
  assign _066_ = ~rst;
  assign _067_ = ~rst;
  assign _068_ = ~rst;
  assign _069_ = ~rst;
  assign _070_ = ~rst;
  DFFR_X1 _158_ (
    .CK(clk),
    .D(_075_),
    .Q(rx_data[0]),
    .QN(_045_),
    .RN(_054_)
  );
  DFFR_X1 _159_ (
    .CK(clk),
    .D(_074_),
    .Q(rx_data[1]),
    .QN(_046_),
    .RN(_053_)
  );
  DFFR_X1 _160_ (
    .CK(clk),
    .D(_073_),
    .Q(rx_data[2]),
    .QN(_047_),
    .RN(_052_)
  );
  DFFR_X1 _161_ (
    .CK(clk),
    .D(_072_),
    .Q(rx_data[3]),
    .QN(_048_),
    .RN(_051_)
  );
  DFFR_X1 _162_ (
    .CK(clk),
    .D(_071_),
    .Q(rx_data[4]),
    .QN(_049_),
    .RN(_050_)
  );
  DFFR_X1 _163_ (
    .CK(clk),
    .D(_090_),
    .Q(rx_data[5]),
    .QN(_029_),
    .RN(_070_)
  );
  DFFR_X1 _164_ (
    .CK(clk),
    .D(_089_),
    .Q(rx_data[6]),
    .QN(_030_),
    .RN(_069_)
  );
  DFFR_X1 _165_ (
    .CK(clk),
    .D(_077_),
    .Q(rx_data[7]),
    .QN(_043_),
    .RN(_056_)
  );
  DFFR_X1 _166_ (
    .CK(clk),
    .D(_088_),
    .Q(tx_shift[0]),
    .QN(_031_),
    .RN(_068_)
  );
  DFFR_X1 _167_ (
    .CK(clk),
    .D(_087_),
    .Q(tx_shift[1]),
    .QN(_032_),
    .RN(_067_)
  );
  DFFR_X1 _168_ (
    .CK(clk),
    .D(_086_),
    .Q(tx_shift[2]),
    .QN(_033_),
    .RN(_066_)
  );
  DFFR_X1 _169_ (
    .CK(clk),
    .D(_085_),
    .Q(tx_shift[3]),
    .QN(_034_),
    .RN(_065_)
  );
  DFFR_X1 _170_ (
    .CK(clk),
    .D(_084_),
    .Q(tx_shift[4]),
    .QN(_035_),
    .RN(_064_)
  );
  DFFR_X1 _171_ (
    .CK(clk),
    .D(_083_),
    .Q(tx_shift[5]),
    .QN(_036_),
    .RN(_063_)
  );
  DFFR_X1 _172_ (
    .CK(clk),
    .D(_082_),
    .Q(tx_shift[6]),
    .QN(_037_),
    .RN(_062_)
  );
  DFFR_X1 _173_ (
    .CK(clk),
    .D(_078_),
    .Q(mosi),
    .QN(_042_),
    .RN(_057_)
  );
  DFFR_X1 _174_ (
    .CK(clk),
    .D(_081_),
    .Q(bit_count[0]),
    .QN(_038_),
    .RN(_061_)
  );
  DFFR_X1 _175_ (
    .CK(clk),
    .D(_080_),
    .Q(bit_count[1]),
    .QN(_039_),
    .RN(_060_)
  );
  DFFR_X1 _176_ (
    .CK(clk),
    .D(_076_),
    .Q(bit_count[2]),
    .QN(_044_),
    .RN(_055_)
  );
  DFFR_X1 _177_ (
    .CK(clk),
    .D(_079_),
    .Q(bit_count[3]),
    .QN(_040_),
    .RN(_059_)
  );
  DFFR_X1 _178_ (
    .CK(clk),
    .D(_002_),
    .Q(shift_done),
    .QN(_041_),
    .RN(_058_)
  );
  assign _071_ = _004_ ? _001_[4] : rx_data[4];
  assign _072_ = _004_ ? _001_[3] : rx_data[3];
  assign _073_ = _004_ ? _001_[2] : rx_data[2];
  assign _074_ = _004_ ? _001_[1] : rx_data[1];
  assign _075_ = _004_ ? _001_[0] : rx_data[0];
  assign _076_ = _004_ ? _000_[2] : bit_count[2];
  assign _077_ = _004_ ? _001_[7] : rx_data[7];
  assign _078_ = _004_ ? _003_[7] : mosi;
  assign _079_ = _004_ ? _000_[3] : bit_count[3];
  assign _080_ = _004_ ? _000_[1] : bit_count[1];
  assign _081_ = _004_ ? _000_[0] : bit_count[0];
  assign _082_ = _004_ ? _003_[6] : tx_shift[6];
  assign _083_ = _004_ ? _003_[5] : tx_shift[5];
  assign _084_ = _004_ ? _003_[4] : tx_shift[4];
  assign _085_ = _004_ ? _003_[3] : tx_shift[3];
  assign _086_ = _004_ ? _003_[2] : tx_shift[2];
  assign _087_ = _004_ ? _003_[1] : tx_shift[1];
  assign _088_ = _004_ ? _003_[0] : tx_shift[0];
  assign _089_ = _004_ ? _001_[6] : rx_data[6];
  assign _090_ = _004_ ? _001_[5] : rx_data[5];
  assign tx_shift[7] = mosi;
endmodule

module spi_chip_select(clk, rst, cs_enable, cs_n);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input cs_enable;
  wire cs_enable;
  output cs_n;
  wire cs_n;
  wire _0_;
  wire _1_;
  wire _2_;
  INV_X1 _3_ (
    .A(cs_enable),
    .ZN(_0_)
  );
  assign _2_ = ~rst;
  DFFS_X1 _5_ (
    .CK(clk),
    .D(_0_),
    .Q(cs_n),
    .QN(_1_),
    .SN(_2_)
  );
endmodule

module spi_master_fsm(clk, rst, start, shift_done, load, shift_enable, cs_enable, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input shift_done;
  wire shift_done;
  output load;
  wire load;
  output shift_enable;
  wire shift_enable;
  output cs_enable;
  wire cs_enable;
  output done;
  wire done;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire [1:0] state;
  INV_X1 _26_ (
    .A(state[0]),
    .ZN(_06_)
  );
  INV_X1 _27_ (
    .A(start),
    .ZN(_07_)
  );
  INV_X1 _28_ (
    .A(shift_done),
    .ZN(_08_)
  );
  AND2_X1 _29_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_01_)
  );
  AND2_X1 _30_ (
    .A1(_06_),
    .A2(state[1]),
    .ZN(_03_)
  );
  NAND3_X1 _31_ (
    .A1(_06_),
    .A2(state[1]),
    .A3(shift_done),
    .ZN(_09_)
  );
  NOR2_X1 _32_ (
    .A1(state[0]),
    .A2(state[1]),
    .ZN(_10_)
  );
  NAND2_X1 _33_ (
    .A1(start),
    .A2(_10_),
    .ZN(_11_)
  );
  NAND2_X1 _34_ (
    .A1(_09_),
    .A2(_11_),
    .ZN(_04_[0])
  );
  NOR2_X1 _35_ (
    .A1(_06_),
    .A2(state[1]),
    .ZN(_02_)
  );
  AOI22_X1 _36_ (
    .A1(_08_),
    .A2(_03_),
    .B1(_10_),
    .B2(_07_),
    .ZN(_05_)
  );
  OAI21_X1 _37_ (
    .A(_09_),
    .B1(state[1]),
    .B2(_06_),
    .ZN(_04_[1])
  );
  OR2_X1 _38_ (
    .A1(_03_),
    .A2(_02_),
    .ZN(_00_)
  );
  assign _18_ = ~rst;
  assign _19_ = ~rst;
  assign _20_ = ~rst;
  assign _21_ = ~rst;
  assign _22_ = ~rst;
  assign _23_ = ~rst;
  DFFR_X1 _45_ (
    .CK(clk),
    .D(_25_),
    .Q(state[0]),
    .QN(_14_),
    .RN(_21_)
  );
  DFFR_X1 _46_ (
    .CK(clk),
    .D(_24_),
    .Q(state[1]),
    .QN(_17_),
    .RN(_18_)
  );
  DFFR_X1 _47_ (
    .CK(clk),
    .D(_00_),
    .Q(cs_enable),
    .QN(_16_),
    .RN(_19_)
  );
  DFFR_X1 _48_ (
    .CK(clk),
    .D(_02_),
    .Q(load),
    .QN(_13_),
    .RN(_22_)
  );
  DFFR_X1 _49_ (
    .CK(clk),
    .D(_03_),
    .Q(shift_enable),
    .QN(_15_),
    .RN(_20_)
  );
  DFFR_X1 _50_ (
    .CK(clk),
    .D(_01_),
    .Q(done),
    .QN(_12_),
    .RN(_23_)
  );
  assign _24_ = _05_ ? _04_[1] : state[1];
  assign _25_ = _05_ ? _04_[0] : state[0];
endmodule

module spi_master_top(clk, rst, start, tx_data, miso, spi_clk, mosi, cs_n, rx_data, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  input miso;
  wire miso;
  output spi_clk;
  wire spi_clk;
  output mosi;
  wire mosi;
  output cs_n;
  wire cs_n;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  output done;
  wire done;
  wire cs_enable;
  wire load;
  wire shift_done;
  wire shift_enable;
  spi_chip_select chip_select (
    .clk(clk),
    .cs_enable(cs_enable),
    .cs_n(cs_n),
    .rst(rst)
  );
  \$paramod\spi_clock_divider\DIVIDER=s32'00000000000000000000000000000100  clock_divider (
    .clk(clk),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  spi_master_fsm fsm (
    .clk(clk),
    .cs_enable(cs_enable),
    .done(done),
    .load(load),
    .rst(rst),
    .shift_done(shift_done),
    .shift_enable(shift_enable),
    .start(start)
  );
  \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_register (
    .clk(spi_clk),
    .load(load),
    .miso(miso),
    .mosi(mosi),
    .rst(rst),
    .rx_data(rx_data),
    .shift_done(shift_done),
    .shift_enable(shift_enable),
    .tx_data(tx_data)
  );
endmodule
