/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_tx_fsm(clk, rst, start, data_in, tx, busy);
  wire [2:0] _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [2:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire [7:0] _20_;
  wire _21_;
  wire [2:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  wire [1:0] _26_;
  wire _27_;
  reg [2:0] bit_count;
  output busy;
  reg busy;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  input rst;
  wire rst;
  reg [7:0] shift_reg;
  input start;
  wire start;
  reg [1:0] state;
  output tx;
  reg tx;
  assign _05_ = bit_count + 1'h1;
  always @(posedge clk)
    if (_13_) shift_reg <= _02_;
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_08_) busy <= _01_;
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_14_) state <= _03_;
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 3'h0;
    else if (_15_) bit_count <= _00_;
  assign _06_ = { _21_, start } != 2'h2;
  assign _07_ = | { _21_, _19_ };
  assign _08_ = | { _21_, _24_ };
  assign _09_ = { _19_, _18_ } != 2'h2;
  assign _10_ = | { _21_, _24_, _23_, _19_ };
  assign _11_ = { _19_, _18_ } != 2'h3;
  assign _12_ = | { _23_, _19_ };
  assign _17_ = ~ rst;
  assign _13_ = & { _17_, _07_, _06_ };
  assign _14_ = & { _10_, _09_, _06_ };
  assign _15_ = & { _12_, _11_ };
  assign _16_ = | { _24_, _21_ };
  assign _18_ = bit_count == 3'h7;
  always @(posedge clk, posedge rst)
    if (rst) tx <= 1'h1;
    else tx <= _04_;
  function [7:0] _47_;
    input [7:0] a;
    input [15:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _47_ = b[7:0];
      2'b1?:
        _47_ = b[15:8];
      default:
        _47_ = a;
    endcase
  endfunction
  assign _02_ = _47_(8'hxx, { _20_, 1'h0, shift_reg[7:1] }, { _21_, _19_ });
  assign _20_ = start ? data_in : 8'hxx;
  assign _22_ = _18_ ? 3'hx : _05_;
  function [2:0] _50_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _50_ = b[2:0];
      2'b1?:
        _50_ = b[5:3];
      default:
        _50_ = a;
    endcase
  endfunction
  assign _00_ = _50_(3'hx, { 3'h0, _22_ }, { _23_, _19_ });
  function [1:0] _51_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _51_ = b[1:0];
      4'b??1?:
        _51_ = b[3:2];
      4'b?1??:
        _51_ = b[5:4];
      4'b1???:
        _51_ = b[7:6];
      default:
        _51_ = a;
    endcase
  endfunction
  assign _03_ = _51_(2'hx, { _26_, 2'h2, _25_, 2'h0 }, { _21_, _23_, _19_, _24_ });
  assign _25_ = _18_ ? 2'h3 : 2'hx;
  assign _19_ = state == 2'h2;
  assign _23_ = state == 2'h1;
  assign _26_ = start ? 2'h1 : 2'hx;
  function [0:0] _56_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _56_ = b[0:0];
      2'b1?:
        _56_ = b[1:1];
      default:
        _56_ = a;
    endcase
  endfunction
  assign _01_ = _56_(1'hx, { _27_, 1'h0 }, { _21_, _24_ });
  assign _24_ = state == 2'h3;
  assign _27_ = start ? 1'h1 : 1'h0;
  assign _21_ = ! state;
  function [0:0] _60_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _60_ = b[0:0];
      3'b?1?:
        _60_ = b[1:1];
      3'b1??:
        _60_ = b[2:2];
      default:
        _60_ = a;
    endcase
  endfunction
  assign _04_ = _60_(1'hx, { 1'h0, shift_reg[0], 1'h1 }, { _23_, _19_, _16_ });
endmodule
