/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

(* top =  1  *)
(* src = "rtl/fifo.v:1.1-44.10" *)
module fifo(clk, rst, wr_en, rd_en, data_in, data_out, full, empty);
  (* src = "rtl/fifo.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "rtl/fifo.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "rtl/fifo.v:4.11-4.16" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/fifo.v:5.11-5.16" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/fifo.v:6.17-6.24" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "rtl/fifo.v:8.22-8.30" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "rtl/fifo.v:9.12-9.16" *)
  output full;
  wire full;
  (* src = "rtl/fifo.v:10.12-10.17" *)
  output empty;
  wire empty;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo.v:28.23-28.36|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [1:0] _150_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo.v:29.22-29.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [2:0] _151_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo.v:34.23-34.36|rtl/fifo.v:28.23-28.36|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [1:0] _152_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo.v:35.22-35.34|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [2:0] _153_;
  (* src = "rtl/fifo.v:16.11-16.16" *)
  wire [2:0] count;
  (* src = "rtl/fifo.v:13.11-13.17" *)
  wire [7:0] \memory[0] ;
  (* src = "rtl/fifo.v:13.11-13.17" *)
  wire [7:0] \memory[1] ;
  (* src = "rtl/fifo.v:13.11-13.17" *)
  wire [7:0] \memory[2] ;
  (* src = "rtl/fifo.v:13.11-13.17" *)
  wire [7:0] \memory[3] ;
  (* src = "rtl/fifo.v:15.11-15.17" *)
  wire [1:0] rd_ptr;
  (* src = "rtl/fifo.v:14.11-14.17" *)
  wire [1:0] wr_ptr;
  INV_X1 _154_ (
    .A(count[1]),
    .ZN(_064_)
  );
  INV_X1 _155_ (
    .A(rst),
    .ZN(_002_)
  );
  NAND2_X1 _156_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_065_)
  );
  NAND3_X1 _157_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(wr_en),
    .ZN(_066_)
  );
  OR2_X1 _158_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_067_)
  );
  NOR2_X1 _159_ (
    .A1(count[2]),
    .A2(_067_),
    .ZN(empty)
  );
  OAI21_X1 _160_ (
    .A(rd_en),
    .B1(_067_),
    .B2(count[2]),
    .ZN(_068_)
  );
  XNOR2_X1 _161_ (
    .A(count[2]),
    .B(_066_),
    .ZN(_069_)
  );
  AOI21_X1 _162_ (
    .A(count[1]),
    .B1(_153_[1]),
    .B2(count[0]),
    .ZN(_070_)
  );
  XNOR2_X1 _163_ (
    .A(_153_[2]),
    .B(_070_),
    .ZN(_071_)
  );
  MUX2_X1 _164_ (
    .A(_071_),
    .B(_069_),
    .S(_068_),
    .Z(_063_)
  );
  NOR2_X1 _165_ (
    .A1(rd_ptr[1]),
    .A2(rd_ptr[0]),
    .ZN(_072_)
  );
  NOR2_X1 _166_ (
    .A1(rd_ptr[1]),
    .A2(_152_[0]),
    .ZN(_073_)
  );
  NOR2_X1 _167_ (
    .A1(_152_[0]),
    .A2(_000_),
    .ZN(_074_)
  );
  NOR2_X1 _168_ (
    .A1(rd_ptr[0]),
    .A2(_000_),
    .ZN(_075_)
  );
  AOI22_X1 _169_ (
    .A1(\memory[0] [7]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [7]),
    .ZN(_076_)
  );
  AOI22_X1 _170_ (
    .A1(\memory[1] [7]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [7]),
    .ZN(_077_)
  );
  NAND2_X1 _171_ (
    .A1(_076_),
    .A2(_077_),
    .ZN(_078_)
  );
  MUX2_X1 _172_ (
    .A(_078_),
    .B(data_out[7]),
    .S(_068_),
    .Z(_061_)
  );
  OAI211_X1 _173_ (
    .A(rd_ptr[0]),
    .B(rd_en),
    .C1(_067_),
    .C2(count[2]),
    .ZN(_079_)
  );
  XNOR2_X1 _174_ (
    .A(rd_ptr[1]),
    .B(_079_),
    .ZN(_057_)
  );
  NOR2_X1 _175_ (
    .A1(_153_[2]),
    .A2(_067_),
    .ZN(full)
  );
  OAI21_X1 _176_ (
    .A(wr_en),
    .B1(_067_),
    .B2(_153_[2]),
    .ZN(_080_)
  );
  OAI211_X1 _177_ (
    .A(wr_ptr[0]),
    .B(wr_en),
    .C1(_067_),
    .C2(_153_[2]),
    .ZN(_081_)
  );
  XNOR2_X1 _178_ (
    .A(wr_ptr[1]),
    .B(_081_),
    .ZN(_056_)
  );
  MUX2_X1 _179_ (
    .A(_152_[0]),
    .B(rd_ptr[0]),
    .S(_068_),
    .Z(_048_)
  );
  MUX2_X1 _180_ (
    .A(_150_[0]),
    .B(wr_ptr[0]),
    .S(_080_),
    .Z(_047_)
  );
  AOI22_X1 _181_ (
    .A1(\memory[0] [0]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [0]),
    .ZN(_082_)
  );
  AOI22_X1 _182_ (
    .A1(\memory[1] [0]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [0]),
    .ZN(_083_)
  );
  NAND2_X1 _183_ (
    .A1(_082_),
    .A2(_083_),
    .ZN(_084_)
  );
  MUX2_X1 _184_ (
    .A(_084_),
    .B(data_out[0]),
    .S(_068_),
    .Z(_039_)
  );
  AOI22_X1 _185_ (
    .A1(\memory[0] [1]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [1]),
    .ZN(_085_)
  );
  AOI22_X1 _186_ (
    .A1(\memory[1] [1]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [1]),
    .ZN(_086_)
  );
  NAND2_X1 _187_ (
    .A1(_085_),
    .A2(_086_),
    .ZN(_087_)
  );
  MUX2_X1 _188_ (
    .A(_087_),
    .B(data_out[1]),
    .S(_068_),
    .Z(_038_)
  );
  AOI22_X1 _189_ (
    .A1(\memory[0] [2]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [2]),
    .ZN(_088_)
  );
  AOI22_X1 _190_ (
    .A1(\memory[1] [2]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [2]),
    .ZN(_089_)
  );
  NAND2_X1 _191_ (
    .A1(_088_),
    .A2(_089_),
    .ZN(_090_)
  );
  MUX2_X1 _192_ (
    .A(_090_),
    .B(data_out[2]),
    .S(_068_),
    .Z(_037_)
  );
  AOI22_X1 _193_ (
    .A1(\memory[0] [3]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [3]),
    .ZN(_091_)
  );
  AOI22_X1 _194_ (
    .A1(\memory[1] [3]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [3]),
    .ZN(_092_)
  );
  NAND2_X1 _195_ (
    .A1(_091_),
    .A2(_092_),
    .ZN(_093_)
  );
  MUX2_X1 _196_ (
    .A(_093_),
    .B(data_out[3]),
    .S(_068_),
    .Z(_036_)
  );
  AOI22_X1 _197_ (
    .A1(\memory[0] [4]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [4]),
    .ZN(_094_)
  );
  AOI22_X1 _198_ (
    .A1(\memory[1] [4]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [4]),
    .ZN(_095_)
  );
  NAND2_X1 _199_ (
    .A1(_094_),
    .A2(_095_),
    .ZN(_096_)
  );
  MUX2_X1 _200_ (
    .A(_096_),
    .B(data_out[4]),
    .S(_068_),
    .Z(_035_)
  );
  AOI22_X1 _201_ (
    .A1(\memory[0] [5]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [5]),
    .ZN(_097_)
  );
  AOI22_X1 _202_ (
    .A1(\memory[1] [5]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [5]),
    .ZN(_098_)
  );
  NAND2_X1 _203_ (
    .A1(_097_),
    .A2(_098_),
    .ZN(_099_)
  );
  MUX2_X1 _204_ (
    .A(_099_),
    .B(data_out[5]),
    .S(_068_),
    .Z(_034_)
  );
  AOI22_X1 _205_ (
    .A1(\memory[0] [6]),
    .A2(_072_),
    .B1(_074_),
    .B2(\memory[3] [6]),
    .ZN(_100_)
  );
  AOI22_X1 _206_ (
    .A1(\memory[1] [6]),
    .A2(_073_),
    .B1(_075_),
    .B2(\memory[2] [6]),
    .ZN(_101_)
  );
  NAND2_X1 _207_ (
    .A1(_100_),
    .A2(_101_),
    .ZN(_102_)
  );
  MUX2_X1 _208_ (
    .A(_102_),
    .B(data_out[6]),
    .S(_068_),
    .Z(_033_)
  );
  NAND2_X1 _209_ (
    .A1(_068_),
    .A2(_080_),
    .ZN(_103_)
  );
  MUX2_X1 _210_ (
    .A(count[0]),
    .B(_151_[0]),
    .S(_103_),
    .Z(_018_)
  );
  XNOR2_X1 _211_ (
    .A(count[0]),
    .B(_153_[1]),
    .ZN(_104_)
  );
  NAND4_X1 _212_ (
    .A1(wr_en),
    .A2(_065_),
    .A3(_067_),
    .A4(_068_),
    .ZN(_105_)
  );
  OAI221_X1 _213_ (
    .A(_105_),
    .B1(_104_),
    .B2(_068_),
    .C1(_064_),
    .C2(_103_),
    .ZN(_017_)
  );
  NOR4_X1 _214_ (
    .A1(wr_ptr[1]),
    .A2(_150_[0]),
    .A3(rst),
    .A4(_080_),
    .ZN(_106_)
  );
  MUX2_X1 _215_ (
    .A(\memory[1] [6]),
    .B(data_in[6]),
    .S(_106_),
    .Z(_019_)
  );
  MUX2_X1 _216_ (
    .A(\memory[1] [5]),
    .B(data_in[5]),
    .S(_106_),
    .Z(_020_)
  );
  MUX2_X1 _217_ (
    .A(\memory[1] [4]),
    .B(data_in[4]),
    .S(_106_),
    .Z(_021_)
  );
  MUX2_X1 _218_ (
    .A(\memory[1] [3]),
    .B(data_in[3]),
    .S(_106_),
    .Z(_022_)
  );
  MUX2_X1 _219_ (
    .A(\memory[1] [2]),
    .B(data_in[2]),
    .S(_106_),
    .Z(_023_)
  );
  MUX2_X1 _220_ (
    .A(\memory[1] [1]),
    .B(data_in[1]),
    .S(_106_),
    .Z(_024_)
  );
  MUX2_X1 _221_ (
    .A(\memory[1] [0]),
    .B(data_in[0]),
    .S(_106_),
    .Z(_025_)
  );
  NOR4_X1 _222_ (
    .A1(wr_ptr[0]),
    .A2(_001_),
    .A3(rst),
    .A4(_080_),
    .ZN(_107_)
  );
  MUX2_X1 _223_ (
    .A(\memory[2] [6]),
    .B(data_in[6]),
    .S(_107_),
    .Z(_026_)
  );
  MUX2_X1 _224_ (
    .A(\memory[2] [5]),
    .B(data_in[5]),
    .S(_107_),
    .Z(_027_)
  );
  MUX2_X1 _225_ (
    .A(\memory[2] [4]),
    .B(data_in[4]),
    .S(_107_),
    .Z(_028_)
  );
  MUX2_X1 _226_ (
    .A(\memory[2] [3]),
    .B(data_in[3]),
    .S(_107_),
    .Z(_029_)
  );
  MUX2_X1 _227_ (
    .A(\memory[2] [2]),
    .B(data_in[2]),
    .S(_107_),
    .Z(_030_)
  );
  MUX2_X1 _228_ (
    .A(\memory[2] [1]),
    .B(data_in[1]),
    .S(_107_),
    .Z(_031_)
  );
  MUX2_X1 _229_ (
    .A(\memory[2] [0]),
    .B(data_in[0]),
    .S(_107_),
    .Z(_032_)
  );
  OR4_X1 _230_ (
    .A1(wr_ptr[1]),
    .A2(wr_ptr[0]),
    .A3(rst),
    .A4(_080_),
    .ZN(_108_)
  );
  MUX2_X1 _231_ (
    .A(data_in[6]),
    .B(\memory[0] [6]),
    .S(_108_),
    .Z(_040_)
  );
  MUX2_X1 _232_ (
    .A(data_in[5]),
    .B(\memory[0] [5]),
    .S(_108_),
    .Z(_041_)
  );
  MUX2_X1 _233_ (
    .A(data_in[4]),
    .B(\memory[0] [4]),
    .S(_108_),
    .Z(_042_)
  );
  MUX2_X1 _234_ (
    .A(data_in[3]),
    .B(\memory[0] [3]),
    .S(_108_),
    .Z(_043_)
  );
  MUX2_X1 _235_ (
    .A(data_in[2]),
    .B(\memory[0] [2]),
    .S(_108_),
    .Z(_044_)
  );
  MUX2_X1 _236_ (
    .A(data_in[1]),
    .B(\memory[0] [1]),
    .S(_108_),
    .Z(_045_)
  );
  MUX2_X1 _237_ (
    .A(data_in[0]),
    .B(\memory[0] [0]),
    .S(_108_),
    .Z(_046_)
  );
  NOR4_X1 _238_ (
    .A1(_150_[0]),
    .A2(_001_),
    .A3(rst),
    .A4(_080_),
    .ZN(_109_)
  );
  MUX2_X1 _239_ (
    .A(\memory[3] [6]),
    .B(data_in[6]),
    .S(_109_),
    .Z(_049_)
  );
  MUX2_X1 _240_ (
    .A(\memory[3] [5]),
    .B(data_in[5]),
    .S(_109_),
    .Z(_050_)
  );
  MUX2_X1 _241_ (
    .A(\memory[3] [4]),
    .B(data_in[4]),
    .S(_109_),
    .Z(_051_)
  );
  MUX2_X1 _242_ (
    .A(\memory[3] [3]),
    .B(data_in[3]),
    .S(_109_),
    .Z(_052_)
  );
  MUX2_X1 _243_ (
    .A(\memory[3] [2]),
    .B(data_in[2]),
    .S(_109_),
    .Z(_053_)
  );
  MUX2_X1 _244_ (
    .A(\memory[3] [1]),
    .B(data_in[1]),
    .S(_109_),
    .Z(_054_)
  );
  MUX2_X1 _245_ (
    .A(\memory[3] [0]),
    .B(data_in[0]),
    .S(_109_),
    .Z(_055_)
  );
  MUX2_X1 _246_ (
    .A(\memory[3] [7]),
    .B(data_in[7]),
    .S(_109_),
    .Z(_058_)
  );
  MUX2_X1 _247_ (
    .A(\memory[2] [7]),
    .B(data_in[7]),
    .S(_107_),
    .Z(_059_)
  );
  MUX2_X1 _248_ (
    .A(\memory[1] [7]),
    .B(data_in[7]),
    .S(_106_),
    .Z(_060_)
  );
  MUX2_X1 _249_ (
    .A(data_in[7]),
    .B(\memory[0] [7]),
    .S(_108_),
    .Z(_062_)
  );
  INV_X1 _250_ (
    .A(rst),
    .ZN(_003_)
  );
  INV_X1 _251_ (
    .A(rst),
    .ZN(_004_)
  );
  INV_X1 _252_ (
    .A(rst),
    .ZN(_005_)
  );
  INV_X1 _253_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _254_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _255_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _256_ (
    .A(rst),
    .ZN(_009_)
  );
  INV_X1 _257_ (
    .A(rst),
    .ZN(_010_)
  );
  INV_X1 _258_ (
    .A(rst),
    .ZN(_011_)
  );
  INV_X1 _259_ (
    .A(rst),
    .ZN(_012_)
  );
  INV_X1 _260_ (
    .A(rst),
    .ZN(_013_)
  );
  INV_X1 _261_ (
    .A(rst),
    .ZN(_014_)
  );
  INV_X1 _262_ (
    .A(rst),
    .ZN(_015_)
  );
  INV_X1 _263_ (
    .A(rst),
    .ZN(_016_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _264_ (
    .CK(clk),
    .D(_055_),
    .Q(\memory[3] [0]),
    .QN(_115_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _265_ (
    .CK(clk),
    .D(_054_),
    .Q(\memory[3] [1]),
    .QN(_116_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _266_ (
    .CK(clk),
    .D(_053_),
    .Q(\memory[3] [2]),
    .QN(_117_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _267_ (
    .CK(clk),
    .D(_052_),
    .Q(\memory[3] [3]),
    .QN(_118_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _268_ (
    .CK(clk),
    .D(_051_),
    .Q(\memory[3] [4]),
    .QN(_119_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _269_ (
    .CK(clk),
    .D(_050_),
    .Q(\memory[3] [5]),
    .QN(_120_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _270_ (
    .CK(clk),
    .D(_049_),
    .Q(\memory[3] [6]),
    .QN(_121_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _271_ (
    .CK(clk),
    .D(_058_),
    .Q(\memory[3] [7]),
    .QN(_114_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _272_ (
    .CK(clk),
    .D(_048_),
    .Q(rd_ptr[0]),
    .QN(_152_[0]),
    .RN(_012_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _273_ (
    .CK(clk),
    .D(_057_),
    .Q(rd_ptr[1]),
    .QN(_000_),
    .RN(_014_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _274_ (
    .CK(clk),
    .D(_047_),
    .Q(wr_ptr[0]),
    .QN(_150_[0]),
    .RN(_011_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _275_ (
    .CK(clk),
    .D(_056_),
    .Q(wr_ptr[1]),
    .QN(_001_),
    .RN(_013_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _276_ (
    .CK(clk),
    .D(_046_),
    .Q(\memory[0] [0]),
    .QN(_122_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _277_ (
    .CK(clk),
    .D(_045_),
    .Q(\memory[0] [1]),
    .QN(_123_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _278_ (
    .CK(clk),
    .D(_044_),
    .Q(\memory[0] [2]),
    .QN(_124_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _279_ (
    .CK(clk),
    .D(_043_),
    .Q(\memory[0] [3]),
    .QN(_125_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _280_ (
    .CK(clk),
    .D(_042_),
    .Q(\memory[0] [4]),
    .QN(_126_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _281_ (
    .CK(clk),
    .D(_041_),
    .Q(\memory[0] [5]),
    .QN(_127_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _282_ (
    .CK(clk),
    .D(_040_),
    .Q(\memory[0] [6]),
    .QN(_128_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _283_ (
    .CK(clk),
    .D(_062_),
    .Q(\memory[0] [7]),
    .QN(_110_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _284_ (
    .CK(clk),
    .D(_039_),
    .Q(data_out[0]),
    .QN(_129_),
    .RN(_010_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _285_ (
    .CK(clk),
    .D(_038_),
    .Q(data_out[1]),
    .QN(_130_),
    .RN(_009_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _286_ (
    .CK(clk),
    .D(_037_),
    .Q(data_out[2]),
    .QN(_131_),
    .RN(_008_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _287_ (
    .CK(clk),
    .D(_036_),
    .Q(data_out[3]),
    .QN(_132_),
    .RN(_007_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _288_ (
    .CK(clk),
    .D(_035_),
    .Q(data_out[4]),
    .QN(_133_),
    .RN(_006_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _289_ (
    .CK(clk),
    .D(_034_),
    .Q(data_out[5]),
    .QN(_134_),
    .RN(_005_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _290_ (
    .CK(clk),
    .D(_033_),
    .Q(data_out[6]),
    .QN(_135_),
    .RN(_004_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _291_ (
    .CK(clk),
    .D(_061_),
    .Q(data_out[7]),
    .QN(_111_),
    .RN(_015_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _292_ (
    .CK(clk),
    .D(_032_),
    .Q(\memory[2] [0]),
    .QN(_136_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _293_ (
    .CK(clk),
    .D(_031_),
    .Q(\memory[2] [1]),
    .QN(_137_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _294_ (
    .CK(clk),
    .D(_030_),
    .Q(\memory[2] [2]),
    .QN(_138_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _295_ (
    .CK(clk),
    .D(_029_),
    .Q(\memory[2] [3]),
    .QN(_139_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _296_ (
    .CK(clk),
    .D(_028_),
    .Q(\memory[2] [4]),
    .QN(_140_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _297_ (
    .CK(clk),
    .D(_027_),
    .Q(\memory[2] [5]),
    .QN(_141_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _298_ (
    .CK(clk),
    .D(_026_),
    .Q(\memory[2] [6]),
    .QN(_142_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _299_ (
    .CK(clk),
    .D(_059_),
    .Q(\memory[2] [7]),
    .QN(_113_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _300_ (
    .CK(clk),
    .D(_025_),
    .Q(\memory[1] [0]),
    .QN(_143_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _301_ (
    .CK(clk),
    .D(_024_),
    .Q(\memory[1] [1]),
    .QN(_144_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _302_ (
    .CK(clk),
    .D(_023_),
    .Q(\memory[1] [2]),
    .QN(_145_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _303_ (
    .CK(clk),
    .D(_022_),
    .Q(\memory[1] [3]),
    .QN(_146_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _304_ (
    .CK(clk),
    .D(_021_),
    .Q(\memory[1] [4]),
    .QN(_147_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _305_ (
    .CK(clk),
    .D(_020_),
    .Q(\memory[1] [5]),
    .QN(_148_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _306_ (
    .CK(clk),
    .D(_019_),
    .Q(\memory[1] [6]),
    .QN(_149_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFF_X1 _307_ (
    .CK(clk),
    .D(_060_),
    .Q(\memory[1] [7]),
    .QN(_112_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _308_ (
    .CK(clk),
    .D(_018_),
    .Q(count[0]),
    .QN(_151_[0]),
    .RN(_003_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _309_ (
    .CK(clk),
    .D(_017_),
    .Q(count[1]),
    .QN(_153_[1]),
    .RN(_002_)
  );
  (* src = "rtl/fifo.v:18.1-39.4" *)
  DFFR_X1 _310_ (
    .CK(clk),
    .D(_063_),
    .Q(count[2]),
    .QN(_153_[2]),
    .RN(_016_)
  );
  assign _153_[0] = count[0];
  assign _150_[1] = wr_ptr[1];
  assign _151_[2:1] = count[2:1];
  assign _152_[1] = rd_ptr[1];
endmodule
