/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

(* top =  1  *)
(* src = "rtl/pwm_generator.v:1.1-32.10" *)
module pwm_generator(clk, rst, duty, pwm);
  (* src = "rtl/pwm_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "rtl/pwm_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "rtl/pwm_generator.v:5.17-5.21" *)
  input [7:0] duty;
  wire [7:0] duty;
  (* src = "rtl/pwm_generator.v:7.16-7.19" *)
  output pwm;
  wire pwm;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/pwm_generator.v:19.20-19.31|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _42_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/pwm_generator.v:19.20-19.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "8" *)
  wire [31:0] _43_;
  (* src = "rtl/pwm_generator.v:10.11-10.18" *)
  wire [7:0] counter;
  INV_X1 _44_ (
    .A(counter[6]),
    .ZN(_08_)
  );
  INV_X1 _45_ (
    .A(counter[4]),
    .ZN(_09_)
  );
  INV_X1 _46_ (
    .A(duty[1]),
    .ZN(_10_)
  );
  INV_X1 _47_ (
    .A(counter[2]),
    .ZN(_11_)
  );
  INV_X1 _48_ (
    .A(duty[3]),
    .ZN(_12_)
  );
  INV_X1 _49_ (
    .A(counter[7]),
    .ZN(_13_)
  );
  INV_X1 _50_ (
    .A(counter[5]),
    .ZN(_14_)
  );
  INV_X1 _51_ (
    .A(duty[2]),
    .ZN(_15_)
  );
  INV_X1 _52_ (
    .A(counter[3]),
    .ZN(_16_)
  );
  INV_X1 _53_ (
    .A(duty[0]),
    .ZN(_17_)
  );
  INV_X1 _54_ (
    .A(rst),
    .ZN(_00_)
  );
  NAND2_X1 _55_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .ZN(_18_)
  );
  NAND3_X1 _56_ (
    .A1(counter[0]),
    .A2(counter[1]),
    .A3(counter[2]),
    .ZN(_19_)
  );
  NOR2_X1 _57_ (
    .A1(_16_),
    .A2(_19_),
    .ZN(_20_)
  );
  NOR3_X1 _58_ (
    .A1(_09_),
    .A2(_16_),
    .A3(_19_),
    .ZN(_21_)
  );
  NAND2_X1 _59_ (
    .A1(counter[5]),
    .A2(_21_),
    .ZN(_22_)
  );
  NAND3_X1 _60_ (
    .A1(counter[6]),
    .A2(counter[5]),
    .A3(_21_),
    .ZN(_23_)
  );
  XNOR2_X1 _61_ (
    .A(counter[7]),
    .B(_23_),
    .ZN(_43_[7])
  );
  XNOR2_X1 _62_ (
    .A(counter[6]),
    .B(_22_),
    .ZN(_43_[6])
  );
  XNOR2_X1 _63_ (
    .A(_14_),
    .B(_21_),
    .ZN(_43_[5])
  );
  XNOR2_X1 _64_ (
    .A(_09_),
    .B(_20_),
    .ZN(_43_[4])
  );
  XNOR2_X1 _65_ (
    .A(counter[3]),
    .B(_19_),
    .ZN(_43_[3])
  );
  XNOR2_X1 _66_ (
    .A(counter[2]),
    .B(_18_),
    .ZN(_43_[2])
  );
  XOR2_X1 _67_ (
    .A(counter[0]),
    .B(counter[1]),
    .Z(_43_[1])
  );
  NOR2_X1 _68_ (
    .A1(_13_),
    .A2(duty[7]),
    .ZN(_24_)
  );
  AOI211_X1 _69_ (
    .A(counter[0]),
    .B(_17_),
    .C1(_10_),
    .C2(counter[1]),
    .ZN(_25_)
  );
  OAI22_X1 _70_ (
    .A1(_11_),
    .A2(duty[2]),
    .B1(counter[3]),
    .B2(_12_),
    .ZN(_26_)
  );
  OAI22_X1 _71_ (
    .A1(counter[1]),
    .A2(_10_),
    .B1(counter[2]),
    .B2(_15_),
    .ZN(_27_)
  );
  NOR3_X1 _72_ (
    .A1(_25_),
    .A2(_26_),
    .A3(_27_),
    .ZN(_28_)
  );
  OAI211_X1 _73_ (
    .A(counter[2]),
    .B(_15_),
    .C1(counter[3]),
    .C2(_12_),
    .ZN(_29_)
  );
  OAI221_X1 _74_ (
    .A(_29_),
    .B1(_16_),
    .B2(duty[3]),
    .C1(_09_),
    .C2(duty[4]),
    .ZN(_30_)
  );
  AOI22_X1 _75_ (
    .A1(_09_),
    .A2(duty[4]),
    .B1(_14_),
    .B2(duty[5]),
    .ZN(_31_)
  );
  OAI21_X1 _76_ (
    .A(_31_),
    .B1(_30_),
    .B2(_28_),
    .ZN(_32_)
  );
  OAI221_X1 _77_ (
    .A(_32_),
    .B1(_14_),
    .B2(duty[5]),
    .C1(_08_),
    .C2(duty[6]),
    .ZN(_33_)
  );
  AOI22_X1 _78_ (
    .A1(_08_),
    .A2(duty[6]),
    .B1(duty[7]),
    .B2(_13_),
    .ZN(_34_)
  );
  AOI21_X1 _79_ (
    .A(_24_),
    .B1(_33_),
    .B2(_34_),
    .ZN(pwm)
  );
  INV_X1 _80_ (
    .A(rst),
    .ZN(_01_)
  );
  INV_X1 _81_ (
    .A(rst),
    .ZN(_02_)
  );
  INV_X1 _82_ (
    .A(rst),
    .ZN(_03_)
  );
  INV_X1 _83_ (
    .A(rst),
    .ZN(_04_)
  );
  INV_X1 _84_ (
    .A(rst),
    .ZN(_05_)
  );
  INV_X1 _85_ (
    .A(rst),
    .ZN(_06_)
  );
  INV_X1 _86_ (
    .A(rst),
    .ZN(_07_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _87_ (
    .CK(clk),
    .D(_42_[0]),
    .Q(counter[0]),
    .QN(_42_[0]),
    .RN(_06_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _88_ (
    .CK(clk),
    .D(_43_[1]),
    .Q(counter[1]),
    .QN(_36_),
    .RN(_05_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _89_ (
    .CK(clk),
    .D(_43_[2]),
    .Q(counter[2]),
    .QN(_37_),
    .RN(_04_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _90_ (
    .CK(clk),
    .D(_43_[3]),
    .Q(counter[3]),
    .QN(_38_),
    .RN(_03_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _91_ (
    .CK(clk),
    .D(_43_[4]),
    .Q(counter[4]),
    .QN(_39_),
    .RN(_02_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _92_ (
    .CK(clk),
    .D(_43_[5]),
    .Q(counter[5]),
    .QN(_40_),
    .RN(_01_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _93_ (
    .CK(clk),
    .D(_43_[6]),
    .Q(counter[6]),
    .QN(_41_),
    .RN(_00_)
  );
  (* src = "rtl/pwm_generator.v:12.1-21.4" *)
  DFFR_X1 _94_ (
    .CK(clk),
    .D(_43_[7]),
    .Q(counter[7]),
    .QN(_35_),
    .RN(_07_)
  );
  assign _42_[31:1] = { 24'h000000, counter[7:1] };
  assign { _43_[31:9], _43_[0] } = { 23'h000000, _42_[0] };
endmodule
