/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

(* top =  1  *)
(* src = "rtl/timer.v:1.1-37.10" *)
module timer(clk, rst, enable, period, timeout);
  (* src = "rtl/timer.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "rtl/timer.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "rtl/timer.v:4.11-4.17" *)
  input enable;
  wire enable;
  (* src = "rtl/timer.v:5.17-5.23" *)
  input [7:0] period;
  wire [7:0] period;
  (* src = "rtl/timer.v:7.16-7.23" *)
  output timeout;
  wire timeout;
  (* src = "rtl/timer.v:12.1-35.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/timer.v:27.24-27.38|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _051_;
  (* src = "rtl/timer.v:10.11-10.18" *)
  wire [7:0] counter;
  INV_X1 _052_ (
    .A(enable),
    .ZN(_018_)
  );
  INV_X1 _053_ (
    .A(counter[0]),
    .ZN(_019_)
  );
  INV_X1 _054_ (
    .A(rst),
    .ZN(_001_)
  );
  AND4_X1 _055_ (
    .A1(enable),
    .A2(counter[0]),
    .A3(counter[1]),
    .A4(counter[2]),
    .ZN(_020_)
  );
  AND3_X1 _056_ (
    .A1(counter[3]),
    .A2(counter[4]),
    .A3(_020_),
    .ZN(_021_)
  );
  AND4_X1 _057_ (
    .A1(counter[3]),
    .A2(counter[4]),
    .A3(counter[5]),
    .A4(_020_),
    .ZN(_022_)
  );
  AND3_X1 _058_ (
    .A1(counter[7]),
    .A2(counter[6]),
    .A3(_022_),
    .ZN(_023_)
  );
  XNOR2_X1 _059_ (
    .A(counter[1]),
    .B(period[1]),
    .ZN(_024_)
  );
  XNOR2_X1 _060_ (
    .A(counter[6]),
    .B(period[6]),
    .ZN(_025_)
  );
  XNOR2_X1 _061_ (
    .A(counter[3]),
    .B(period[3]),
    .ZN(_026_)
  );
  XNOR2_X1 _062_ (
    .A(counter[0]),
    .B(period[0]),
    .ZN(_027_)
  );
  NAND4_X1 _063_ (
    .A1(_024_),
    .A2(_025_),
    .A3(_026_),
    .A4(_027_),
    .ZN(_028_)
  );
  XNOR2_X1 _064_ (
    .A(counter[7]),
    .B(period[7]),
    .ZN(_029_)
  );
  XNOR2_X1 _065_ (
    .A(counter[5]),
    .B(period[5]),
    .ZN(_030_)
  );
  XNOR2_X1 _066_ (
    .A(counter[4]),
    .B(period[4]),
    .ZN(_031_)
  );
  XNOR2_X1 _067_ (
    .A(counter[2]),
    .B(period[2]),
    .ZN(_032_)
  );
  NAND4_X1 _068_ (
    .A1(_029_),
    .A2(_030_),
    .A3(_031_),
    .A4(_032_),
    .ZN(_033_)
  );
  NOR3_X1 _069_ (
    .A1(_018_),
    .A2(_028_),
    .A3(_033_),
    .ZN(_000_)
  );
  AOI21_X1 _070_ (
    .A(counter[7]),
    .B1(counter[6]),
    .B2(_022_),
    .ZN(_034_)
  );
  NOR3_X1 _071_ (
    .A1(_023_),
    .A2(_000_),
    .A3(_034_),
    .ZN(_017_)
  );
  OAI211_X1 _072_ (
    .A(enable),
    .B(_051_[0]),
    .C1(_028_),
    .C2(_033_),
    .ZN(_035_)
  );
  OAI21_X1 _073_ (
    .A(_035_),
    .B1(_019_),
    .B2(enable),
    .ZN(_016_)
  );
  AOI21_X1 _074_ (
    .A(counter[1]),
    .B1(counter[0]),
    .B2(enable),
    .ZN(_036_)
  );
  AND3_X1 _075_ (
    .A1(enable),
    .A2(counter[0]),
    .A3(counter[1]),
    .ZN(_037_)
  );
  NOR3_X1 _076_ (
    .A1(_000_),
    .A2(_036_),
    .A3(_037_),
    .ZN(_015_)
  );
  NOR2_X1 _077_ (
    .A1(counter[2]),
    .A2(_037_),
    .ZN(_038_)
  );
  NOR3_X1 _078_ (
    .A1(_020_),
    .A2(_000_),
    .A3(_038_),
    .ZN(_014_)
  );
  XNOR2_X1 _079_ (
    .A(counter[3]),
    .B(_020_),
    .ZN(_039_)
  );
  NOR2_X1 _080_ (
    .A1(_000_),
    .A2(_039_),
    .ZN(_013_)
  );
  AOI21_X1 _081_ (
    .A(counter[4]),
    .B1(_020_),
    .B2(counter[3]),
    .ZN(_040_)
  );
  NOR3_X1 _082_ (
    .A1(_021_),
    .A2(_000_),
    .A3(_040_),
    .ZN(_012_)
  );
  NOR2_X1 _083_ (
    .A1(counter[5]),
    .A2(_021_),
    .ZN(_041_)
  );
  NOR3_X1 _084_ (
    .A1(_022_),
    .A2(_000_),
    .A3(_041_),
    .ZN(_011_)
  );
  XNOR2_X1 _085_ (
    .A(counter[6]),
    .B(_022_),
    .ZN(_042_)
  );
  NOR2_X1 _086_ (
    .A1(_000_),
    .A2(_042_),
    .ZN(_010_)
  );
  INV_X1 _087_ (
    .A(rst),
    .ZN(_002_)
  );
  INV_X1 _088_ (
    .A(rst),
    .ZN(_003_)
  );
  INV_X1 _089_ (
    .A(rst),
    .ZN(_004_)
  );
  INV_X1 _090_ (
    .A(rst),
    .ZN(_005_)
  );
  INV_X1 _091_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _092_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _093_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _094_ (
    .A(rst),
    .ZN(_009_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _095_ (
    .CK(clk),
    .D(_010_),
    .Q(counter[6]),
    .QN(_050_),
    .RN(_001_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _096_ (
    .CK(clk),
    .D(_017_),
    .Q(counter[7]),
    .QN(_044_),
    .RN(_008_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _097_ (
    .CK(clk),
    .D(_000_),
    .Q(timeout),
    .QN(_043_),
    .RN(_009_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _098_ (
    .CK(clk),
    .D(_016_),
    .Q(counter[0]),
    .QN(_051_[0]),
    .RN(_007_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _099_ (
    .CK(clk),
    .D(_015_),
    .Q(counter[1]),
    .QN(_045_),
    .RN(_006_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _100_ (
    .CK(clk),
    .D(_014_),
    .Q(counter[2]),
    .QN(_046_),
    .RN(_005_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _101_ (
    .CK(clk),
    .D(_013_),
    .Q(counter[3]),
    .QN(_047_),
    .RN(_004_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _102_ (
    .CK(clk),
    .D(_012_),
    .Q(counter[4]),
    .QN(_048_),
    .RN(_003_)
  );
  (* src = "rtl/timer.v:12.1-35.4" *)
  DFFR_X1 _103_ (
    .CK(clk),
    .D(_011_),
    .Q(counter[5]),
    .QN(_049_),
    .RN(_002_)
  );
  assign _051_[7:1] = counter[7:1];
endmodule
