create_clock -name clk -period 10.0 [get_ports clk]

set_input_delay 1.0 -clock clk [get_ports rst]
set_input_delay 1.0 -clock clk [get_ports cpu_read]
set_input_delay 1.0 -clock clk [get_ports cpu_write]
set_input_delay 1.0 -clock clk [get_ports cpu_address]
set_input_delay 1.0 -clock clk [get_ports cpu_write_data]
set_input_delay 1.0 -clock clk [get_ports memory_read_data]
set_input_delay 1.0 -clock clk [get_ports memory_ready]

set_output_delay 1.0 -clock clk [get_ports cpu_read_data]
set_output_delay 1.0 -clock clk [get_ports cpu_ready]
set_output_delay 1.0 -clock clk [get_ports memory_read]
set_output_delay 1.0 -clock clk [get_ports memory_write]
set_output_delay 1.0 -clock clk [get_ports memory_address]
set_output_delay 1.0 -clock clk [get_ports memory_write_data]
