create_clock -name clk -period 10.0 [get_ports clk]

set_input_delay 1.0 -clock clk [get_ports rst]
set_input_delay 1.0 -clock clk [get_ports req_valid]
set_input_delay 1.0 -clock clk [get_ports req_write]
set_input_delay 1.0 -clock clk [get_ports req_addr]
set_input_delay 1.0 -clock clk [get_ports req_wdata]
set_input_delay 1.0 -clock clk [get_ports mem_rdata]
set_input_delay 1.0 -clock clk [get_ports mem_ready]

set_output_delay 1.0 -clock clk [get_ports req_ready]
set_output_delay 1.0 -clock clk [get_ports resp_valid]
set_output_delay 1.0 -clock clk [get_ports resp_hit]
set_output_delay 1.0 -clock clk [get_ports resp_rdata]
set_output_delay 1.0 -clock clk [get_ports mem_read]
set_output_delay 1.0 -clock clk [get_ports mem_addr]
set_output_delay 1.0 -clock clk [get_ports miss_pending]
set_output_delay 1.0 -clock clk [get_ports miss_addr_debug]
set_output_delay 1.0 -clock clk [get_ports miss_write_debug]
