/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/local/bin/wrapped-cc/g++ 11.4.0) */

module interrupt_controller_top(clk, rst, irq, mask_write, mask_data, cpu_ack, cpu_interrupt, busy, interrupt_id);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] irq;
  wire [7:0] irq;
  input mask_write;
  wire mask_write;
  input [7:0] mask_data;
  wire [7:0] mask_data;
  input cpu_ack;
  wire cpu_ack;
  output cpu_interrupt;
  wire cpu_interrupt;
  output busy;
  wire busy;
  output [2:0] interrupt_id;
  wire [2:0] interrupt_id;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire clear_interrupt;
  wire \fsm.busy ;
  wire \fsm.clear_interrupt ;
  wire \fsm.clk ;
  wire \fsm.cpu_ack ;
  wire \fsm.cpu_interrupt ;
  wire \fsm.rst ;
  wire [1:0] \fsm.state ;
  wire \mask_reg.clk ;
  wire [7:0] \mask_reg.mask_data ;
  wire [7:0] \mask_reg.mask_register ;
  wire \mask_reg.mask_write ;
  wire \mask_reg.rst ;
  wire [7:0] mask_register;
  wire [7:0] pending_irq;
  wire [2:0] \priority_encoder.interrupt_id ;
  wire \request_reg.clk ;
  wire [7:0] \request_reg.irq ;
  wire [7:0] \request_reg.pending_irq ;
  wire \request_reg.rst ;
  INV_X1 _095_ (
    .A(\fsm.state [1]),
    .ZN(_013_)
  );
  INV_X1 _096_ (
    .A(\fsm.state [0]),
    .ZN(_014_)
  );
  NAND3_X1 _097_ (
    .A1(\fsm.state [1]),
    .A2(cpu_ack),
    .A3(_014_),
    .ZN(_015_)
  );
  NAND2_X1 _098_ (
    .A1(\request_reg.pending_irq [4]),
    .A2(\mask_reg.mask_register [4]),
    .ZN(_016_)
  );
  AND2_X1 _099_ (
    .A1(\request_reg.pending_irq [7]),
    .A2(\mask_reg.mask_register [7]),
    .ZN(_017_)
  );
  AOI22_X1 _100_ (
    .A1(\request_reg.pending_irq [6]),
    .A2(\mask_reg.mask_register [6]),
    .B1(\request_reg.pending_irq [7]),
    .B2(\mask_reg.mask_register [7]),
    .ZN(_018_)
  );
  AOI222_X1 _101_ (
    .A1(\request_reg.pending_irq [6]),
    .A2(\mask_reg.mask_register [6]),
    .B1(\request_reg.pending_irq [7]),
    .B2(\mask_reg.mask_register [7]),
    .C1(\mask_reg.mask_register [5]),
    .C2(\request_reg.pending_irq [5]),
    .ZN(_019_)
  );
  AND2_X1 _102_ (
    .A1(_016_),
    .A2(_019_),
    .ZN(_020_)
  );
  INV_X1 _103_ (
    .A(_020_),
    .ZN(interrupt_id[2])
  );
  AOI22_X1 _104_ (
    .A1(\request_reg.pending_irq [3]),
    .A2(\mask_reg.mask_register [3]),
    .B1(\mask_reg.mask_register [2]),
    .B2(\request_reg.pending_irq [2]),
    .ZN(_021_)
  );
  AND2_X1 _105_ (
    .A1(\request_reg.pending_irq [1]),
    .A2(\mask_reg.mask_register [1]),
    .ZN(_022_)
  );
  NAND2_X1 _106_ (
    .A1(\request_reg.pending_irq [1]),
    .A2(\mask_reg.mask_register [1]),
    .ZN(_023_)
  );
  AND4_X1 _107_ (
    .A1(\request_reg.pending_irq [3]),
    .A2(\mask_reg.mask_register [3]),
    .A3(_016_),
    .A4(_019_),
    .ZN(_024_)
  );
  AND4_X1 _108_ (
    .A1(_016_),
    .A2(_019_),
    .A3(_021_),
    .A4(_022_),
    .ZN(_025_)
  );
  AND4_X1 _109_ (
    .A1(_016_),
    .A2(_019_),
    .A3(_021_),
    .A4(_023_),
    .ZN(_026_)
  );
  AOI22_X1 _110_ (
    .A1(\request_reg.pending_irq [1]),
    .A2(\mask_reg.mask_register [1]),
    .B1(\mask_reg.mask_register [0]),
    .B2(\request_reg.pending_irq [0]),
    .ZN(_027_)
  );
  AND4_X1 _111_ (
    .A1(_016_),
    .A2(_019_),
    .A3(_021_),
    .A4(_027_),
    .ZN(_028_)
  );
  NOR2_X1 _112_ (
    .A1(\fsm.state [1]),
    .A2(\fsm.state [0]),
    .ZN(_029_)
  );
  NAND2_X1 _113_ (
    .A1(_013_),
    .A2(_014_),
    .ZN(_030_)
  );
  OAI21_X1 _114_ (
    .A(_015_),
    .B1(_028_),
    .B2(_030_),
    .ZN(_003_)
  );
  OAI21_X1 _115_ (
    .A(_018_),
    .B1(interrupt_id[2]),
    .B2(_021_),
    .ZN(interrupt_id[1])
  );
  NOR2_X1 _116_ (
    .A1(_013_),
    .A2(_014_),
    .ZN(_002_)
  );
  NAND3_X1 _117_ (
    .A1(\request_reg.pending_irq [6]),
    .A2(\mask_reg.mask_register [6]),
    .A3(\fsm.clear_interrupt ),
    .ZN(_031_)
  );
  OAI22_X1 _118_ (
    .A1(\request_reg.pending_irq [6]),
    .A2(irq[6]),
    .B1(_017_),
    .B2(_031_),
    .ZN(_032_)
  );
  INV_X1 _119_ (
    .A(_032_),
    .ZN(_011_)
  );
  NOR2_X1 _120_ (
    .A1(\request_reg.pending_irq [5]),
    .A2(irq[5]),
    .ZN(_033_)
  );
  AND3_X1 _121_ (
    .A1(\request_reg.pending_irq [5]),
    .A2(\mask_reg.mask_register [5]),
    .A3(_018_),
    .ZN(_034_)
  );
  AOI21_X1 _122_ (
    .A(_033_),
    .B1(_034_),
    .B2(\fsm.clear_interrupt ),
    .ZN(_010_)
  );
  NOR2_X1 _123_ (
    .A1(\request_reg.pending_irq [4]),
    .A2(irq[4]),
    .ZN(_035_)
  );
  AND3_X1 _124_ (
    .A1(\request_reg.pending_irq [4]),
    .A2(\mask_reg.mask_register [4]),
    .A3(\fsm.clear_interrupt ),
    .ZN(_036_)
  );
  AOI21_X1 _125_ (
    .A(_035_),
    .B1(_036_),
    .B2(_019_),
    .ZN(_009_)
  );
  NOR2_X1 _126_ (
    .A1(\request_reg.pending_irq [3]),
    .A2(irq[3]),
    .ZN(_037_)
  );
  AOI21_X1 _127_ (
    .A(_037_),
    .B1(_024_),
    .B2(\fsm.clear_interrupt ),
    .ZN(_008_)
  );
  NOR2_X1 _128_ (
    .A1(\request_reg.pending_irq [2]),
    .A2(irq[2]),
    .ZN(_038_)
  );
  NAND3_X1 _129_ (
    .A1(\request_reg.pending_irq [2]),
    .A2(\mask_reg.mask_register [2]),
    .A3(\fsm.clear_interrupt ),
    .ZN(_039_)
  );
  AOI21_X1 _130_ (
    .A(_039_),
    .B1(\mask_reg.mask_register [3]),
    .B2(\request_reg.pending_irq [3]),
    .ZN(_040_)
  );
  AOI21_X1 _131_ (
    .A(_038_),
    .B1(_040_),
    .B2(_020_),
    .ZN(_007_)
  );
  NOR2_X1 _132_ (
    .A1(\request_reg.pending_irq [1]),
    .A2(irq[1]),
    .ZN(_041_)
  );
  AOI21_X1 _133_ (
    .A(_041_),
    .B1(_025_),
    .B2(\fsm.clear_interrupt ),
    .ZN(_006_)
  );
  NOR2_X1 _134_ (
    .A1(\request_reg.pending_irq [0]),
    .A2(irq[0]),
    .ZN(_042_)
  );
  AOI21_X1 _135_ (
    .A(_042_),
    .B1(_026_),
    .B2(\fsm.clear_interrupt ),
    .ZN(_005_)
  );
  OR4_X1 _136_ (
    .A1(_017_),
    .A2(_024_),
    .A3(_025_),
    .A4(_034_),
    .ZN(interrupt_id[0])
  );
  XOR2_X1 _137_ (
    .A(\fsm.state [1]),
    .B(\fsm.state [0]),
    .Z(_001_)
  );
  NOR2_X1 _138_ (
    .A1(\request_reg.pending_irq [7]),
    .A2(irq[7]),
    .ZN(_043_)
  );
  AOI21_X1 _139_ (
    .A(_043_),
    .B1(_017_),
    .B2(\fsm.clear_interrupt ),
    .ZN(_012_)
  );
  OAI21_X1 _140_ (
    .A(_015_),
    .B1(_014_),
    .B2(\fsm.state [1]),
    .ZN(_004_)
  );
  NOR3_X1 _141_ (
    .A1(_013_),
    .A2(cpu_ack),
    .A3(\fsm.state [0]),
    .ZN(_044_)
  );
  AOI21_X1 _142_ (
    .A(_044_),
    .B1(_029_),
    .B2(_028_),
    .ZN(_000_)
  );
  assign _065_ = ~rst;
  assign _066_ = ~rst;
  assign _067_ = ~rst;
  assign _068_ = ~rst;
  assign _069_ = ~rst;
  assign _070_ = ~rst;
  assign _071_ = ~rst;
  assign _072_ = ~rst;
  assign _073_ = ~rst;
  assign _074_ = ~rst;
  assign _075_ = ~rst;
  assign _076_ = ~rst;
  assign _077_ = ~rst;
  assign _078_ = ~rst;
  assign _079_ = ~rst;
  assign _080_ = ~rst;
  assign _081_ = ~rst;
  assign _082_ = ~rst;
  assign _083_ = ~rst;
  assign _084_ = ~rst;
  DFFR_X1 _163_ (
    .CK(clk),
    .D(_094_),
    .Q(\fsm.state [0]),
    .QN(_048_),
    .RN(_081_)
  );
  DFFR_X1 _164_ (
    .CK(clk),
    .D(_092_),
    .Q(\fsm.state [1]),
    .QN(_053_),
    .RN(_076_)
  );
  DFFS_X1 _165_ (
    .CK(clk),
    .D(_093_),
    .Q(\mask_reg.mask_register [0]),
    .QN(_050_),
    .SN(_079_)
  );
  DFFS_X1 _166_ (
    .CK(clk),
    .D(_090_),
    .Q(\mask_reg.mask_register [1]),
    .QN(_055_),
    .SN(_074_)
  );
  DFFS_X1 _167_ (
    .CK(clk),
    .D(_089_),
    .Q(\mask_reg.mask_register [2]),
    .QN(_056_),
    .SN(_073_)
  );
  DFFS_X1 _168_ (
    .CK(clk),
    .D(_088_),
    .Q(\mask_reg.mask_register [3]),
    .QN(_057_),
    .SN(_072_)
  );
  DFFS_X1 _169_ (
    .CK(clk),
    .D(_087_),
    .Q(\mask_reg.mask_register [4]),
    .QN(_058_),
    .SN(_071_)
  );
  DFFS_X1 _170_ (
    .CK(clk),
    .D(_086_),
    .Q(\mask_reg.mask_register [5]),
    .QN(_059_),
    .SN(_070_)
  );
  DFFS_X1 _171_ (
    .CK(clk),
    .D(_085_),
    .Q(\mask_reg.mask_register [6]),
    .QN(_060_),
    .SN(_069_)
  );
  DFFS_X1 _172_ (
    .CK(clk),
    .D(_091_),
    .Q(\mask_reg.mask_register [7]),
    .QN(_054_),
    .SN(_075_)
  );
  DFFR_X1 _173_ (
    .CK(clk),
    .D(_005_),
    .Q(\request_reg.pending_irq [0]),
    .QN(_045_),
    .RN(_084_)
  );
  DFFR_X1 _174_ (
    .CK(clk),
    .D(_006_),
    .Q(\request_reg.pending_irq [1]),
    .QN(_046_),
    .RN(_083_)
  );
  DFFR_X1 _175_ (
    .CK(clk),
    .D(_007_),
    .Q(\request_reg.pending_irq [2]),
    .QN(_047_),
    .RN(_082_)
  );
  DFFR_X1 _176_ (
    .CK(clk),
    .D(_008_),
    .Q(\request_reg.pending_irq [3]),
    .QN(_061_),
    .RN(_068_)
  );
  DFFR_X1 _177_ (
    .CK(clk),
    .D(_009_),
    .Q(\request_reg.pending_irq [4]),
    .QN(_062_),
    .RN(_067_)
  );
  DFFR_X1 _178_ (
    .CK(clk),
    .D(_010_),
    .Q(\request_reg.pending_irq [5]),
    .QN(_063_),
    .RN(_066_)
  );
  DFFR_X1 _179_ (
    .CK(clk),
    .D(_011_),
    .Q(\request_reg.pending_irq [6]),
    .QN(_064_),
    .RN(_065_)
  );
  DFFR_X1 _180_ (
    .CK(clk),
    .D(_012_),
    .Q(\request_reg.pending_irq [7]),
    .QN(_051_),
    .RN(_078_)
  );
  DFFR_X1 _181_ (
    .CK(clk),
    .D(_002_),
    .Q(\fsm.clear_interrupt ),
    .QN(_049_),
    .RN(_080_)
  );
  DFFR_X1 _182_ (
    .CK(clk),
    .D(_001_),
    .Q(\fsm.cpu_interrupt ),
    .QN(_052_),
    .RN(_077_)
  );
  assign _085_ = mask_write ? mask_data[6] : \mask_reg.mask_register [6];
  assign _086_ = mask_write ? mask_data[5] : \mask_reg.mask_register [5];
  assign _087_ = mask_write ? mask_data[4] : \mask_reg.mask_register [4];
  assign _088_ = mask_write ? mask_data[3] : \mask_reg.mask_register [3];
  assign _089_ = mask_write ? mask_data[2] : \mask_reg.mask_register [2];
  assign _090_ = mask_write ? mask_data[1] : \mask_reg.mask_register [1];
  assign _091_ = mask_write ? mask_data[7] : \mask_reg.mask_register [7];
  assign _092_ = _000_ ? _004_ : \fsm.state [1];
  assign _093_ = mask_write ? mask_data[0] : \mask_reg.mask_register [0];
  assign _094_ = _000_ ? _003_ : \fsm.state [0];
  assign \priority_encoder.interrupt_id  = interrupt_id;
  assign \fsm.busy  = \fsm.cpu_interrupt ;
  assign \fsm.cpu_ack  = cpu_ack;
  assign \fsm.rst  = rst;
  assign \fsm.clk  = clk;
  assign \mask_reg.clk  = clk;
  assign \mask_reg.rst  = rst;
  assign \mask_reg.mask_write  = mask_write;
  assign \mask_reg.mask_data  = mask_data;
  assign \request_reg.clk  = clk;
  assign \request_reg.rst  = rst;
  assign \request_reg.irq  = irq;
  assign clear_interrupt = \fsm.clear_interrupt ;
  assign mask_register = \mask_reg.mask_register ;
  assign pending_irq = \request_reg.pending_irq ;
  assign busy = \fsm.cpu_interrupt ;
  assign cpu_interrupt = \fsm.cpu_interrupt ;
endmodule
