/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\spi_shift_register" *)
(* src = "RTL/spi_shift_register.v:1.1-41.10" *)
module \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, rst, load, shift, data_in, miso, rx_data, mosi, shift_reg);
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  wire [7:0] _00_;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  wire [7:0] _01_;
  wire _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  (* src = "RTL/spi_shift_register.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_shift_register.v:8.28-8.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/spi_shift_register.v:6.11-6.15" *)
  input load;
  wire load;
  (* src = "RTL/spi_shift_register.v:9.11-9.15" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_shift_register.v:12.12-12.16" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_shift_register.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_shift_register.v:11.33-11.40" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_shift_register.v:7.11-7.16" *)
  input shift;
  wire shift;
  (* src = "RTL/spi_shift_register.v:13.33-13.42" *)
  output [7:0] shift_reg;
  reg [7:0] shift_reg;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_02_) rx_data <= _00_;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_reg <= 8'h00;
    else if (_02_) shift_reg <= _01_;
  assign _02_ = | { shift, load };
  assign _03_ = shift ? (* src = "RTL/spi_shift_register.v:34.13-34.18|RTL/spi_shift_register.v:34.10-38.8" *) { shift_reg[6:0], 1'h0 } : 8'hxx;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:28.13-28.17|RTL/spi_shift_register.v:28.10-38.8" *) data_in : _03_;
  assign _04_ = shift ? (* src = "RTL/spi_shift_register.v:34.13-34.18|RTL/spi_shift_register.v:34.10-38.8" *) { rx_data[6:0], miso } : 8'hxx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:28.13-28.17|RTL/spi_shift_register.v:28.10-38.8" *) 8'h00 : _04_;
  assign mosi = shift_reg[7];
endmodule

(* src = "RTL/spi_bit_counter.v:1.1-23.10" *)
module spi_bit_counter(clk, rst, enable, bit_count, done);
  (* src = "RTL/spi_bit_counter.v:19.26-19.42" *)
  wire [2:0] _0_;
  wire [2:0] _1_;
  (* src = "RTL/spi_bit_counter.v:5.22-5.31" *)
  output [2:0] bit_count;
  reg [2:0] bit_count;
  (* src = "RTL/spi_bit_counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_bit_counter.v:6.12-6.16" *)
  output done;
  wire done;
  (* src = "RTL/spi_bit_counter.v:4.11-4.17" *)
  input enable;
  wire enable;
  (* src = "RTL/spi_bit_counter.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _0_ = bit_count + (* src = "RTL/spi_bit_counter.v:19.26-19.42" *) 1'h1;
  (* src = "RTL/spi_bit_counter.v:11.1-21.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 3'h0;
    else if (enable) bit_count <= _1_;
  assign done = bit_count == (* src = "RTL/spi_bit_counter.v:16.13-16.30" *) 3'h7;
  assign _1_ = done ? (* full_case = 32'd1 *) (* src = "RTL/spi_bit_counter.v:16.13-16.30|RTL/spi_bit_counter.v:16.9-19.43" *) 3'h0 : _0_;
endmodule

(* src = "RTL/spi_clock_generator.v:1.1-35.10" *)
module spi_clock_generator(clk, rst, clk_divider, cpol, spi_clk);
  (* src = "RTL/spi_clock_generator.v:14.1-34.4" *)
  wire [7:0] _0_;
  (* src = "RTL/spi_clock_generator.v:26.22-26.35" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _1_;
  (* src = "RTL/spi_clock_generator.v:28.12-28.36" *)
  wire _2_;
  (* src = "RTL/spi_clock_generator.v:31.20-31.28" *)
  wire _3_;
  (* src = "RTL/spi_clock_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_clock_generator.v:12.11-12.20" *)
  reg [7:0] clk_count;
  (* src = "RTL/spi_clock_generator.v:5.17-5.28" *)
  input [7:0] clk_divider;
  wire [7:0] clk_divider;
  (* src = "RTL/spi_clock_generator.v:6.11-6.15" *)
  input cpol;
  wire cpol;
  (* src = "RTL/spi_clock_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_clock_generator.v:8.16-8.23" *)
  output spi_clk;
  reg spi_clk;
  assign _1_ = clk_count + (* src = "RTL/spi_clock_generator.v:26.22-26.35" *) 32'd1;
  (* src = "RTL/spi_clock_generator.v:14.1-34.4" *)
  always @(posedge clk, posedge rst)
    if (rst) spi_clk <= 1'h0;
    else if (_2_) spi_clk <= _3_;
  assign _2_ = clk_count >= (* src = "RTL/spi_clock_generator.v:28.12-28.36" *) clk_divider;
  assign _3_ = ~ (* src = "RTL/spi_clock_generator.v:31.20-31.28" *) spi_clk;
  (* src = "RTL/spi_clock_generator.v:14.1-34.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count <= 8'h00;
    else clk_count <= _0_;
  assign _0_ = _2_ ? (* src = "RTL/spi_clock_generator.v:28.12-28.36|RTL/spi_clock_generator.v:28.9-32.8" *) 8'h00 : _1_[7:0];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_master.v:1.1-67.10" *)
module spi_master(clk, rst, start, data_in, clk_divider, miso, cpol, rx_data, spi_clk, mosi, busy, cs);
  (* src = "RTL/spi_master.v:25.12-25.21" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] bit_count;
  (* src = "RTL/spi_master.v:15.12-15.16" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_master.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master.v:8.17-8.28" *)
  input [7:0] clk_divider;
  wire [7:0] clk_divider;
  (* src = "RTL/spi_master.v:10.11-10.15" *)
  input cpol;
  wire cpol;
  (* src = "RTL/spi_master.v:16.12-16.14" *)
  output cs;
  wire cs;
  (* src = "RTL/spi_master.v:7.28-7.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/spi_master.v:22.6-22.10" *)
  wire done;
  (* src = "RTL/spi_master.v:21.6-21.12" *)
  wire enable;
  (* src = "RTL/spi_master.v:19.6-19.10" *)
  wire load;
  (* src = "RTL/spi_master.v:9.11-9.15" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_master.v:14.12-14.16" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_master.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master.v:12.29-12.36" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "RTL/spi_master.v:20.6-20.11" *)
  wire shift;
  (* src = "RTL/spi_master.v:24.23-24.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] shift_reg;
  (* src = "RTL/spi_master.v:13.12-13.19" *)
  output spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_master.v:6.11-6.16" *)
  input start;
  wire start;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master.v:27.21-33.2" *)
  spi_clock_generator clock_gen (
    .clk(clk),
    .clk_divider(clk_divider),
    .cpol(cpol),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master.v:55.16-65.2" *)
  spi_master_fsm controller (
    .busy(busy),
    .clk(clk),
    .cs(cs),
    .done(done),
    .enable(enable),
    .load(load),
    .rst(rst),
    .shift(shift),
    .start(start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master.v:47.17-53.2" *)
  spi_bit_counter counter (
    .bit_count(bit_count),
    .clk(clk),
    .done(done),
    .enable(enable),
    .rst(rst)
  );
  (* src = "RTL/spi_master.v:37.3-45.2" *)
  \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_register (
    .clk(clk),
    .data_in(data_in),
    .load(load),
    .mosi(mosi),
    .rst(rst),
    .shift(shift),
    .shift_reg(shift_reg)
  );
endmodule

(* src = "RTL/spi_master_fsm.v:1.1-84.10" *)
module spi_master_fsm(clk, rst, start, done, load, shift, enable, busy, cs);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/spi_master_fsm.v:35.26-35.45" *)
  wire [1:0] _05_;
  (* src = "RTL/spi_master_fsm.v:41.26-41.45" *)
  wire [1:0] _06_;
  (* src = "RTL/spi_master_fsm.v:10.16-10.20" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_master_fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_fsm.v:11.16-11.18" *)
  output cs;
  wire cs;
  (* src = "RTL/spi_master_fsm.v:5.11-5.15" *)
  input done;
  wire done;
  (* src = "RTL/spi_master_fsm.v:9.16-9.22" *)
  output enable;
  wire enable;
  (* src = "RTL/spi_master_fsm.v:7.16-7.20" *)
  output load;
  wire load;
  (* src = "RTL/spi_master_fsm.v:20.11-20.21" *)
  wire [1:0] next_state;
  (* src = "RTL/spi_master_fsm.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_fsm.v:8.16-8.21" *)
  output shift;
  wire shift;
  (* src = "RTL/spi_master_fsm.v:4.11-4.16" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_fsm.v:19.11-19.16" *)
  reg [1:0] state;
  assign _00_ = | { _02_, _01_ };
  (* src = "RTL/spi_master_fsm.v:22.1-27.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else state <= next_state;
  assign cs = _00_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:62.5-80.12" *) 1'h0 : 1'h1;
  assign busy = _00_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:62.5-80.12" *) 1'h1 : 1'h0;
  assign load = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:62.5-80.12" *) 1'h1 : 1'h0;
  assign enable = _01_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:62.5-80.12" *) 1'h1 : 1'h0;
  function [1:0] _13_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:32.5-49.12" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _13_ = b[1:0];
      4'b??1?:
        _13_ = b[3:2];
      4'b?1??:
        _13_ = b[5:4];
      4'b1???:
        _13_ = b[7:6];
      default:
        _13_ = a;
    endcase
  endfunction
  assign next_state = _13_(2'hx, { _05_, 2'h2, _06_, 2'h0 }, { _04_, _02_, _01_, _03_ });
  assign _03_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:32.5-49.12" *) 2'h3;
  assign _01_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:32.5-49.12" *) 2'h2;
  assign _02_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:32.5-49.12" *) 2'h1;
  assign _04_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:32.5-49.12" *) state;
  assign _05_ = start ? (* src = "RTL/spi_master_fsm.v:35.26-35.45" *) 2'h1 : 2'h0;
  assign _06_ = done ? (* src = "RTL/spi_master_fsm.v:41.26-41.45" *) 2'h3 : 2'h2;
  assign shift = enable;
endmodule
