/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module forwarding_comparator(rs, ex_mem_rd, mem_wb_rd, ex_mem_reg_write, mem_wb_reg_write, ex_mem_match, mem_wb_match);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output ex_mem_match;
  wire ex_mem_match;
  input [4:0] ex_mem_rd;
  wire [4:0] ex_mem_rd;
  input ex_mem_reg_write;
  wire ex_mem_reg_write;
  output mem_wb_match;
  wire mem_wb_match;
  input [4:0] mem_wb_rd;
  wire [4:0] mem_wb_rd;
  input mem_wb_reg_write;
  wire mem_wb_reg_write;
  input [4:0] rs;
  wire [4:0] rs;
  INV_X1 _20_ (
    .A(ex_mem_rd[2]),
    .ZN(_00_)
  );
  INV_X1 _21_ (
    .A(ex_mem_rd[4]),
    .ZN(_01_)
  );
  INV_X1 _22_ (
    .A(mem_wb_rd[2]),
    .ZN(_02_)
  );
  INV_X1 _23_ (
    .A(mem_wb_rd[4]),
    .ZN(_03_)
  );
  INV_X1 _24_ (
    .A(rs[1]),
    .ZN(_04_)
  );
  INV_X1 _25_ (
    .A(rs[3]),
    .ZN(_05_)
  );
  NOR4_X1 _26_ (
    .A1(ex_mem_rd[0]),
    .A2(ex_mem_rd[1]),
    .A3(ex_mem_rd[2]),
    .A4(ex_mem_rd[3]),
    .ZN(_06_)
  );
  OAI21_X1 _27_ (
    .A(_01_),
    .B1(rs[4]),
    .B2(_06_),
    .ZN(_07_)
  );
  OAI22_X1 _28_ (
    .A1(ex_mem_rd[1]),
    .A2(_04_),
    .B1(rs[2]),
    .B2(_00_),
    .ZN(_08_)
  );
  XOR2_X1 _29_ (
    .A(ex_mem_rd[0]),
    .B(rs[0]),
    .Z(_09_)
  );
  AOI211_X1 _30_ (
    .A(_08_),
    .B(_09_),
    .C1(ex_mem_rd[1]),
    .C2(_04_),
    .ZN(_10_)
  );
  OAI221_X1 _31_ (
    .A(ex_mem_reg_write),
    .B1(_05_),
    .B2(ex_mem_rd[3]),
    .C1(rs[4]),
    .C2(_01_),
    .ZN(_11_)
  );
  AOI221_X1 _32_ (
    .A(_11_),
    .B1(_05_),
    .B2(ex_mem_rd[3]),
    .C1(_00_),
    .C2(rs[2]),
    .ZN(_12_)
  );
  AND3_X1 _33_ (
    .A1(_07_),
    .A2(_10_),
    .A3(_12_),
    .ZN(ex_mem_match)
  );
  NOR4_X1 _34_ (
    .A1(mem_wb_rd[0]),
    .A2(mem_wb_rd[1]),
    .A3(mem_wb_rd[2]),
    .A4(mem_wb_rd[3]),
    .ZN(_13_)
  );
  OAI21_X1 _35_ (
    .A(_03_),
    .B1(rs[4]),
    .B2(_13_),
    .ZN(_14_)
  );
  OAI22_X1 _36_ (
    .A1(mem_wb_rd[1]),
    .A2(_04_),
    .B1(rs[2]),
    .B2(_02_),
    .ZN(_15_)
  );
  XOR2_X1 _37_ (
    .A(mem_wb_rd[0]),
    .B(rs[0]),
    .Z(_16_)
  );
  AOI211_X1 _38_ (
    .A(_15_),
    .B(_16_),
    .C1(mem_wb_rd[1]),
    .C2(_04_),
    .ZN(_17_)
  );
  OAI221_X1 _39_ (
    .A(mem_wb_reg_write),
    .B1(_05_),
    .B2(mem_wb_rd[3]),
    .C1(rs[4]),
    .C2(_03_),
    .ZN(_18_)
  );
  AOI221_X1 _40_ (
    .A(_18_),
    .B1(_05_),
    .B2(mem_wb_rd[3]),
    .C1(_02_),
    .C2(rs[2]),
    .ZN(_19_)
  );
  AND3_X1 _41_ (
    .A1(_14_),
    .A2(_17_),
    .A3(_19_),
    .ZN(mem_wb_match)
  );
endmodule

module forwarding_control_logic(ex_mem_match_rs1, mem_wb_match_rs1, ex_mem_match_rs2, mem_wb_match_rs2, forward_a, forward_b);
  wire _0_;
  wire _1_;
  input ex_mem_match_rs1;
  wire ex_mem_match_rs1;
  input ex_mem_match_rs2;
  wire ex_mem_match_rs2;
  output [1:0] forward_a;
  wire [1:0] forward_a;
  output [1:0] forward_b;
  wire [1:0] forward_b;
  input mem_wb_match_rs1;
  wire mem_wb_match_rs1;
  input mem_wb_match_rs2;
  wire mem_wb_match_rs2;
  INV_X1 _2_ (
    .A(mem_wb_match_rs2),
    .ZN(_0_)
  );
  INV_X1 _3_ (
    .A(mem_wb_match_rs1),
    .ZN(_1_)
  );
  NOR2_X1 _4_ (
    .A1(_0_),
    .A2(ex_mem_match_rs2),
    .ZN(forward_b[0])
  );
  NOR2_X1 _5_ (
    .A1(_1_),
    .A2(ex_mem_match_rs1),
    .ZN(forward_a[0])
  );
  assign forward_a[1] = ex_mem_match_rs1;
  assign forward_b[1] = ex_mem_match_rs2;
endmodule

module forwarding_unit(rs1, rs2, ex_mem_rd, ex_mem_reg_write, mem_wb_rd, mem_wb_reg_write, forward_a, forward_b);
  wire ex_mem_match_rs1;
  wire ex_mem_match_rs2;
  input [4:0] ex_mem_rd;
  wire [4:0] ex_mem_rd;
  input ex_mem_reg_write;
  wire ex_mem_reg_write;
  output [1:0] forward_a;
  wire [1:0] forward_a;
  output [1:0] forward_b;
  wire [1:0] forward_b;
  wire mem_wb_match_rs1;
  wire mem_wb_match_rs2;
  input [4:0] mem_wb_rd;
  wire [4:0] mem_wb_rd;
  input mem_wb_reg_write;
  wire mem_wb_reg_write;
  input [4:0] rs1;
  wire [4:0] rs1;
  input [4:0] rs2;
  wire [4:0] rs2;
  forwarding_comparator comparator_rs1 (
    .ex_mem_match(ex_mem_match_rs1),
    .ex_mem_rd(ex_mem_rd),
    .ex_mem_reg_write(ex_mem_reg_write),
    .mem_wb_match(mem_wb_match_rs1),
    .mem_wb_rd(mem_wb_rd),
    .mem_wb_reg_write(mem_wb_reg_write),
    .rs(rs1)
  );
  forwarding_comparator comparator_rs2 (
    .ex_mem_match(ex_mem_match_rs2),
    .ex_mem_rd(ex_mem_rd),
    .ex_mem_reg_write(ex_mem_reg_write),
    .mem_wb_match(mem_wb_match_rs2),
    .mem_wb_rd(mem_wb_rd),
    .mem_wb_reg_write(mem_wb_reg_write),
    .rs(rs2)
  );
  forwarding_control_logic control_logic (
    .ex_mem_match_rs1(ex_mem_match_rs1),
    .ex_mem_match_rs2(ex_mem_match_rs2),
    .forward_a(forward_a),
    .forward_b(forward_b),
    .mem_wb_match_rs1(mem_wb_match_rs1),
    .mem_wb_match_rs2(mem_wb_match_rs2)
  );
endmodule
