/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module pipelined_alu_top(clk, rst, stall_request, flush_request, fetch_pc, fetch_instruction, decode_rs1_value, decode_rs2_value, decode_immediate, decode_rs1, decode_rs2, decode_rd, decode_alu_control, decode_reg_write, decode_mem_read, decode_mem_write, decode_mem_to_reg, decode_alu_src, execute_result, execute_store_data, execute_zero
, memory_read_data, wb_alu_result, wb_memory_data, wb_rd, wb_reg_write, wb_mem_to_reg);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  input clk;
  wire clk;
  wire \control_unit.flush_request ;
  wire \control_unit.stall_request ;
  input [3:0] decode_alu_control;
  wire [3:0] decode_alu_control;
  input decode_alu_src;
  wire decode_alu_src;
  input [31:0] decode_immediate;
  wire [31:0] decode_immediate;
  input decode_mem_read;
  wire decode_mem_read;
  input decode_mem_to_reg;
  wire decode_mem_to_reg;
  input decode_mem_write;
  wire decode_mem_write;
  input [4:0] decode_rd;
  wire [4:0] decode_rd;
  input decode_reg_write;
  wire decode_reg_write;
  input [4:0] decode_rs1;
  wire [4:0] decode_rs1;
  input [31:0] decode_rs1_value;
  wire [31:0] decode_rs1_value;
  input [4:0] decode_rs2;
  wire [4:0] decode_rs2;
  input [31:0] decode_rs2_value;
  wire [31:0] decode_rs2_value;
  wire [31:0] \ex_mem.alu_result_in ;
  wire [31:0] \ex_mem.alu_result_out ;
  wire \ex_mem.clk ;
  wire \ex_mem.flush ;
  wire \ex_mem.mem_to_reg_in ;
  wire \ex_mem.mem_to_reg_out ;
  wire [4:0] \ex_mem.rd_in ;
  wire [4:0] \ex_mem.rd_out ;
  wire \ex_mem.reg_write_in ;
  wire \ex_mem.reg_write_out ;
  wire \ex_mem.rst ;
  wire \ex_mem.stall ;
  wire [31:0] \ex_mem.store_data_in ;
  wire \ex_mem.zero_in ;
  wire [31:0] ex_mem_alu_result;
  wire ex_mem_mem_to_reg;
  wire [4:0] ex_mem_rd;
  wire ex_mem_reg_write;
  input [31:0] execute_result;
  wire [31:0] execute_result;
  input [31:0] execute_store_data;
  wire [31:0] execute_store_data;
  input execute_zero;
  wire execute_zero;
  input [31:0] fetch_instruction;
  wire [31:0] fetch_instruction;
  input [31:0] fetch_pc;
  wire [31:0] fetch_pc;
  input flush_request;
  wire flush_request;
  wire [3:0] \id_ex.alu_control_in ;
  wire \id_ex.alu_src_in ;
  wire \id_ex.clk ;
  wire [31:0] \id_ex.immediate_in ;
  wire \id_ex.mem_read_in ;
  wire \id_ex.mem_to_reg_in ;
  wire \id_ex.mem_to_reg_out ;
  wire \id_ex.mem_write_in ;
  wire [4:0] \id_ex.rd_in ;
  wire [4:0] \id_ex.rd_out ;
  wire \id_ex.reg_write_in ;
  wire \id_ex.reg_write_out ;
  wire [4:0] \id_ex.rs1_in ;
  wire [31:0] \id_ex.rs1_value_in ;
  wire [4:0] \id_ex.rs2_in ;
  wire [31:0] \id_ex.rs2_value_in ;
  wire \id_ex.rst ;
  wire \id_ex.stall ;
  wire id_ex_mem_to_reg;
  wire [4:0] id_ex_rd;
  wire id_ex_reg_write;
  wire \if_id.clk ;
  wire \if_id.flush ;
  wire [31:0] \if_id.instruction_in ;
  wire [31:0] \if_id.pc_in ;
  wire \if_id.rst ;
  wire [31:0] \mem_wb.alu_result_in ;
  wire [31:0] \mem_wb.alu_result_out ;
  wire \mem_wb.clk ;
  wire \mem_wb.flush ;
  wire [31:0] \mem_wb.mem_data_in ;
  wire [31:0] \mem_wb.mem_data_out ;
  wire \mem_wb.mem_to_reg_in ;
  wire \mem_wb.mem_to_reg_out ;
  wire [4:0] \mem_wb.rd_in ;
  wire [4:0] \mem_wb.rd_out ;
  wire \mem_wb.reg_write_in ;
  wire \mem_wb.reg_write_out ;
  wire \mem_wb.rst ;
  wire \mem_wb.stall ;
  wire [31:0] mem_wb_alu_result;
  wire [31:0] mem_wb_data;
  wire mem_wb_mem_to_reg;
  wire [4:0] mem_wb_rd;
  wire mem_wb_reg_write;
  input [31:0] memory_read_data;
  wire [31:0] memory_read_data;
  input rst;
  wire rst;
  input stall_request;
  wire stall_request;
  output [31:0] wb_alu_result;
  wire [31:0] wb_alu_result;
  output wb_mem_to_reg;
  wire wb_mem_to_reg;
  output [31:0] wb_memory_data;
  wire [31:0] wb_memory_data;
  output [4:0] wb_rd;
  wire [4:0] wb_rd;
  output wb_reg_write;
  wire wb_reg_write;
  NOR2_X1 _236_ (
    .A1(flush_request),
    .A2(rst),
    .ZN(_117_)
  );
  AND2_X1 _237_ (
    .A1(execute_result[0]),
    .A2(_117_),
    .ZN(_000_)
  );
  AND2_X1 _238_ (
    .A1(execute_result[1]),
    .A2(_117_),
    .ZN(_001_)
  );
  AND2_X1 _239_ (
    .A1(execute_result[2]),
    .A2(_117_),
    .ZN(_002_)
  );
  AND2_X1 _240_ (
    .A1(execute_result[3]),
    .A2(_117_),
    .ZN(_003_)
  );
  AND2_X1 _241_ (
    .A1(execute_result[4]),
    .A2(_117_),
    .ZN(_004_)
  );
  AND2_X1 _242_ (
    .A1(execute_result[5]),
    .A2(_117_),
    .ZN(_005_)
  );
  AND2_X1 _243_ (
    .A1(execute_result[6]),
    .A2(_117_),
    .ZN(_006_)
  );
  AND2_X1 _244_ (
    .A1(execute_result[7]),
    .A2(_117_),
    .ZN(_007_)
  );
  AND2_X1 _245_ (
    .A1(execute_result[8]),
    .A2(_117_),
    .ZN(_008_)
  );
  AND2_X1 _246_ (
    .A1(execute_result[9]),
    .A2(_117_),
    .ZN(_009_)
  );
  AND2_X1 _247_ (
    .A1(execute_result[10]),
    .A2(_117_),
    .ZN(_010_)
  );
  AND2_X1 _248_ (
    .A1(execute_result[11]),
    .A2(_117_),
    .ZN(_011_)
  );
  AND2_X1 _249_ (
    .A1(execute_result[12]),
    .A2(_117_),
    .ZN(_012_)
  );
  AND2_X1 _250_ (
    .A1(execute_result[13]),
    .A2(_117_),
    .ZN(_013_)
  );
  AND2_X1 _251_ (
    .A1(execute_result[14]),
    .A2(_117_),
    .ZN(_014_)
  );
  AND2_X1 _252_ (
    .A1(execute_result[15]),
    .A2(_117_),
    .ZN(_015_)
  );
  AND2_X1 _253_ (
    .A1(execute_result[16]),
    .A2(_117_),
    .ZN(_016_)
  );
  AND2_X1 _254_ (
    .A1(execute_result[17]),
    .A2(_117_),
    .ZN(_017_)
  );
  AND2_X1 _255_ (
    .A1(execute_result[18]),
    .A2(_117_),
    .ZN(_018_)
  );
  AND2_X1 _256_ (
    .A1(execute_result[19]),
    .A2(_117_),
    .ZN(_019_)
  );
  AND2_X1 _257_ (
    .A1(execute_result[20]),
    .A2(_117_),
    .ZN(_020_)
  );
  AND2_X1 _258_ (
    .A1(execute_result[21]),
    .A2(_117_),
    .ZN(_021_)
  );
  AND2_X1 _259_ (
    .A1(execute_result[22]),
    .A2(_117_),
    .ZN(_022_)
  );
  AND2_X1 _260_ (
    .A1(execute_result[23]),
    .A2(_117_),
    .ZN(_023_)
  );
  AND2_X1 _261_ (
    .A1(execute_result[24]),
    .A2(_117_),
    .ZN(_024_)
  );
  AND2_X1 _262_ (
    .A1(execute_result[25]),
    .A2(_117_),
    .ZN(_025_)
  );
  AND2_X1 _263_ (
    .A1(execute_result[26]),
    .A2(_117_),
    .ZN(_026_)
  );
  AND2_X1 _264_ (
    .A1(execute_result[27]),
    .A2(_117_),
    .ZN(_027_)
  );
  AND2_X1 _265_ (
    .A1(execute_result[28]),
    .A2(_117_),
    .ZN(_028_)
  );
  AND2_X1 _266_ (
    .A1(execute_result[29]),
    .A2(_117_),
    .ZN(_029_)
  );
  AND2_X1 _267_ (
    .A1(execute_result[30]),
    .A2(_117_),
    .ZN(_030_)
  );
  AND2_X1 _268_ (
    .A1(execute_result[31]),
    .A2(_117_),
    .ZN(_031_)
  );
  AND2_X1 _269_ (
    .A1(\id_ex.mem_to_reg_out ),
    .A2(_117_),
    .ZN(_032_)
  );
  AND2_X1 _270_ (
    .A1(\id_ex.reg_write_out ),
    .A2(_117_),
    .ZN(_033_)
  );
  AND2_X1 _271_ (
    .A1(\id_ex.rd_out [0]),
    .A2(_117_),
    .ZN(_034_)
  );
  AND2_X1 _272_ (
    .A1(\id_ex.rd_out [1]),
    .A2(_117_),
    .ZN(_035_)
  );
  AND2_X1 _273_ (
    .A1(\id_ex.rd_out [2]),
    .A2(_117_),
    .ZN(_036_)
  );
  AND2_X1 _274_ (
    .A1(\id_ex.rd_out [3]),
    .A2(_117_),
    .ZN(_037_)
  );
  AND2_X1 _275_ (
    .A1(\id_ex.rd_out [4]),
    .A2(_117_),
    .ZN(_038_)
  );
  NOR3_X1 _276_ (
    .A1(flush_request),
    .A2(rst),
    .A3(stall_request),
    .ZN(_118_)
  );
  AND2_X1 _277_ (
    .A1(decode_mem_to_reg),
    .A2(_118_),
    .ZN(_039_)
  );
  AND2_X1 _278_ (
    .A1(decode_reg_write),
    .A2(_118_),
    .ZN(_040_)
  );
  AND2_X1 _279_ (
    .A1(decode_rd[0]),
    .A2(_118_),
    .ZN(_041_)
  );
  AND2_X1 _280_ (
    .A1(decode_rd[1]),
    .A2(_118_),
    .ZN(_042_)
  );
  AND2_X1 _281_ (
    .A1(decode_rd[2]),
    .A2(_118_),
    .ZN(_043_)
  );
  AND2_X1 _282_ (
    .A1(decode_rd[3]),
    .A2(_118_),
    .ZN(_044_)
  );
  AND2_X1 _283_ (
    .A1(decode_rd[4]),
    .A2(_118_),
    .ZN(_045_)
  );
  AND2_X1 _284_ (
    .A1(memory_read_data[0]),
    .A2(_117_),
    .ZN(_046_)
  );
  AND2_X1 _285_ (
    .A1(memory_read_data[1]),
    .A2(_117_),
    .ZN(_047_)
  );
  AND2_X1 _286_ (
    .A1(memory_read_data[2]),
    .A2(_117_),
    .ZN(_048_)
  );
  AND2_X1 _287_ (
    .A1(memory_read_data[3]),
    .A2(_117_),
    .ZN(_049_)
  );
  AND2_X1 _288_ (
    .A1(memory_read_data[4]),
    .A2(_117_),
    .ZN(_050_)
  );
  AND2_X1 _289_ (
    .A1(memory_read_data[5]),
    .A2(_117_),
    .ZN(_051_)
  );
  AND2_X1 _290_ (
    .A1(memory_read_data[6]),
    .A2(_117_),
    .ZN(_052_)
  );
  AND2_X1 _291_ (
    .A1(memory_read_data[7]),
    .A2(_117_),
    .ZN(_053_)
  );
  AND2_X1 _292_ (
    .A1(memory_read_data[8]),
    .A2(_117_),
    .ZN(_054_)
  );
  AND2_X1 _293_ (
    .A1(memory_read_data[9]),
    .A2(_117_),
    .ZN(_055_)
  );
  AND2_X1 _294_ (
    .A1(memory_read_data[10]),
    .A2(_117_),
    .ZN(_056_)
  );
  AND2_X1 _295_ (
    .A1(memory_read_data[11]),
    .A2(_117_),
    .ZN(_057_)
  );
  AND2_X1 _296_ (
    .A1(memory_read_data[12]),
    .A2(_117_),
    .ZN(_058_)
  );
  AND2_X1 _297_ (
    .A1(memory_read_data[13]),
    .A2(_117_),
    .ZN(_059_)
  );
  AND2_X1 _298_ (
    .A1(memory_read_data[14]),
    .A2(_117_),
    .ZN(_060_)
  );
  AND2_X1 _299_ (
    .A1(memory_read_data[15]),
    .A2(_117_),
    .ZN(_061_)
  );
  AND2_X1 _300_ (
    .A1(memory_read_data[16]),
    .A2(_117_),
    .ZN(_062_)
  );
  AND2_X1 _301_ (
    .A1(memory_read_data[17]),
    .A2(_117_),
    .ZN(_063_)
  );
  AND2_X1 _302_ (
    .A1(memory_read_data[18]),
    .A2(_117_),
    .ZN(_064_)
  );
  AND2_X1 _303_ (
    .A1(memory_read_data[19]),
    .A2(_117_),
    .ZN(_065_)
  );
  AND2_X1 _304_ (
    .A1(memory_read_data[20]),
    .A2(_117_),
    .ZN(_066_)
  );
  AND2_X1 _305_ (
    .A1(memory_read_data[21]),
    .A2(_117_),
    .ZN(_067_)
  );
  AND2_X1 _306_ (
    .A1(memory_read_data[22]),
    .A2(_117_),
    .ZN(_068_)
  );
  AND2_X1 _307_ (
    .A1(memory_read_data[23]),
    .A2(_117_),
    .ZN(_069_)
  );
  AND2_X1 _308_ (
    .A1(memory_read_data[24]),
    .A2(_117_),
    .ZN(_070_)
  );
  AND2_X1 _309_ (
    .A1(memory_read_data[25]),
    .A2(_117_),
    .ZN(_071_)
  );
  AND2_X1 _310_ (
    .A1(memory_read_data[26]),
    .A2(_117_),
    .ZN(_072_)
  );
  AND2_X1 _311_ (
    .A1(memory_read_data[27]),
    .A2(_117_),
    .ZN(_073_)
  );
  AND2_X1 _312_ (
    .A1(memory_read_data[28]),
    .A2(_117_),
    .ZN(_074_)
  );
  AND2_X1 _313_ (
    .A1(memory_read_data[29]),
    .A2(_117_),
    .ZN(_075_)
  );
  AND2_X1 _314_ (
    .A1(memory_read_data[30]),
    .A2(_117_),
    .ZN(_076_)
  );
  AND2_X1 _315_ (
    .A1(memory_read_data[31]),
    .A2(_117_),
    .ZN(_077_)
  );
  AND2_X1 _316_ (
    .A1(\ex_mem.alu_result_out [0]),
    .A2(_117_),
    .ZN(_078_)
  );
  AND2_X1 _317_ (
    .A1(\ex_mem.alu_result_out [1]),
    .A2(_117_),
    .ZN(_079_)
  );
  AND2_X1 _318_ (
    .A1(\ex_mem.alu_result_out [2]),
    .A2(_117_),
    .ZN(_080_)
  );
  AND2_X1 _319_ (
    .A1(\ex_mem.alu_result_out [3]),
    .A2(_117_),
    .ZN(_081_)
  );
  AND2_X1 _320_ (
    .A1(\ex_mem.alu_result_out [4]),
    .A2(_117_),
    .ZN(_082_)
  );
  AND2_X1 _321_ (
    .A1(\ex_mem.alu_result_out [5]),
    .A2(_117_),
    .ZN(_083_)
  );
  AND2_X1 _322_ (
    .A1(\ex_mem.alu_result_out [6]),
    .A2(_117_),
    .ZN(_084_)
  );
  AND2_X1 _323_ (
    .A1(\ex_mem.alu_result_out [7]),
    .A2(_117_),
    .ZN(_085_)
  );
  AND2_X1 _324_ (
    .A1(\ex_mem.alu_result_out [8]),
    .A2(_117_),
    .ZN(_086_)
  );
  AND2_X1 _325_ (
    .A1(\ex_mem.alu_result_out [9]),
    .A2(_117_),
    .ZN(_087_)
  );
  AND2_X1 _326_ (
    .A1(\ex_mem.alu_result_out [10]),
    .A2(_117_),
    .ZN(_088_)
  );
  AND2_X1 _327_ (
    .A1(\ex_mem.alu_result_out [11]),
    .A2(_117_),
    .ZN(_089_)
  );
  AND2_X1 _328_ (
    .A1(\ex_mem.alu_result_out [12]),
    .A2(_117_),
    .ZN(_090_)
  );
  AND2_X1 _329_ (
    .A1(\ex_mem.alu_result_out [13]),
    .A2(_117_),
    .ZN(_091_)
  );
  AND2_X1 _330_ (
    .A1(\ex_mem.alu_result_out [14]),
    .A2(_117_),
    .ZN(_092_)
  );
  AND2_X1 _331_ (
    .A1(\ex_mem.alu_result_out [15]),
    .A2(_117_),
    .ZN(_093_)
  );
  AND2_X1 _332_ (
    .A1(\ex_mem.alu_result_out [16]),
    .A2(_117_),
    .ZN(_094_)
  );
  AND2_X1 _333_ (
    .A1(\ex_mem.alu_result_out [17]),
    .A2(_117_),
    .ZN(_095_)
  );
  AND2_X1 _334_ (
    .A1(\ex_mem.alu_result_out [18]),
    .A2(_117_),
    .ZN(_096_)
  );
  AND2_X1 _335_ (
    .A1(\ex_mem.alu_result_out [19]),
    .A2(_117_),
    .ZN(_097_)
  );
  AND2_X1 _336_ (
    .A1(\ex_mem.alu_result_out [20]),
    .A2(_117_),
    .ZN(_098_)
  );
  AND2_X1 _337_ (
    .A1(\ex_mem.alu_result_out [21]),
    .A2(_117_),
    .ZN(_099_)
  );
  AND2_X1 _338_ (
    .A1(\ex_mem.alu_result_out [22]),
    .A2(_117_),
    .ZN(_100_)
  );
  AND2_X1 _339_ (
    .A1(\ex_mem.alu_result_out [23]),
    .A2(_117_),
    .ZN(_101_)
  );
  AND2_X1 _340_ (
    .A1(\ex_mem.alu_result_out [24]),
    .A2(_117_),
    .ZN(_102_)
  );
  AND2_X1 _341_ (
    .A1(\ex_mem.alu_result_out [25]),
    .A2(_117_),
    .ZN(_103_)
  );
  AND2_X1 _342_ (
    .A1(\ex_mem.alu_result_out [26]),
    .A2(_117_),
    .ZN(_104_)
  );
  AND2_X1 _343_ (
    .A1(\ex_mem.alu_result_out [27]),
    .A2(_117_),
    .ZN(_105_)
  );
  AND2_X1 _344_ (
    .A1(\ex_mem.alu_result_out [28]),
    .A2(_117_),
    .ZN(_106_)
  );
  AND2_X1 _345_ (
    .A1(\ex_mem.alu_result_out [29]),
    .A2(_117_),
    .ZN(_107_)
  );
  AND2_X1 _346_ (
    .A1(\ex_mem.alu_result_out [30]),
    .A2(_117_),
    .ZN(_108_)
  );
  AND2_X1 _347_ (
    .A1(\ex_mem.alu_result_out [31]),
    .A2(_117_),
    .ZN(_109_)
  );
  AND2_X1 _348_ (
    .A1(\ex_mem.mem_to_reg_out ),
    .A2(_117_),
    .ZN(_110_)
  );
  AND2_X1 _349_ (
    .A1(\ex_mem.reg_write_out ),
    .A2(_117_),
    .ZN(_111_)
  );
  AND2_X1 _350_ (
    .A1(\ex_mem.rd_out [0]),
    .A2(_117_),
    .ZN(_112_)
  );
  AND2_X1 _351_ (
    .A1(\ex_mem.rd_out [1]),
    .A2(_117_),
    .ZN(_113_)
  );
  AND2_X1 _352_ (
    .A1(\ex_mem.rd_out [2]),
    .A2(_117_),
    .ZN(_114_)
  );
  AND2_X1 _353_ (
    .A1(\ex_mem.rd_out [3]),
    .A2(_117_),
    .ZN(_115_)
  );
  AND2_X1 _354_ (
    .A1(\ex_mem.rd_out [4]),
    .A2(_117_),
    .ZN(_116_)
  );
  DFF_X1 _355_ (
    .CK(clk),
    .D(_000_),
    .Q(\ex_mem.alu_result_out [0]),
    .QN(_235_)
  );
  DFF_X1 _356_ (
    .CK(clk),
    .D(_001_),
    .Q(\ex_mem.alu_result_out [1]),
    .QN(_234_)
  );
  DFF_X1 _357_ (
    .CK(clk),
    .D(_002_),
    .Q(\ex_mem.alu_result_out [2]),
    .QN(_233_)
  );
  DFF_X1 _358_ (
    .CK(clk),
    .D(_003_),
    .Q(\ex_mem.alu_result_out [3]),
    .QN(_232_)
  );
  DFF_X1 _359_ (
    .CK(clk),
    .D(_004_),
    .Q(\ex_mem.alu_result_out [4]),
    .QN(_231_)
  );
  DFF_X1 _360_ (
    .CK(clk),
    .D(_005_),
    .Q(\ex_mem.alu_result_out [5]),
    .QN(_230_)
  );
  DFF_X1 _361_ (
    .CK(clk),
    .D(_006_),
    .Q(\ex_mem.alu_result_out [6]),
    .QN(_229_)
  );
  DFF_X1 _362_ (
    .CK(clk),
    .D(_007_),
    .Q(\ex_mem.alu_result_out [7]),
    .QN(_228_)
  );
  DFF_X1 _363_ (
    .CK(clk),
    .D(_008_),
    .Q(\ex_mem.alu_result_out [8]),
    .QN(_227_)
  );
  DFF_X1 _364_ (
    .CK(clk),
    .D(_009_),
    .Q(\ex_mem.alu_result_out [9]),
    .QN(_226_)
  );
  DFF_X1 _365_ (
    .CK(clk),
    .D(_010_),
    .Q(\ex_mem.alu_result_out [10]),
    .QN(_225_)
  );
  DFF_X1 _366_ (
    .CK(clk),
    .D(_011_),
    .Q(\ex_mem.alu_result_out [11]),
    .QN(_224_)
  );
  DFF_X1 _367_ (
    .CK(clk),
    .D(_012_),
    .Q(\ex_mem.alu_result_out [12]),
    .QN(_223_)
  );
  DFF_X1 _368_ (
    .CK(clk),
    .D(_013_),
    .Q(\ex_mem.alu_result_out [13]),
    .QN(_222_)
  );
  DFF_X1 _369_ (
    .CK(clk),
    .D(_014_),
    .Q(\ex_mem.alu_result_out [14]),
    .QN(_221_)
  );
  DFF_X1 _370_ (
    .CK(clk),
    .D(_015_),
    .Q(\ex_mem.alu_result_out [15]),
    .QN(_220_)
  );
  DFF_X1 _371_ (
    .CK(clk),
    .D(_016_),
    .Q(\ex_mem.alu_result_out [16]),
    .QN(_219_)
  );
  DFF_X1 _372_ (
    .CK(clk),
    .D(_017_),
    .Q(\ex_mem.alu_result_out [17]),
    .QN(_218_)
  );
  DFF_X1 _373_ (
    .CK(clk),
    .D(_018_),
    .Q(\ex_mem.alu_result_out [18]),
    .QN(_217_)
  );
  DFF_X1 _374_ (
    .CK(clk),
    .D(_019_),
    .Q(\ex_mem.alu_result_out [19]),
    .QN(_216_)
  );
  DFF_X1 _375_ (
    .CK(clk),
    .D(_020_),
    .Q(\ex_mem.alu_result_out [20]),
    .QN(_215_)
  );
  DFF_X1 _376_ (
    .CK(clk),
    .D(_021_),
    .Q(\ex_mem.alu_result_out [21]),
    .QN(_214_)
  );
  DFF_X1 _377_ (
    .CK(clk),
    .D(_022_),
    .Q(\ex_mem.alu_result_out [22]),
    .QN(_213_)
  );
  DFF_X1 _378_ (
    .CK(clk),
    .D(_023_),
    .Q(\ex_mem.alu_result_out [23]),
    .QN(_212_)
  );
  DFF_X1 _379_ (
    .CK(clk),
    .D(_024_),
    .Q(\ex_mem.alu_result_out [24]),
    .QN(_211_)
  );
  DFF_X1 _380_ (
    .CK(clk),
    .D(_025_),
    .Q(\ex_mem.alu_result_out [25]),
    .QN(_210_)
  );
  DFF_X1 _381_ (
    .CK(clk),
    .D(_026_),
    .Q(\ex_mem.alu_result_out [26]),
    .QN(_209_)
  );
  DFF_X1 _382_ (
    .CK(clk),
    .D(_027_),
    .Q(\ex_mem.alu_result_out [27]),
    .QN(_208_)
  );
  DFF_X1 _383_ (
    .CK(clk),
    .D(_028_),
    .Q(\ex_mem.alu_result_out [28]),
    .QN(_207_)
  );
  DFF_X1 _384_ (
    .CK(clk),
    .D(_029_),
    .Q(\ex_mem.alu_result_out [29]),
    .QN(_206_)
  );
  DFF_X1 _385_ (
    .CK(clk),
    .D(_030_),
    .Q(\ex_mem.alu_result_out [30]),
    .QN(_205_)
  );
  DFF_X1 _386_ (
    .CK(clk),
    .D(_031_),
    .Q(\ex_mem.alu_result_out [31]),
    .QN(_204_)
  );
  DFF_X1 _387_ (
    .CK(clk),
    .D(_032_),
    .Q(\ex_mem.mem_to_reg_out ),
    .QN(_203_)
  );
  DFF_X1 _388_ (
    .CK(clk),
    .D(_033_),
    .Q(\ex_mem.reg_write_out ),
    .QN(_202_)
  );
  DFF_X1 _389_ (
    .CK(clk),
    .D(_034_),
    .Q(\ex_mem.rd_out [0]),
    .QN(_201_)
  );
  DFF_X1 _390_ (
    .CK(clk),
    .D(_035_),
    .Q(\ex_mem.rd_out [1]),
    .QN(_200_)
  );
  DFF_X1 _391_ (
    .CK(clk),
    .D(_036_),
    .Q(\ex_mem.rd_out [2]),
    .QN(_199_)
  );
  DFF_X1 _392_ (
    .CK(clk),
    .D(_037_),
    .Q(\ex_mem.rd_out [3]),
    .QN(_198_)
  );
  DFF_X1 _393_ (
    .CK(clk),
    .D(_038_),
    .Q(\ex_mem.rd_out [4]),
    .QN(_197_)
  );
  DFF_X1 _394_ (
    .CK(clk),
    .D(_039_),
    .Q(\id_ex.mem_to_reg_out ),
    .QN(_196_)
  );
  DFF_X1 _395_ (
    .CK(clk),
    .D(_040_),
    .Q(\id_ex.reg_write_out ),
    .QN(_195_)
  );
  DFF_X1 _396_ (
    .CK(clk),
    .D(_041_),
    .Q(\id_ex.rd_out [0]),
    .QN(_194_)
  );
  DFF_X1 _397_ (
    .CK(clk),
    .D(_042_),
    .Q(\id_ex.rd_out [1]),
    .QN(_193_)
  );
  DFF_X1 _398_ (
    .CK(clk),
    .D(_043_),
    .Q(\id_ex.rd_out [2]),
    .QN(_192_)
  );
  DFF_X1 _399_ (
    .CK(clk),
    .D(_044_),
    .Q(\id_ex.rd_out [3]),
    .QN(_191_)
  );
  DFF_X1 _400_ (
    .CK(clk),
    .D(_045_),
    .Q(\id_ex.rd_out [4]),
    .QN(_190_)
  );
  DFF_X1 _401_ (
    .CK(clk),
    .D(_046_),
    .Q(\mem_wb.mem_data_out [0]),
    .QN(_189_)
  );
  DFF_X1 _402_ (
    .CK(clk),
    .D(_047_),
    .Q(\mem_wb.mem_data_out [1]),
    .QN(_188_)
  );
  DFF_X1 _403_ (
    .CK(clk),
    .D(_048_),
    .Q(\mem_wb.mem_data_out [2]),
    .QN(_187_)
  );
  DFF_X1 _404_ (
    .CK(clk),
    .D(_049_),
    .Q(\mem_wb.mem_data_out [3]),
    .QN(_186_)
  );
  DFF_X1 _405_ (
    .CK(clk),
    .D(_050_),
    .Q(\mem_wb.mem_data_out [4]),
    .QN(_185_)
  );
  DFF_X1 _406_ (
    .CK(clk),
    .D(_051_),
    .Q(\mem_wb.mem_data_out [5]),
    .QN(_184_)
  );
  DFF_X1 _407_ (
    .CK(clk),
    .D(_052_),
    .Q(\mem_wb.mem_data_out [6]),
    .QN(_183_)
  );
  DFF_X1 _408_ (
    .CK(clk),
    .D(_053_),
    .Q(\mem_wb.mem_data_out [7]),
    .QN(_182_)
  );
  DFF_X1 _409_ (
    .CK(clk),
    .D(_054_),
    .Q(\mem_wb.mem_data_out [8]),
    .QN(_181_)
  );
  DFF_X1 _410_ (
    .CK(clk),
    .D(_055_),
    .Q(\mem_wb.mem_data_out [9]),
    .QN(_180_)
  );
  DFF_X1 _411_ (
    .CK(clk),
    .D(_056_),
    .Q(\mem_wb.mem_data_out [10]),
    .QN(_179_)
  );
  DFF_X1 _412_ (
    .CK(clk),
    .D(_057_),
    .Q(\mem_wb.mem_data_out [11]),
    .QN(_178_)
  );
  DFF_X1 _413_ (
    .CK(clk),
    .D(_058_),
    .Q(\mem_wb.mem_data_out [12]),
    .QN(_177_)
  );
  DFF_X1 _414_ (
    .CK(clk),
    .D(_059_),
    .Q(\mem_wb.mem_data_out [13]),
    .QN(_176_)
  );
  DFF_X1 _415_ (
    .CK(clk),
    .D(_060_),
    .Q(\mem_wb.mem_data_out [14]),
    .QN(_175_)
  );
  DFF_X1 _416_ (
    .CK(clk),
    .D(_061_),
    .Q(\mem_wb.mem_data_out [15]),
    .QN(_174_)
  );
  DFF_X1 _417_ (
    .CK(clk),
    .D(_062_),
    .Q(\mem_wb.mem_data_out [16]),
    .QN(_173_)
  );
  DFF_X1 _418_ (
    .CK(clk),
    .D(_063_),
    .Q(\mem_wb.mem_data_out [17]),
    .QN(_172_)
  );
  DFF_X1 _419_ (
    .CK(clk),
    .D(_064_),
    .Q(\mem_wb.mem_data_out [18]),
    .QN(_171_)
  );
  DFF_X1 _420_ (
    .CK(clk),
    .D(_065_),
    .Q(\mem_wb.mem_data_out [19]),
    .QN(_170_)
  );
  DFF_X1 _421_ (
    .CK(clk),
    .D(_066_),
    .Q(\mem_wb.mem_data_out [20]),
    .QN(_169_)
  );
  DFF_X1 _422_ (
    .CK(clk),
    .D(_067_),
    .Q(\mem_wb.mem_data_out [21]),
    .QN(_168_)
  );
  DFF_X1 _423_ (
    .CK(clk),
    .D(_068_),
    .Q(\mem_wb.mem_data_out [22]),
    .QN(_167_)
  );
  DFF_X1 _424_ (
    .CK(clk),
    .D(_069_),
    .Q(\mem_wb.mem_data_out [23]),
    .QN(_166_)
  );
  DFF_X1 _425_ (
    .CK(clk),
    .D(_070_),
    .Q(\mem_wb.mem_data_out [24]),
    .QN(_165_)
  );
  DFF_X1 _426_ (
    .CK(clk),
    .D(_071_),
    .Q(\mem_wb.mem_data_out [25]),
    .QN(_164_)
  );
  DFF_X1 _427_ (
    .CK(clk),
    .D(_072_),
    .Q(\mem_wb.mem_data_out [26]),
    .QN(_163_)
  );
  DFF_X1 _428_ (
    .CK(clk),
    .D(_073_),
    .Q(\mem_wb.mem_data_out [27]),
    .QN(_162_)
  );
  DFF_X1 _429_ (
    .CK(clk),
    .D(_074_),
    .Q(\mem_wb.mem_data_out [28]),
    .QN(_161_)
  );
  DFF_X1 _430_ (
    .CK(clk),
    .D(_075_),
    .Q(\mem_wb.mem_data_out [29]),
    .QN(_160_)
  );
  DFF_X1 _431_ (
    .CK(clk),
    .D(_076_),
    .Q(\mem_wb.mem_data_out [30]),
    .QN(_159_)
  );
  DFF_X1 _432_ (
    .CK(clk),
    .D(_077_),
    .Q(\mem_wb.mem_data_out [31]),
    .QN(_158_)
  );
  DFF_X1 _433_ (
    .CK(clk),
    .D(_078_),
    .Q(\mem_wb.alu_result_out [0]),
    .QN(_157_)
  );
  DFF_X1 _434_ (
    .CK(clk),
    .D(_079_),
    .Q(\mem_wb.alu_result_out [1]),
    .QN(_156_)
  );
  DFF_X1 _435_ (
    .CK(clk),
    .D(_080_),
    .Q(\mem_wb.alu_result_out [2]),
    .QN(_155_)
  );
  DFF_X1 _436_ (
    .CK(clk),
    .D(_081_),
    .Q(\mem_wb.alu_result_out [3]),
    .QN(_154_)
  );
  DFF_X1 _437_ (
    .CK(clk),
    .D(_082_),
    .Q(\mem_wb.alu_result_out [4]),
    .QN(_153_)
  );
  DFF_X1 _438_ (
    .CK(clk),
    .D(_083_),
    .Q(\mem_wb.alu_result_out [5]),
    .QN(_152_)
  );
  DFF_X1 _439_ (
    .CK(clk),
    .D(_084_),
    .Q(\mem_wb.alu_result_out [6]),
    .QN(_151_)
  );
  DFF_X1 _440_ (
    .CK(clk),
    .D(_085_),
    .Q(\mem_wb.alu_result_out [7]),
    .QN(_150_)
  );
  DFF_X1 _441_ (
    .CK(clk),
    .D(_086_),
    .Q(\mem_wb.alu_result_out [8]),
    .QN(_149_)
  );
  DFF_X1 _442_ (
    .CK(clk),
    .D(_087_),
    .Q(\mem_wb.alu_result_out [9]),
    .QN(_148_)
  );
  DFF_X1 _443_ (
    .CK(clk),
    .D(_088_),
    .Q(\mem_wb.alu_result_out [10]),
    .QN(_147_)
  );
  DFF_X1 _444_ (
    .CK(clk),
    .D(_089_),
    .Q(\mem_wb.alu_result_out [11]),
    .QN(_146_)
  );
  DFF_X1 _445_ (
    .CK(clk),
    .D(_090_),
    .Q(\mem_wb.alu_result_out [12]),
    .QN(_145_)
  );
  DFF_X1 _446_ (
    .CK(clk),
    .D(_091_),
    .Q(\mem_wb.alu_result_out [13]),
    .QN(_144_)
  );
  DFF_X1 _447_ (
    .CK(clk),
    .D(_092_),
    .Q(\mem_wb.alu_result_out [14]),
    .QN(_143_)
  );
  DFF_X1 _448_ (
    .CK(clk),
    .D(_093_),
    .Q(\mem_wb.alu_result_out [15]),
    .QN(_142_)
  );
  DFF_X1 _449_ (
    .CK(clk),
    .D(_094_),
    .Q(\mem_wb.alu_result_out [16]),
    .QN(_141_)
  );
  DFF_X1 _450_ (
    .CK(clk),
    .D(_095_),
    .Q(\mem_wb.alu_result_out [17]),
    .QN(_140_)
  );
  DFF_X1 _451_ (
    .CK(clk),
    .D(_096_),
    .Q(\mem_wb.alu_result_out [18]),
    .QN(_139_)
  );
  DFF_X1 _452_ (
    .CK(clk),
    .D(_097_),
    .Q(\mem_wb.alu_result_out [19]),
    .QN(_138_)
  );
  DFF_X1 _453_ (
    .CK(clk),
    .D(_098_),
    .Q(\mem_wb.alu_result_out [20]),
    .QN(_137_)
  );
  DFF_X1 _454_ (
    .CK(clk),
    .D(_099_),
    .Q(\mem_wb.alu_result_out [21]),
    .QN(_136_)
  );
  DFF_X1 _455_ (
    .CK(clk),
    .D(_100_),
    .Q(\mem_wb.alu_result_out [22]),
    .QN(_135_)
  );
  DFF_X1 _456_ (
    .CK(clk),
    .D(_101_),
    .Q(\mem_wb.alu_result_out [23]),
    .QN(_134_)
  );
  DFF_X1 _457_ (
    .CK(clk),
    .D(_102_),
    .Q(\mem_wb.alu_result_out [24]),
    .QN(_133_)
  );
  DFF_X1 _458_ (
    .CK(clk),
    .D(_103_),
    .Q(\mem_wb.alu_result_out [25]),
    .QN(_132_)
  );
  DFF_X1 _459_ (
    .CK(clk),
    .D(_104_),
    .Q(\mem_wb.alu_result_out [26]),
    .QN(_131_)
  );
  DFF_X1 _460_ (
    .CK(clk),
    .D(_105_),
    .Q(\mem_wb.alu_result_out [27]),
    .QN(_130_)
  );
  DFF_X1 _461_ (
    .CK(clk),
    .D(_106_),
    .Q(\mem_wb.alu_result_out [28]),
    .QN(_129_)
  );
  DFF_X1 _462_ (
    .CK(clk),
    .D(_107_),
    .Q(\mem_wb.alu_result_out [29]),
    .QN(_128_)
  );
  DFF_X1 _463_ (
    .CK(clk),
    .D(_108_),
    .Q(\mem_wb.alu_result_out [30]),
    .QN(_127_)
  );
  DFF_X1 _464_ (
    .CK(clk),
    .D(_109_),
    .Q(\mem_wb.alu_result_out [31]),
    .QN(_126_)
  );
  DFF_X1 _465_ (
    .CK(clk),
    .D(_110_),
    .Q(\mem_wb.mem_to_reg_out ),
    .QN(_125_)
  );
  DFF_X1 _466_ (
    .CK(clk),
    .D(_111_),
    .Q(\mem_wb.reg_write_out ),
    .QN(_124_)
  );
  DFF_X1 _467_ (
    .CK(clk),
    .D(_112_),
    .Q(\mem_wb.rd_out [0]),
    .QN(_123_)
  );
  DFF_X1 _468_ (
    .CK(clk),
    .D(_113_),
    .Q(\mem_wb.rd_out [1]),
    .QN(_122_)
  );
  DFF_X1 _469_ (
    .CK(clk),
    .D(_114_),
    .Q(\mem_wb.rd_out [2]),
    .QN(_121_)
  );
  DFF_X1 _470_ (
    .CK(clk),
    .D(_115_),
    .Q(\mem_wb.rd_out [3]),
    .QN(_120_)
  );
  DFF_X1 _471_ (
    .CK(clk),
    .D(_116_),
    .Q(\mem_wb.rd_out [4]),
    .QN(_119_)
  );
  assign \control_unit.flush_request  = flush_request;
  assign \control_unit.stall_request  = stall_request;
  assign \ex_mem.alu_result_in  = execute_result;
  assign \ex_mem.clk  = clk;
  assign \ex_mem.flush  = flush_request;
  assign \ex_mem.mem_to_reg_in  = \id_ex.mem_to_reg_out ;
  assign \ex_mem.rd_in  = \id_ex.rd_out ;
  assign \ex_mem.reg_write_in  = \id_ex.reg_write_out ;
  assign \ex_mem.rst  = rst;
  assign \ex_mem.stall  = 1'h0;
  assign \ex_mem.store_data_in  = execute_store_data;
  assign \ex_mem.zero_in  = execute_zero;
  assign ex_mem_alu_result = \ex_mem.alu_result_out ;
  assign ex_mem_mem_to_reg = \ex_mem.mem_to_reg_out ;
  assign ex_mem_rd = \ex_mem.rd_out ;
  assign ex_mem_reg_write = \ex_mem.reg_write_out ;
  assign \id_ex.alu_control_in  = decode_alu_control;
  assign \id_ex.alu_src_in  = decode_alu_src;
  assign \id_ex.clk  = clk;
  assign \id_ex.immediate_in  = decode_immediate;
  assign \id_ex.mem_read_in  = decode_mem_read;
  assign \id_ex.mem_to_reg_in  = decode_mem_to_reg;
  assign \id_ex.mem_write_in  = decode_mem_write;
  assign \id_ex.rd_in  = decode_rd;
  assign \id_ex.reg_write_in  = decode_reg_write;
  assign \id_ex.rs1_in  = decode_rs1;
  assign \id_ex.rs1_value_in  = decode_rs1_value;
  assign \id_ex.rs2_in  = decode_rs2;
  assign \id_ex.rs2_value_in  = decode_rs2_value;
  assign \id_ex.rst  = rst;
  assign \id_ex.stall  = 1'h0;
  assign id_ex_mem_to_reg = \id_ex.mem_to_reg_out ;
  assign id_ex_rd = \id_ex.rd_out ;
  assign id_ex_reg_write = \id_ex.reg_write_out ;
  assign \if_id.clk  = clk;
  assign \if_id.flush  = flush_request;
  assign \if_id.instruction_in  = fetch_instruction;
  assign \if_id.pc_in  = fetch_pc;
  assign \if_id.rst  = rst;
  assign \mem_wb.alu_result_in  = \ex_mem.alu_result_out ;
  assign \mem_wb.clk  = clk;
  assign \mem_wb.flush  = flush_request;
  assign \mem_wb.mem_data_in  = memory_read_data;
  assign \mem_wb.mem_to_reg_in  = \ex_mem.mem_to_reg_out ;
  assign \mem_wb.rd_in  = \ex_mem.rd_out ;
  assign \mem_wb.reg_write_in  = \ex_mem.reg_write_out ;
  assign \mem_wb.rst  = rst;
  assign \mem_wb.stall  = 1'h0;
  assign mem_wb_alu_result = \mem_wb.alu_result_out ;
  assign mem_wb_data = \mem_wb.mem_data_out ;
  assign mem_wb_mem_to_reg = \mem_wb.mem_to_reg_out ;
  assign mem_wb_rd = \mem_wb.rd_out ;
  assign mem_wb_reg_write = \mem_wb.reg_write_out ;
  assign wb_alu_result = \mem_wb.alu_result_out ;
  assign wb_mem_to_reg = \mem_wb.mem_to_reg_out ;
  assign wb_memory_data = \mem_wb.mem_data_out ;
  assign wb_rd = \mem_wb.rd_out ;
  assign wb_reg_write = \mem_wb.reg_write_out ;
endmodule
